# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_cli.banner import _DIM, _RST, cprint
from hermes_cli.config import save_env_value_secure
from hermes_constants import display_hermes_home
from typing import Any
import getpass
import queue
import time

def clarify_callback(cli: Any, question: Any, choices: Any) -> Any:
    ...

def prompt_for_secret(cli: Any, var_name: str, prompt: str, metadata: Any) -> dict:
    ...

def approval_callback(cli: Any, command: str, description: str) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import queue
import time
import getpass
import hermes_cli
import hermes_cli.banner
import hermes_cli.config
import hermes_constants
import cli
import threading