# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from hermes_cli.config import get_config_path, get_hermes_home, load_config, save_config
from hermes_cli.setup import Colors, color, print_error, print_header, print_info, print_success, prompt_yes_no
from hermes_constants import get_optional_skills_dir
from pathlib import Path
from typing import Any
import importlib.util
import logging
import subprocess
import sys

_OPENCLAW_SCRIPT = get_optional_skills_dir(PROJECT_ROOT / 'optional-skills') / 'migration' / 'openclaw-migration' / 'scripts' / 'openclaw_to_hermes.py'
_OPENCLAW_SCRIPT_INSTALLED = get_hermes_home() / 'skills' / 'migration' / 'openclaw-migration' / 'scripts' / 'openclaw_to_hermes.py'
_OPENCLAW_DIR_NAMES = ('.openclaw', '.clawdbot', '.moltbot')
def _detect_openclaw_processes() -> list[str]:
    ...

def _warn_if_openclaw_running(auto_yes: bool) -> None:
    ...

def _warn_if_gateway_running(auto_yes: bool) -> None:
    ...

_WORKSPACE_STATE_GLOBS = ('*/todo.json', '*/sessions/*', '*/memory/*.json', '*/logs/*')
def _find_migration_script() -> Path | None:
    ...

def _load_migration_module(script_path: Path) -> Any:
    ...

def _find_openclaw_dirs() -> list[Path]:
    ...

def _scan_workspace_state(source_dir: Path) -> list[tuple[Path, str]]:
    ...

def _archive_directory(source_dir: Path, dry_run: bool) -> Path:
    ...

def claw_command(args: Any) -> Any:
    ...

def _cmd_migrate(args: Any) -> Any:
    ...

def _cmd_cleanup(args: Any) -> Any:
    ...

def _print_migration_report(report: dict, dry_run: bool) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import importlib
import importlib.util
import logging
import subprocess
import sys
import datetime
import pathlib
import hermes_cli
import hermes_cli.config
import hermes_constants
import hermes_cli.setup
import gateway
import gateway.status