# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_cli.colors import Colors, color
import getpass
import sys

def print_info(text: str) -> None:
    ...

def print_success(text: str) -> None:
    ...

def print_warning(text: str) -> None:
    ...

def print_error(text: str) -> None:
    ...

def print_header(text: str) -> None:
    ...

def prompt(question: str, default: str | None, password: bool) -> str:
    ...

def prompt_yes_no(question: str, default: bool) -> bool:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import getpass
import sys
import hermes_cli
import hermes_cli.colors