# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
import os
import sys

def should_use_color() -> bool:
    ...

class Colors:
def color(text: str) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import sys