# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from pathlib import Path
from typing import Optional
import json
import logging
import os
import shutil
import subprocess
import time

COPILOT_OAUTH_CLIENT_ID = 'Ov23li8tweQw6odWQebz'
_CLASSIC_PAT_PREFIX = 'ghp_'
_SUPPORTED_PREFIXES = ('gho_', 'github_pat_', 'ghu_')
COPILOT_ENV_VARS = ('COPILOT_GITHUB_TOKEN', 'GH_TOKEN', 'GITHUB_TOKEN')
_DEVICE_CODE_POLL_INTERVAL = 5
_DEVICE_CODE_POLL_SAFETY_MARGIN = 3
def validate_copilot_token(token: str) -> tuple[bool, str]:
    ...

def resolve_copilot_token() -> tuple[str, str]:
    ...

def _gh_cli_candidates() -> list[str]:
    ...

def _try_gh_cli_token() -> Optional[str]:
    ...

def copilot_device_code_login() -> Optional[str]:
    ...

def copilot_request_headers() -> dict[str, str]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import json
import logging
import os
import shutil
import subprocess
import time
import pathlib
import typing
import urllib
import urllib.request
import urllib.parse