# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_cli.colors import Colors, color
from pathlib import Path
from typing import Any, Iterable, List, Optional
import json
import sys

def _normalize_skills(single_skill: Any, skills: Optional[Iterable[str]]) -> Optional[List[str]]:
    ...

def _cron_api() -> Any:
    ...

def cron_list(show_all: bool) -> Any:
    ...

def cron_tick() -> Any:
    ...

def cron_status() -> Any:
    ...

def cron_create(args: Any) -> Any:
    ...

def cron_edit(args: Any) -> Any:
    ...

def _job_action(action: str, job_id: str, success_verb: str) -> int:
    ...

def cron_command(args: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import sys
import pathlib
import typing
import hermes_cli
import hermes_cli.colors
import tools
import tools.cronjob_tools
import cron.jobs
import hermes_cli.gateway
import cron.scheduler