# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_constants import get_hermes_home
from pathlib import Path
from typing import Any, Optional
import io
import sys
import urllib.error
import urllib.parse
import urllib.request

_PASTE_RS_URL = 'https://paste.rs/'
_DPASTE_COM_URL = 'https://dpaste.com/api/'
_MAX_LOG_BYTES = 512000
def _upload_paste_rs(content: str) -> str:
    ...

def _upload_dpaste_com(content: str, expiry_days: int) -> str:
    ...

def upload_to_pastebin(content: str, expiry_days: int) -> str:
    ...

def _resolve_log_path(log_name: str) -> Optional[Path]:
    ...

def _read_log_tail(log_name: str, num_lines: int) -> str:
    ...

def _read_full_log(log_name: str, max_bytes: int) -> Optional[str]:
    ...

def _capture_dump() -> str:
    ...

def collect_debug_report() -> str:
    ...

def run_debug_share(args: Any) -> Any:
    ...

def run_debug(args: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import io
import sys
import urllib
import urllib.error
import urllib.parse
import urllib.request
import pathlib
import typing
import hermes_constants
import hermes_cli
import hermes_cli.logs
import hermes_cli.dump