# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from dotenv import load_dotenv
from hermes_cli.colors import Colors, color
from hermes_cli.config import get_env_path, get_hermes_home, get_project_root
from hermes_constants import OPENROUTER_MODELS_URL, display_hermes_home, is_termux
from typing import Any
import os
import shutil
import subprocess
import sys

_PROVIDER_ENV_HINTS = ('OPENROUTER_API_KEY', 'OPENAI_API_KEY', 'ANTHROPIC_API_KEY', 'ANTHROPIC_TOKEN', 'OPENAI_BASE_URL', 'NOUS_API_KEY', 'GLM_API_KEY', 'ZAI_API_KEY', 'Z_AI_API_KEY', 'KIMI_API_KEY', 'MINIMAX_API_KEY', 'MINIMAX_CN_API_KEY', 'KILOCODE_API_KEY', 'DEEPSEEK_API_KEY', 'DASHSCOPE_API_KEY', 'HF_TOKEN', 'AI_GATEWAY_API_KEY', 'OPENCODE_ZEN_API_KEY', 'OPENCODE_GO_API_KEY', 'XIAOMI_API_KEY')
def _python_install_cmd() -> str:
    ...

def _system_package_install_cmd(pkg: str) -> str:
    ...

def _termux_browser_setup_steps(node_installed: bool) -> list[str]:
    ...

def _has_provider_env_config(content: str) -> bool:
    ...

def _honcho_is_configured_for_doctor() -> bool:
    ...

def _apply_doctor_tool_availability_overrides(available: list[str], unavailable: list[dict]) -> tuple[list[str], list[dict]]:
    ...

def check_ok(text: str, detail: str) -> Any:
    ...

def check_warn(text: str, detail: str) -> Any:
    ...

def check_fail(text: str, detail: str) -> Any:
    ...

def check_info(text: str) -> Any:
    ...

def _check_gateway_service_linger(issues: list[str]) -> None:
    ...

def run_doctor(args: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import sys
import subprocess
import shutil
import hermes_cli
import hermes_cli.config
import hermes_constants
import dotenv
import dotenv.load_dotenv
import hermes_cli.colors
import plugins
import plugins.memory
import plugins.memory.honcho
import plugins.memory.honcho.client
import hermes_cli.gateway
import yaml
import utils
import hermes_cli.auth
import sqlite3
import daytona
import json
import httpx
import agent
import agent.anthropic_adapter
import agent.auxiliary_client
import tinker_atropos
import model_tools
import plugins.memory.mem0
import plugins.memory.mem0._load_config
import plugins.memory.load_memory_provider
import hermes_cli.profiles
import re