# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from dotenv import load_dotenv
from pathlib import Path
import os

def _load_dotenv_with_fallback(path: Path) -> None:
    ...

def load_hermes_dotenv() -> list[Path]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import os
import pathlib
import dotenv
import dotenv.load_dotenv