# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime, timedelta
from hermes_constants import display_hermes_home, get_hermes_home
from pathlib import Path
from typing import Optional, Sequence
import re
import sys
import time

LOG_FILES = {'agent': 'agent.log', 'errors': 'errors.log', 'gateway': 'gateway.log'}
_LEVEL_ORDER = {'DEBUG': 0, 'INFO': 1, 'WARNING': 2, 'ERROR': 3, 'CRITICAL': 4}
def _parse_since(since_str: str) -> Optional[datetime]:
    ...

def _parse_line_timestamp(line: str) -> Optional[datetime]:
    ...

def _extract_level(line: str) -> Optional[str]:
    ...

def _extract_logger_name(line: str) -> Optional[str]:
    ...

def _line_matches_component(line: str, prefixes: Sequence[str]) -> bool:
    ...

def _matches_filters(line: str) -> bool:
    ...

def tail_log(log_name: str) -> None:
    ...

def _read_tail(path: Path, num_lines: int) -> list:
    ...

def _read_last_n_lines(path: Path, n: int) -> list:
    ...

def _follow_log(path: Path) -> None:
    ...

def list_logs() -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import re
import sys
import time
import datetime
import pathlib
import typing
import hermes_constants
import hermes_logging