# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from hermes_cli import __release_date__, __version__
from hermes_cli.config import get_hermes_home, load_config
from hermes_cli.env_loader import load_hermes_dotenv
from hermes_cli.models import _PROVIDER_MODELS
from hermes_constants import OPENROUTER_BASE_URL, apply_ipv4_preference
from hermes_logging import setup_logging
from pathlib import Path
from typing import Any, Optional
import argparse
import logging
import os
import subprocess
import sys
import time

def _require_tty(command_name: str) -> None:
    ...

def _apply_profile_override() -> None:
    ...

def _relative_time(ts: Any) -> str:
    ...

def _has_any_provider_configured() -> bool:
    ...

def _session_browse_picker(sessions: list) -> Optional[str]:
    ...

def _resolve_last_cli_session() -> Optional[str]:
    ...

def _probe_container(cmd: list, backend: str, via_sudo: bool) -> Any:
    ...

def _exec_in_container(container_info: dict, cli_args: list) -> Any:
    ...

def _resolve_session_by_name_or_id(name_or_id: str) -> Optional[str]:
    ...

def cmd_chat(args: Any) -> Any:
    ...

def cmd_gateway(args: Any) -> Any:
    ...

def cmd_whatsapp(args: Any) -> Any:
    ...

def cmd_setup(args: Any) -> Any:
    ...

def cmd_model(args: Any) -> Any:
    ...

def select_provider_and_model(args: Any) -> Any:
    ...

def _clear_stale_openai_base_url() -> Any:
    ...

def _prompt_provider_choice(choices: Any) -> Any:
    ...

def _model_flow_openrouter(config: Any, current_model: Any) -> Any:
    ...

def _model_flow_nous(config: Any, current_model: Any, args: Any) -> Any:
    ...

def _model_flow_openai_codex(config: Any, current_model: Any) -> Any:
    ...

_DEFAULT_QWEN_PORTAL_MODELS = ['qwen3-coder-plus', 'qwen3-coder']
def _model_flow_qwen_oauth(_config: Any, current_model: Any) -> Any:
    ...

def _model_flow_custom(config: Any) -> Any:
    ...

def _save_custom_provider(base_url: Any, api_key: Any, model: Any, context_length: Any) -> Any:
    ...

def _remove_custom_provider(config: Any) -> Any:
    ...

def _model_flow_named_custom(config: Any, provider_info: Any) -> Any:
    ...

def _current_reasoning_effort(config: Any) -> str:
    ...

def _set_reasoning_effort(config: Any, effort: str) -> None:
    ...

def _prompt_reasoning_effort_selection(efforts: Any, current_effort: Any) -> Any:
    ...

def _model_flow_copilot(config: Any, current_model: Any) -> Any:
    ...

def _model_flow_copilot_acp(config: Any, current_model: Any) -> Any:
    ...

def _model_flow_kimi(config: Any, current_model: Any) -> Any:
    ...

def _model_flow_api_key_provider(config: Any, provider_id: Any, current_model: Any) -> Any:
    ...

def _run_anthropic_oauth_flow(save_env_value: Any) -> Any:
    ...

def _model_flow_anthropic(config: Any, current_model: Any) -> Any:
    ...

def cmd_login(args: Any) -> Any:
    ...

def cmd_logout(args: Any) -> Any:
    ...

def cmd_auth(args: Any) -> Any:
    ...

def cmd_status(args: Any) -> Any:
    ...

def cmd_cron(args: Any) -> Any:
    ...

def cmd_webhook(args: Any) -> Any:
    ...

def cmd_doctor(args: Any) -> Any:
    ...

def cmd_dump(args: Any) -> Any:
    ...

def cmd_debug(args: Any) -> Any:
    ...

def cmd_config(args: Any) -> Any:
    ...

def cmd_backup(args: Any) -> Any:
    ...

def cmd_import(args: Any) -> Any:
    ...

def cmd_version(args: Any) -> Any:
    ...

def cmd_uninstall(args: Any) -> Any:
    ...

def _clear_bytecode_cache(root: Path) -> int:
    ...

def _gateway_prompt(prompt_text: str, default: str, timeout: float) -> str:
    ...

def _build_web_ui(web_dir: Path) -> bool:
    ...

def _update_via_zip(args: Any) -> Any:
    ...

def _stash_local_changes_if_needed(git_cmd: list[str], cwd: Path) -> Optional[str]:
    ...

def _resolve_stash_selector(git_cmd: list[str], cwd: Path, stash_ref: str) -> Optional[str]:
    ...

def _print_stash_cleanup_guidance(stash_ref: str, stash_selector: Optional[str]) -> None:
    ...

def _restore_stashed_changes(git_cmd: list[str], cwd: Path, stash_ref: str, prompt_user: bool, input_fn: Any) -> bool:
    ...

OFFICIAL_REPO_URLS = {'https://github.com/NousResearch/hermes-agent.git', 'git@github.com:NousResearch/hermes-agent.git', 'https://github.com/NousResearch/hermes-agent', 'git@github.com:NousResearch/hermes-agent'}
OFFICIAL_REPO_URL = 'https://github.com/NousResearch/hermes-agent.git'
SKIP_UPSTREAM_PROMPT_FILE = '.skip_upstream_prompt'
def _get_origin_url(git_cmd: list[str], cwd: Path) -> Optional[str]:
    ...

def _is_fork(origin_url: Optional[str]) -> bool:
    ...

def _has_upstream_remote(git_cmd: list[str], cwd: Path) -> bool:
    ...

def _add_upstream_remote(git_cmd: list[str], cwd: Path) -> bool:
    ...

def _count_commits_between(git_cmd: list[str], cwd: Path, base: str, head: str) -> int:
    ...

def _should_skip_upstream_prompt() -> bool:
    ...

def _mark_skip_upstream_prompt() -> Any:
    ...

def _sync_fork_with_upstream(git_cmd: list[str], cwd: Path) -> bool:
    ...

def _sync_with_upstream_if_needed(git_cmd: list[str], cwd: Path) -> None:
    ...

def _invalidate_update_cache() -> Any:
    ...

def _load_installable_optional_extras() -> list[str]:
    ...

def _install_python_dependencies_with_optional_fallback(install_cmd_prefix: list[str]) -> None:
    ...

def cmd_update(args: Any) -> Any:
    ...

def _coalesce_session_name_args(argv: list) -> list:
    ...

def cmd_profile(args: Any) -> Any:
    ...

def cmd_dashboard(args: Any) -> Any:
    ...

def cmd_completion(args: Any) -> Any:
    ...

def cmd_logs(args: Any) -> Any:
    ...

def main() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import argparse
import os
import subprocess
import sys
import pathlib
import typing
import hermes_constants
import hermes_cli
import hermes_cli.profiles
import hermes_cli.config
import hermes_cli.env_loader
import hermes_logging
import logging
import time
import datetime
import hermes_cli.__version__
import hermes_cli.__release_date__
import hermes_cli.auth
import json
import agent
import agent.anthropic_adapter
import curses
import hermes_state
import shutil
import hermes_cli.setup
import hermes_cli.banner
import tools
import tools.skills_sync
import cli
import hermes_cli.gateway
import getpass
import hermes_cli.models
import hermes_cli.nous_subscription
import hermes_cli.codex_models
import re
import simple_term_menu
import hermes_cli.curses_ui
import hermes_cli.copilot_auth
import agent.models_dev
import hermes_cli.auth_commands
import hermes_cli.status
import hermes_cli.cron
import hermes_cli.webhook
import hermes_cli.doctor
import hermes_cli.dump
import hermes_cli.debug
import hermes_cli.backup
import openai
import hermes_cli.uninstall
import uuid
import tempfile
import zipfile
import urllib
import urllib.request
import posixpath
import tomllib
import importlib
import plugins
import plugins.memory
import plugins.memory.honcho
import plugins.memory.honcho.cli
import signal
import fastapi
import uvicorn
import hermes_cli.web_server
import hermes_cli.logs
import hermes_cli.pairing
import hermes_cli.skills_config
import hermes_cli.skills_hub
import hermes_cli.plugins_cmd
import plugins.memory.discover_plugin_cli_commands
import hermes_cli.memory_setup
import hermes_cli.tools_config
import hermes_cli.mcp_config
import agent.insights
import hermes_cli.claw
import acp_adapter
import acp_adapter.entry