# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from hermes_constants import get_hermes_home
from pathlib import Path
from typing import Any
import getpass
import os
import sys

def _curses_select(title: str, items: list[tuple[str, str]], default: int) -> int:
    ...

def _prompt(label: str, default: str | None, secret: bool) -> str:
    ...

def _install_dependencies(provider_name: str) -> None:
    ...

def _get_available_providers() -> list:
    ...

def cmd_setup_provider(provider_name: str) -> None:
    ...

def cmd_setup(args: Any) -> None:
    ...

def _write_env_vars(env_path: Path, env_writes: dict) -> None:
    ...

def cmd_status(args: Any) -> None:
    ...

def memory_command(args: Any) -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import getpass
import os
import sys
import pathlib
import hermes_constants
import hermes_cli
import hermes_cli.curses_ui
import subprocess
import yaml
import shutil
import plugins
import plugins.memory
import plugins.memory.discover_memory_providers
import plugins.memory.load_memory_provider
import hermes_cli.config