# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from agent.models_dev import ModelCapabilities, ModelInfo, get_model_capabilities, get_model_info, list_provider_models, search_models_dev
from dataclasses import dataclass
from hermes_cli.model_normalize import normalize_model_for_provider
from hermes_cli.providers import custom_provider_slug, determine_api_mode, get_label, is_aggregator, resolve_provider_full
from typing import List, NamedTuple, Optional
from dataclasses import dataclass
from typing import NamedTuple
import logging

_HERMES_MODEL_WARNING = 'Nous Research Hermes 3 & 4 models are NOT agentic and are not designed for use with Hermes Agent. They lack the tool-calling capabilities required for agent workflows. Consider using an agentic model instead (Claude, GPT, Gemini, DeepSeek, etc.).'
def _check_hermes_model_warning(model_name: str) -> str:
    ...

class ModelIdentity(NamedTuple):

MODEL_ALIASES: dict[str, ModelIdentity] = {'sonnet': ModelIdentity('anthropic', 'claude-sonnet'), 'opus': ModelIdentity('anthropic', 'claude-opus'), 'haiku': ModelIdentity('anthropic', 'claude-haiku'), 'claude': ModelIdentity('anthropic', 'claude'), 'gpt5': ModelIdentity('openai', 'gpt-5'), 'gpt': ModelIdentity('openai', 'gpt'), 'codex': ModelIdentity('openai', 'codex'), 'o3': ModelIdentity('openai', 'o3'), 'o4': ModelIdentity('openai', 'o4'), 'gemini': ModelIdentity('google', 'gemini'), 'deepseek': ModelIdentity('deepseek', 'deepseek-chat'), 'grok': ModelIdentity('x-ai', 'grok'), 'llama': ModelIdentity('meta-llama', 'llama'), 'qwen': ModelIdentity('qwen', 'qwen'), 'minimax': ModelIdentity('minimax', 'minimax'), 'nemotron': ModelIdentity('nvidia', 'nemotron'), 'kimi': ModelIdentity('moonshotai', 'kimi'), 'glm': ModelIdentity('z-ai', 'glm'), 'step': ModelIdentity('stepfun', 'step'), 'mimo': ModelIdentity('xiaomi', 'mimo'), 'trinity': ModelIdentity('arcee-ai', 'trinity')}
class DirectAlias(NamedTuple):

_BUILTIN_DIRECT_ALIASES: dict[str, DirectAlias] = {}
DIRECT_ALIASES: dict[str, DirectAlias] = {}
def _load_direct_aliases() -> dict[str, DirectAlias]:
    ...

def _ensure_direct_aliases() -> None:
    ...

@dataclass
class ModelSwitchResult:
@dataclass
class CustomAutoResult:
def parse_model_flags(raw_args: str) -> tuple[str, str, bool]:
    ...

def resolve_alias(raw_input: str, current_provider: str) -> Optional[tuple[str, str, str]]:
    ...

def get_authenticated_provider_slugs(current_provider: str, user_providers: dict, custom_providers: list | None) -> list[str]:
    ...

def _resolve_alias_fallback(raw_input: str, authenticated_providers: list[str]) -> Optional[tuple[str, str, str]]:
    ...

def switch_model(raw_input: str, current_provider: str, current_model: str, current_base_url: str, current_api_key: str, is_global: bool, explicit_provider: str, user_providers: dict, custom_providers: list | None) -> ModelSwitchResult:
    ...

def list_authenticated_providers(current_provider: str, user_providers: dict, custom_providers: list | None, max_models: int) -> List[dict]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import logging
import dataclasses
import typing
import hermes_cli
import hermes_cli.providers
import hermes_cli.model_normalize
import agent
import agent.models_dev
import hermes_cli.config
import hermes_cli.models
import hermes_cli.runtime_provider
import os
import hermes_cli.auth
import agent.credential_pool
import agent.anthropic_adapter