# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from dataclasses import dataclass
from hermes_cli.auth import get_nous_auth_status
from hermes_cli.config import get_env_value, load_config
from pathlib import Path
from tools.managed_tool_gateway import is_managed_tool_gateway_ready
from tools.tool_backend_helpers import has_direct_modal_credentials, managed_nous_tools_enabled, normalize_browser_cloud_provider, normalize_modal_mode, resolve_modal_backend_state, resolve_openai_audio_api_key
from typing import Dict, Iterable, Optional, Set
from typing_extensions import Self
from dataclasses import dataclass

_DEFAULT_PLATFORM_TOOLSETS = {'cli': 'hermes-cli'}
@dataclass
class NousFeatureState:
@dataclass
class NousSubscriptionFeatures:
    def web(self: Self) -> NousFeatureState: ...
    def image_gen(self: Self) -> NousFeatureState: ...
    def tts(self: Self) -> NousFeatureState: ...
    def browser(self: Self) -> NousFeatureState: ...
    def modal(self: Self) -> NousFeatureState: ...
    def items(self: Self) -> Iterable[NousFeatureState]: ...

def _model_config_dict(config: Dict[str, object]) -> Dict[str, object]:
    ...

def _toolset_enabled(config: Dict[str, object], toolset_key: str) -> bool:
    ...

def _has_agent_browser() -> bool:
    ...

def _browser_label(current_provider: str) -> str:
    ...

def _tts_label(current_provider: str) -> str:
    ...

def _resolve_browser_feature_state() -> tuple[str, bool, bool, bool]:
    ...

def get_nous_subscription_features(config: Optional[Dict[str, object]]) -> NousSubscriptionFeatures:
    ...

def get_nous_subscription_explainer_lines() -> list[str]:
    ...

def apply_nous_provider_defaults(config: Dict[str, object]) -> set[str]:
    ...

def apply_nous_managed_defaults(config: Dict[str, object]) -> set[str]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import dataclasses
import pathlib
import typing
import hermes_cli
import hermes_cli.auth
import hermes_cli.config
import tools
import tools.managed_tool_gateway
import tools.tool_backend_helpers
import toolsets
import shutil