# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from dataclasses import dataclass, field
from hermes_constants import get_hermes_home
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Set, Union
from typing_extensions import Self
from utils import env_var_enabled
from dataclasses import dataclass
import importlib
import importlib.metadata
import importlib.util
import logging
import os
import sys
import types
import yaml

yaml = None
VALID_HOOKS: Set[str] = {'pre_tool_call', 'post_tool_call', 'pre_llm_call', 'post_llm_call', 'pre_api_request', 'post_api_request', 'on_session_start', 'on_session_end', 'on_session_finalize', 'on_session_reset'}
ENTRY_POINTS_GROUP = 'hermes_agent.plugins'
_NS_PARENT = 'hermes_plugins'
def _env_enabled(name: str) -> bool:
    ...

def _get_disabled_plugins() -> set:
    ...

@dataclass
class PluginManifest:
@dataclass
class LoadedPlugin:
class PluginContext:
    def __init__(self: Self, manifest: PluginManifest, manager: 'PluginManager') -> None: ...
    def register_tool(self: Self, name: str, toolset: str, schema: dict, handler: Callable, check_fn: Callable | None, requires_env: list | None, is_async: bool, description: str, emoji: str) -> None: ...
    def inject_message(self: Self, content: str, role: str) -> bool: ...
    def register_cli_command(self: Self, name: str, help: str, setup_fn: Callable, handler_fn: Callable | None, description: str) -> None: ...
    def register_context_engine(self: Self, engine: Any) -> None: ...
    def register_hook(self: Self, hook_name: str, callback: Callable) -> None: ...

class PluginManager:
    def __init__(self: Self) -> None: ...
    def discover_and_load(self: Self) -> None: ...
    def _scan_directory(self: Self, path: Path, source: str) -> List[PluginManifest]: ...
    def _scan_entry_points(self: Self) -> List[PluginManifest]: ...
    def _load_plugin(self: Self, manifest: PluginManifest) -> None: ...
    def _load_directory_module(self: Self, manifest: PluginManifest) -> types.ModuleType: ...
    def _load_entrypoint_module(self: Self, manifest: PluginManifest) -> types.ModuleType: ...
    def invoke_hook(self: Self, hook_name: str) -> List[Any]: ...
    def list_plugins(self: Self) -> List[Dict[str, Any]]: ...

_plugin_manager: Optional[PluginManager] = None
def get_plugin_manager() -> PluginManager:
    ...

def discover_plugins() -> None:
    ...

def invoke_hook(hook_name: str) -> List[Any]:
    ...

def get_plugin_tool_names() -> Set[str]:
    ...

def get_plugin_cli_commands() -> Dict[str, dict]:
    ...

def get_plugin_context_engine() -> Any:
    ...

def get_plugin_toolsets() -> List[tuple]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import importlib
import importlib.util
import logging
import os
import sys
import types
import dataclasses
import pathlib
import typing
import hermes_constants
import utils
import yaml
import hermes_cli
import hermes_cli.config
import tools
import tools.registry
import agent
import agent.context_engine