# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path, PurePosixPath, PureWindowsPath
from typing import Any, List, Optional
from dataclasses import dataclass
import json
import os
import re
import shutil
import stat
import subprocess
import sys

_PROFILE_DIRS = ['memories', 'sessions', 'skills', 'skins', 'logs', 'plans', 'workspace', 'cron', 'home']
_CLONE_CONFIG_FILES = ['config.yaml', '.env', 'SOUL.md']
_CLONE_SUBDIR_FILES = ['memories/MEMORY.md', 'memories/USER.md']
_CLONE_ALL_STRIP = ['gateway.pid', 'gateway_state.json', 'processes.json']
_DEFAULT_EXPORT_EXCLUDE_ROOT = frozenset({'hermes-agent', '.worktrees', 'profiles', 'bin', 'node_modules', 'state.db', 'state.db-shm', 'state.db-wal', 'hermes_state.db', 'response_store.db', 'response_store.db-shm', 'response_store.db-wal', 'gateway.pid', 'gateway_state.json', 'processes.json', 'auth.json', '.env', 'auth.lock', 'active_profile', '.update_check', 'errors.log', '.hermes_history', 'image_cache', 'audio_cache', 'document_cache', 'browser_screenshots', 'checkpoints', 'sandboxes', 'logs'})
_RESERVED_NAMES = frozenset({'hermes', 'default', 'test', 'tmp', 'root', 'sudo'})
_HERMES_SUBCOMMANDS = frozenset({'chat', 'model', 'gateway', 'setup', 'whatsapp', 'login', 'logout', 'status', 'cron', 'doctor', 'dump', 'config', 'pairing', 'skills', 'tools', 'mcp', 'sessions', 'insights', 'version', 'update', 'uninstall', 'profile', 'plugins', 'honcho', 'acp'})
def _get_profiles_root() -> Path:
    ...

def _get_default_hermes_home() -> Path:
    ...

def _get_active_profile_path() -> Path:
    ...

def _get_wrapper_dir() -> Path:
    ...

def validate_profile_name(name: str) -> None:
    ...

def get_profile_dir(name: str) -> Path:
    ...

def profile_exists(name: str) -> bool:
    ...

def check_alias_collision(name: str) -> Optional[str]:
    ...

def _is_wrapper_dir_in_path() -> bool:
    ...

def create_wrapper_script(name: str) -> Optional[Path]:
    ...

def remove_wrapper_script(name: str) -> bool:
    ...

@dataclass
class ProfileInfo:
def _read_config_model(profile_dir: Path) -> tuple:
    ...

def _check_gateway_running(profile_dir: Path) -> bool:
    ...

def _count_skills(profile_dir: Path) -> int:
    ...

def list_profiles() -> List[ProfileInfo]:
    ...

def create_profile(name: str, clone_from: Optional[str], clone_all: bool, clone_config: bool, no_alias: bool) -> Path:
    ...

def seed_profile_skills(profile_dir: Path, quiet: bool) -> Optional[dict]:
    ...

def delete_profile(name: str, yes: bool) -> Path:
    ...

def _cleanup_gateway_service(name: str, profile_dir: Path) -> None:
    ...

def _stop_gateway_process(profile_dir: Path) -> None:
    ...

def get_active_profile() -> str:
    ...

def set_active_profile(name: str) -> None:
    ...

def get_active_profile_name() -> str:
    ...

def _default_export_ignore(root_dir: Path) -> Any:
    ...

def export_profile(name: str, output_path: str) -> Path:
    ...

def _normalize_profile_archive_parts(member_name: str) -> List[str]:
    ...

def _safe_extract_profile_archive(archive: Path, destination: Path) -> None:
    ...

def import_profile(archive_path: str, name: Optional[str]) -> Path:
    ...

def rename_profile(old_name: str, new_name: str) -> Path:
    ...

def generate_bash_completion() -> str:
    ...

def generate_zsh_completion() -> str:
    ...

def resolve_profile_env(profile_name: str) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import os
import re
import shutil
import stat
import subprocess
import sys
import dataclasses
import pathlib
import typing
import hermes_constants
import yaml
import hermes_cli
import hermes_cli.default_soul
import platform
import hermes_cli.gateway
import signal
import time
import tempfile
import tarfile