# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from agent.credential_pool import CredentialPool, PooledCredential, get_custom_provider_pool_key, load_pool
from hermes_cli import auth
from hermes_cli.auth import AuthError, DEFAULT_CODEX_BASE_URL, DEFAULT_QWEN_BASE_URL, PROVIDER_REGISTRY, _agent_key_is_usable, format_auth_error, has_usable_secret, resolve_api_key_provider_credentials, resolve_codex_runtime_credentials, resolve_external_process_provider_credentials, resolve_nous_runtime_credentials, resolve_provider, resolve_qwen_runtime_credentials
from hermes_cli.config import load_config
from hermes_constants import OPENROUTER_BASE_URL
from typing import Any, Dict, Optional
import logging
import os
import re

def _normalize_custom_provider_name(value: str) -> str:
    ...

def _detect_api_mode_for_url(base_url: str) -> Optional[str]:
    ...

def _auto_detect_local_model(base_url: str) -> str:
    ...

def _get_model_config() -> Dict[str, Any]:
    ...

def _provider_supports_explicit_api_mode(provider: Optional[str], configured_provider: Optional[str]) -> bool:
    ...

def _copilot_runtime_api_mode(model_cfg: Dict[str, Any], api_key: str) -> str:
    ...

_VALID_API_MODES = {'chat_completions', 'codex_responses', 'anthropic_messages'}
def _parse_api_mode(raw: Any) -> Optional[str]:
    ...

def _resolve_runtime_from_pool_entry() -> Dict[str, Any]:
    ...

def resolve_requested_provider(requested: Optional[str]) -> str:
    ...

def _try_resolve_from_custom_pool(base_url: str, provider_label: str, api_mode_override: Optional[str]) -> Optional[Dict[str, Any]]:
    ...

def _get_named_custom_provider(requested_provider: str) -> Optional[Dict[str, Any]]:
    ...

def _resolve_named_custom_runtime() -> Optional[Dict[str, Any]]:
    ...

def _resolve_openrouter_runtime() -> Dict[str, Any]:
    ...

def _resolve_explicit_runtime() -> Optional[Dict[str, Any]]:
    ...

def resolve_runtime_provider() -> Dict[str, Any]:
    ...

def format_runtime_provider_error(error: Exception) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import logging
import os
import re
import typing
import hermes_cli
import hermes_cli.auth
import agent
import agent.credential_pool
import hermes_cli.config
import hermes_constants
import requests
import hermes_cli.models
import agent.anthropic_adapter