# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_constants import display_hermes_home
from pathlib import Path
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from typing import Any, Dict, Optional
import json
import shutil

def _resolve_short_name(name: str, sources: Any, console: Console) -> str:
    ...

def _format_extra_metadata_lines(extra: Dict[str, Any]) -> list[str]:
    ...

def _resolve_source_meta_and_bundle(identifier: str, sources: Any) -> Any:
    ...

def _derive_category_from_install_path(install_path: str) -> str:
    ...

def do_search(query: str, source: str, limit: int, console: Optional[Console]) -> None:
    ...

def do_browse(page: int, page_size: int, source: str, console: Optional[Console]) -> None:
    ...

def do_install(identifier: str, category: str, force: bool, console: Optional[Console], skip_confirm: bool, invalidate_cache: bool) -> None:
    ...

def do_inspect(identifier: str, console: Optional[Console]) -> None:
    ...

def do_list(source_filter: str, console: Optional[Console]) -> None:
    ...

def do_check(name: Optional[str], console: Optional[Console]) -> None:
    ...

def do_update(name: Optional[str], console: Optional[Console]) -> None:
    ...

def do_audit(name: Optional[str], console: Optional[Console]) -> None:
    ...

def do_uninstall(name: str, console: Optional[Console], skip_confirm: bool, invalidate_cache: bool) -> None:
    ...

def do_tap(action: str, repo: str, console: Optional[Console]) -> None:
    ...

def do_publish(skill_path: str, target: str, repo: str, console: Optional[Console]) -> None:
    ...

def _github_publish(skill_path: Path, skill_name: str, target_repo: str, auth: Any) -> tuple:
    ...

def do_snapshot_export(output_path: str, console: Optional[Console]) -> None:
    ...

def do_snapshot_import(input_path: str, force: bool, console: Optional[Console]) -> None:
    ...

def skills_command(args: Any) -> None:
    ...

def handle_skills_slash(cmd: str, console: Optional[Console]) -> None:
    ...

def _print_skills_help(console: Console) -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import shutil
import pathlib
import typing
import rich
import rich.console
import rich.panel
import rich.table
import hermes_constants
import tools
import tools.skills_hub
import tools.skills_guard
import agent
import agent.prompt_builder
import tools.skills_sync
import tools.skills_tool
import yaml
import re
import httpx
import base64
import datetime
import sys