# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_cli.auth import AuthError, resolve_provider
from hermes_cli.colors import Colors, color
from hermes_cli.config import get_env_path, get_env_value, get_hermes_home, load_config
from hermes_cli.models import provider_label
from hermes_cli.nous_subscription import get_nous_subscription_features
from hermes_cli.runtime_provider import resolve_requested_provider
from hermes_constants import OPENROUTER_MODELS_URL, is_termux
from pathlib import Path
from tools.tool_backend_helpers import managed_nous_tools_enabled
from typing import Any
import os
import subprocess
import sys

def check_mark(ok: bool) -> str:
    ...

def redact_key(key: str) -> str:
    ...

def _format_iso_timestamp(value: Any) -> str:
    ...

def _configured_model_label(config: dict) -> str:
    ...

def _effective_provider_label() -> str:
    ...

def show_status(args: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import sys
import subprocess
import pathlib
import hermes_cli
import hermes_cli.auth
import hermes_cli.colors
import hermes_cli.config
import hermes_cli.models
import hermes_cli.nous_subscription
import hermes_cli.runtime_provider
import hermes_constants
import tools
import tools.tool_backend_helpers
import datetime
import hermes_cli.gateway
import json
import httpx
import socket