# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_constants import display_hermes_home
from pathlib import Path
from typing import Any, Dict
import json
import os
import re
import secrets
import time

_SUBSCRIPTIONS_FILENAME = 'webhook_subscriptions.json'
def _hermes_home() -> Path:
    ...

def _subscriptions_path() -> Path:
    ...

def _load_subscriptions() -> Dict[str, dict]:
    ...

def _save_subscriptions(subs: Dict[str, dict]) -> None:
    ...

def _get_webhook_config() -> dict:
    ...

def _is_webhook_enabled() -> bool:
    ...

def _get_webhook_base_url() -> str:
    ...

def _setup_hint() -> str:
    ...

def _require_webhook_enabled() -> bool:
    ...

def webhook_command(args: Any) -> Any:
    ...

def _cmd_subscribe(args: Any) -> Any:
    ...

def _cmd_list(args: Any) -> Any:
    ...

def _cmd_remove(args: Any) -> Any:
    ...

def _cmd_test(args: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import os
import re
import secrets
import time
import pathlib
import typing
import hermes_constants
import hermes_cli
import hermes_cli.config
import hmac
import hashlib
import urllib
import urllib.request