# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict
from typing_extensions import Self
from dataclasses import dataclass

PINNED_THRESHOLDS: Dict[str, float] = {'read_file': float('inf')}
DEFAULT_RESULT_SIZE_CHARS: int = 100000
DEFAULT_TURN_BUDGET_CHARS: int = 200000
DEFAULT_PREVIEW_SIZE_CHARS: int = 1500
@dataclass
class BudgetConfig:
    def resolve_threshold(self: Self, tool_name: str) -> int | float: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import dataclasses
import typing
import tools
import tools.registry