# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_constants import get_hermes_home
from pathlib import Path
from typing import Any, Dict, List, Optional, Set
from typing_extensions import Self
import hashlib
import logging
import os
import re
import shutil
import subprocess

CHECKPOINT_BASE = get_hermes_home() / 'checkpoints'
DEFAULT_EXCLUDES = ['node_modules/', 'dist/', 'build/', '.env', '.env.*', '.env.local', '.env.*.local', '__pycache__/', '*.pyc', '*.pyo', '.DS_Store', '*.log', '.cache/', '.next/', '.nuxt/', 'coverage/', '.pytest_cache/', '.venv/', 'venv/', '.git/']
_GIT_TIMEOUT: int = max(10, min(60, int(os.getenv('HERMES_CHECKPOINT_TIMEOUT', '30'))))
_MAX_FILES = 50000
def _validate_commit_hash(commit_hash: str) -> Optional[str]:
    ...

def _validate_file_path(file_path: str, working_dir: str) -> Optional[str]:
    ...

def _normalize_path(path_value: str) -> Path:
    ...

def _shadow_repo_path(working_dir: str) -> Path:
    ...

def _git_env(shadow_repo: Path, working_dir: str) -> dict:
    ...

def _run_git(args: List[str], shadow_repo: Path, working_dir: str, timeout: int, allowed_returncodes: Optional[Set[int]]) -> tuple:
    ...

def _init_shadow_repo(shadow_repo: Path, working_dir: str) -> Optional[str]:
    ...

def _dir_file_count(path: str) -> int:
    ...

class CheckpointManager:
    def __init__(self: Self, enabled: bool, max_snapshots: int) -> None: ...
    def new_turn(self: Self) -> None: ...
    def ensure_checkpoint(self: Self, working_dir: str, reason: str) -> bool: ...
    def list_checkpoints(self: Self, working_dir: str) -> List[Dict]: ...
    @staticmethod
    def _parse_shortstat(stat_line: str, entry: Dict) -> None: ...
    def diff(self: Self, working_dir: str, commit_hash: str) -> Dict: ...
    def restore(self: Self, working_dir: str, commit_hash: str, file_path: str) -> Dict: ...
    def get_working_dir_for_path(self: Self, file_path: str) -> str: ...
    def _take(self: Self, working_dir: str, reason: str) -> bool: ...
    def _prune(self: Self, shadow_repo: Path, working_dir: str) -> None: ...

def format_checkpoint_list(checkpoints: List[Dict], directory: str) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import hashlib
import logging
import os
import re
import shutil
import subprocess
import pathlib
import hermes_constants
import typing
import posixpath