# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from tools.registry import registry, tool_error
from typing import Callable, List, Optional
import json

MAX_CHOICES = 4
def clarify_tool(question: str, choices: Optional[List[str]], callback: Optional[Callable]) -> str:
    ...

def check_clarify_requirements() -> bool:
    ...

CLARIFY_SCHEMA = {'name': 'clarify', 'description': "Ask the user a question when you need clarification, feedback, or a decision before proceeding. Supports two modes:\n\n1. **Multiple choice** — provide up to 4 choices. The user picks one or types their own answer via a 5th 'Other' option.\n2. **Open-ended** — omit choices entirely. The user types a free-form response.\n\nUse this tool when:\n- The task is ambiguous and you need the user to choose an approach\n- You want post-task feedback ('How did that work out?')\n- You want to offer to save a skill or update memory\n- A decision has meaningful trade-offs the user should weigh in on\n\nDo NOT use this tool for simple yes/no confirmation of dangerous commands (the terminal tool handles that). Prefer making a reasonable default choice yourself when the decision is low-stakes.", 'parameters': {'type': 'object', 'properties': {'question': {'type': 'string', 'description': 'The question to present to the user.'}, 'choices': {'type': 'array', 'items': {'type': 'string'}, 'maxItems': MAX_CHOICES, 'description': "Up to 4 answer choices. Omit this parameter entirely to ask an open-ended question. When provided, the UI automatically appends an 'Other (type your answer)' option."}}, 'required': ['question']}}

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import typing
import tools
import tools.registry