# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from tools.registry import registry, tool_error
from typing import Any, Dict, List, Optional
import base64
import json
import logging
import os
import platform
import shlex
import signal
import socket
import subprocess
import sys
import tempfile
import threading
import time
import uuid

_IS_WINDOWS = platform.system() == 'Windows'
SANDBOX_AVAILABLE = sys.platform != 'win32'
SANDBOX_ALLOWED_TOOLS = frozenset(['web_search', 'web_extract', 'read_file', 'write_file', 'search_files', 'patch', 'terminal'])
DEFAULT_TIMEOUT = 300
DEFAULT_MAX_TOOL_CALLS = 50
MAX_STDOUT_BYTES = 50000
MAX_STDERR_BYTES = 10000
def check_sandbox_requirements() -> bool:
    ...

_TOOL_STUBS = {'web_search': ('web_search', 'query: str, limit: int = 5', '"""Search the web. Returns dict with data.web list of {url, title, description}."""', '{"query": query, "limit": limit}'), 'web_extract': ('web_extract', 'urls: list', '"""Extract content from URLs. Returns dict with results list of {url, title, content, error}."""', '{"urls": urls}'), 'read_file': ('read_file', 'path: str, offset: int = 1, limit: int = 500', '"""Read a file (1-indexed lines). Returns dict with "content" and "total_lines"."""', '{"path": path, "offset": offset, "limit": limit}'), 'write_file': ('write_file', 'path: str, content: str', '"""Write content to a file (always overwrites). Returns dict with status."""', '{"path": path, "content": content}'), 'search_files': ('search_files', 'pattern: str, target: str = "content", path: str = ".", file_glob: str = None, limit: int = 50, offset: int = 0, output_mode: str = "content", context: int = 0', '"""Search file contents (target="content") or find files by name (target="files"). Returns dict with "matches"."""', '{"pattern": pattern, "target": target, "path": path, "file_glob": file_glob, "limit": limit, "offset": offset, "output_mode": output_mode, "context": context}'), 'patch': ('patch', 'path: str = None, old_string: str = None, new_string: str = None, replace_all: bool = False, mode: str = "replace", patch: str = None', '"""Targeted find-and-replace (mode="replace") or V4A multi-file patches (mode="patch"). Returns dict with status."""', '{"path": path, "old_string": old_string, "new_string": new_string, "replace_all": replace_all, "mode": mode, "patch": patch}'), 'terminal': ('terminal', 'command: str, timeout: int = None, workdir: str = None', '"""Run a shell command (foreground only). Returns dict with "output" and "exit_code"."""', '{"command": command, "timeout": timeout, "workdir": workdir}')}
def generate_hermes_tools_module(enabled_tools: List[str], transport: str) -> str:
    ...

_COMMON_HELPERS = '\n# ---------------------------------------------------------------------------\n# Convenience helpers (avoid common scripting pitfalls)\n# ---------------------------------------------------------------------------\n\ndef json_parse(text: str):\n    """Parse JSON tolerant of control characters (strict=False).\n    Use this instead of json.loads() when parsing output from terminal()\n    or web_extract() that may contain raw tabs/newlines in strings."""\n    return json.loads(text, strict=False)\n\n\ndef shell_quote(s: str) -> str:\n    """Shell-escape a string for safe interpolation into commands.\n    Use this when inserting dynamic content into terminal() commands:\n        terminal(f"echo {shell_quote(user_input)}")\n    """\n    return shlex.quote(s)\n\n\ndef retry(fn, max_attempts=3, delay=2):\n    """Retry a function up to max_attempts times with exponential backoff.\n    Use for transient failures (network errors, API rate limits):\n        result = retry(lambda: terminal("gh issue list ..."))\n    """\n    last_err = None\n    for attempt in range(max_attempts):\n        try:\n            return fn()\n        except Exception as e:\n            last_err = e\n            if attempt < max_attempts - 1:\n                time.sleep(delay * (2 ** attempt))\n    raise last_err\n\n'
_UDS_TRANSPORT_HEADER = '"""Auto-generated Hermes tools RPC stubs."""\nimport json, os, socket, shlex, time\n\n_sock = None\n' + _COMMON_HELPERS + '\ndef _connect():\n    global _sock\n    if _sock is None:\n        _sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)\n        _sock.connect(os.environ["HERMES_RPC_SOCKET"])\n        _sock.settimeout(300)\n    return _sock\n\ndef _call(tool_name, args):\n    """Send a tool call to the parent process and return the parsed result."""\n    conn = _connect()\n    request = json.dumps({"tool": tool_name, "args": args}) + "\\n"\n    conn.sendall(request.encode())\n    buf = b""\n    while True:\n        chunk = conn.recv(65536)\n        if not chunk:\n            raise RuntimeError("Agent process disconnected")\n        buf += chunk\n        if buf.endswith(b"\\n"):\n            break\n    raw = buf.decode().strip()\n    result = json.loads(raw)\n    if isinstance(result, str):\n        try:\n            return json.loads(result)\n        except (json.JSONDecodeError, TypeError):\n            return result\n    return result\n\n'
_FILE_TRANSPORT_HEADER = '"""Auto-generated Hermes tools RPC stubs (file-based transport)."""\nimport json, os, shlex, tempfile, time\n\n_RPC_DIR = os.environ.get("HERMES_RPC_DIR") or os.path.join(tempfile.gettempdir(), "hermes_rpc")\n_seq = 0\n' + _COMMON_HELPERS + '\ndef _call(tool_name, args):\n    """Send a tool call request via file-based RPC and wait for response."""\n    global _seq\n    _seq += 1\n    seq_str = f"{_seq:06d}"\n    req_file = os.path.join(_RPC_DIR, f"req_{seq_str}")\n    res_file = os.path.join(_RPC_DIR, f"res_{seq_str}")\n\n    # Write request atomically (write to .tmp, then rename)\n    tmp = req_file + ".tmp"\n    with open(tmp, "w") as f:\n        json.dump({"tool": tool_name, "args": args, "seq": _seq}, f)\n    os.rename(tmp, req_file)\n\n    # Wait for response with adaptive polling\n    deadline = time.monotonic() + 300  # 5-minute timeout per tool call\n    poll_interval = 0.05  # Start at 50ms\n    while not os.path.exists(res_file):\n        if time.monotonic() > deadline:\n            raise RuntimeError(f"RPC timeout: no response for {tool_name} after 300s")\n        time.sleep(poll_interval)\n        poll_interval = min(poll_interval * 1.2, 0.25)  # Back off to 250ms\n\n    with open(res_file) as f:\n        raw = f.read()\n\n    # Clean up response file\n    try:\n        os.unlink(res_file)\n    except OSError:\n        pass\n\n    result = json.loads(raw)\n    if isinstance(result, str):\n        try:\n            return json.loads(result)\n        except (json.JSONDecodeError, TypeError):\n            return result\n    return result\n\n'
_TERMINAL_BLOCKED_PARAMS = {'background', 'pty', 'notify_on_complete', 'watch_patterns'}
def _rpc_server_loop(server_sock: socket.socket, task_id: str, tool_call_log: list, tool_call_counter: list, max_tool_calls: int, allowed_tools: frozenset) -> Any:
    ...

def _get_or_create_env(task_id: str) -> Any:
    ...

def _ship_file_to_remote(env: Any, remote_path: str, content: str) -> None:
    ...

def _env_temp_dir(env: Any) -> str:
    ...

def _rpc_poll_loop(env: Any, rpc_dir: str, task_id: str, tool_call_log: list, tool_call_counter: list, max_tool_calls: int, allowed_tools: frozenset, stop_event: threading.Event) -> Any:
    ...

def _execute_remote(code: str, task_id: Optional[str], enabled_tools: Optional[List[str]]) -> str:
    ...

def execute_code(code: str, task_id: Optional[str], enabled_tools: Optional[List[str]]) -> str:
    ...

def _kill_process_group(proc: Any, escalate: bool) -> Any:
    ...

def _load_config() -> dict:
    ...

_TOOL_DOC_LINES = [('web_search', '  web_search(query: str, limit: int = 5) -> dict\n    Returns {"data": {"web": [{"url", "title", "description"}, ...]}}'), ('web_extract', '  web_extract(urls: list[str]) -> dict\n    Returns {"results": [{"url", "title", "content", "error"}, ...]} where content is markdown'), ('read_file', '  read_file(path: str, offset: int = 1, limit: int = 500) -> dict\n    Lines are 1-indexed. Returns {"content": "...", "total_lines": N}'), ('write_file', '  write_file(path: str, content: str) -> dict\n    Always overwrites the entire file.'), ('search_files', '  search_files(pattern: str, target="content", path=".", file_glob=None, limit=50) -> dict\n    target: "content" (search inside files) or "files" (find files by name). Returns {"matches": [...]}'), ('patch', '  patch(path: str, old_string: str, new_string: str, replace_all: bool = False) -> dict\n    Replaces old_string with new_string in the file.'), ('terminal', '  terminal(command: str, timeout=None, workdir=None) -> dict\n    Foreground only (no background/pty). Returns {"output": "...", "exit_code": N}')]
def build_execute_code_schema(enabled_sandbox_tools: set) -> dict:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import base64
import json
import logging
import os
import platform
import shlex
import signal
import socket
import subprocess
import sys
import tempfile
import threading
import time
import uuid
import typing
import model_tools
import tools
import tools.terminal_tool
import tools.ansi_strip
import agent
import agent.redact
import tools.interrupt
import posixpath
import tools.env_passthrough
import hermes_constants
import collections
import collections.deque
import shutil
import cli
import tools.registry