# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_constants import get_hermes_home
from typing import Any, Dict
from typing_extensions import Self
import datetime
import json
import logging
import os
import uuid

class DebugSession:
    def __init__(self: Self, tool_name: str) -> None: ...
    def active(self: Self) -> bool: ...
    def log_call(self: Self, call_name: str, call_data: Dict[str, Any]) -> None: ...
    def save(self: Self) -> None: ...
    def get_session_info(self: Self) -> Dict[str, Any]: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import datetime
import json
import logging
import os
import uuid
import typing
import hermes_constants