# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from contextvars import ContextVar
from pathlib import Path
from typing import Iterable
import logging
import os

_allowed_env_vars_var: ContextVar[set[str]] = ContextVar('_allowed_env_vars')
def _get_allowed() -> set[str]:
    ...

_config_passthrough: frozenset[str] | None = None
def register_env_passthrough(var_names: Iterable[str]) -> None:
    ...

def _load_config_passthrough() -> frozenset[str]:
    ...

def is_env_passthrough(var_name: str) -> bool:
    ...

def get_all_passthrough() -> frozenset[str]:
    ...

def clear_env_passthrough() -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import logging
import os
import contextvars
import pathlib
import typing
import hermes_cli
import hermes_cli.config