# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from dataclasses import dataclass
from datetime import datetime, timezone
from hermes_constants import get_hermes_home
from tools.tool_backend_helpers import managed_nous_tools_enabled
from typing import Any, Callable, Optional
from dataclasses import dataclass
import json
import logging
import os

_DEFAULT_TOOL_GATEWAY_DOMAIN = 'nousresearch.com'
_DEFAULT_TOOL_GATEWAY_SCHEME = 'https'
_NOUS_ACCESS_TOKEN_REFRESH_SKEW_SECONDS = 120
@dataclass
class ManagedToolGatewayConfig:
def auth_json_path() -> Any:
    ...

def _read_nous_provider_state() -> Optional[dict]:
    ...

def _parse_timestamp(value: object) -> Optional[datetime]:
    ...

def _access_token_is_expiring(expires_at: object, skew_seconds: int) -> bool:
    ...

def read_nous_access_token() -> Optional[str]:
    ...

def get_tool_gateway_scheme() -> str:
    ...

def build_vendor_gateway_url(vendor: str) -> str:
    ...

def resolve_managed_tool_gateway(vendor: str, gateway_builder: Optional[Callable[[str], str]], token_reader: Optional[Callable[[], Optional[str]]]) -> Optional[ManagedToolGatewayConfig]:
    ...

def is_managed_tool_gateway_ready(vendor: str, gateway_builder: Optional[Callable[[str], str]], token_reader: Optional[Callable[[], Optional[str]]]) -> bool:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import json
import logging
import os
import datetime
import dataclasses
import typing
import hermes_constants
import tools
import tools.tool_backend_helpers
import hermes_cli
import hermes_cli.auth