# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from http.server import BaseHTTPRequestHandler, HTTPServer
from mcp.client.auth import OAuthClientProvider
from mcp.shared.auth import OAuthClientInformationFull, OAuthClientMetadata, OAuthToken
from pathlib import Path
from pydantic import AnyUrl
from typing import Any
from typing_extensions import Self
from urllib.parse import parse_qs, urlparse
import asyncio
import json
import logging
import os
import re
import socket
import sys
import threading
import webbrowser

_OAUTH_AVAILABLE = False
_OAUTH_AVAILABLE = True
class OAuthNonInteractiveError(RuntimeError):
_oauth_port: int | None = None
def _get_token_dir() -> Path:
    ...

def _safe_filename(name: str) -> str:
    ...

def _find_free_port() -> int:
    ...

def _is_interactive() -> bool:
    ...

def _can_open_browser() -> bool:
    ...

def _read_json(path: Path) -> dict | None:
    ...

def _write_json(path: Path, data: dict) -> None:
    ...

class HermesTokenStorage:
    def __init__(self: Self, server_name: str) -> None: ...
    def _tokens_path(self: Self) -> Path: ...
    def _client_info_path(self: Self) -> Path: ...
    def remove(self: Self) -> None: ...
    def has_cached_tokens(self: Self) -> bool: ...

def _make_callback_handler() -> tuple[type, dict]:
    ...

msg = f'\n  MCP OAuth: authorization required.\n  Open this URL in your browser:\n\n    {authorization_url}\n'
timeout = 300.0
poll_interval = 0.5
elapsed = 0.0
def remove_oauth_tokens(server_name: str) -> None:
    ...

def build_oauth_auth(server_name: str, server_url: str, oauth_config: dict | None) -> 'OAuthClientProvider | None':
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import json
import logging
import os
import re
import socket
import sys
import threading
import webbrowser
import http
import http.server
import pathlib
import typing
import urllib
import urllib.parse
import mcp
import mcp.client
import mcp.client.auth
import mcp.client.auth.OAuthClientProvider
import mcp.shared
import mcp.shared.auth
import pydantic
import pydantic.networks
import hermes_constants