# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from agent.auxiliary_client import extract_content_or_reasoning
from tools.debug_helpers import DebugSession
from tools.openrouter_client import check_api_key, get_async_client
from tools.registry import registry
from typing import Any, Dict, List, Optional
import asyncio
import datetime
import json
import logging
import os

REFERENCE_MODELS = ['anthropic/claude-opus-4.6', 'google/gemini-3-pro-preview', 'openai/gpt-5.4-pro', 'deepseek/deepseek-v3.2']
AGGREGATOR_MODEL = 'anthropic/claude-opus-4.6'
REFERENCE_TEMPERATURE = 0.6
AGGREGATOR_TEMPERATURE = 0.4
MIN_SUCCESSFUL_REFERENCES = 1
AGGREGATOR_SYSTEM_PROMPT = 'You have been provided with a set of responses from various open-source models to the latest user query. Your task is to synthesize these responses into a single, high-quality response. It is crucial to critically evaluate the information provided in these responses, recognizing that some of it may be biased or incorrect. Your response should not simply replicate the given answers but should offer a refined, accurate, and comprehensive reply to the instruction. Ensure your response is well-structured, coherent, and adheres to the highest standards of accuracy and reliability.\n\nResponses from models:'
def _construct_aggregator_prompt(system_prompt: str, responses: List[str]) -> str:
    ...

api_params = {'model': model, 'messages': [{'role': 'user', 'content': user_prompt}], 'extra_body': {'reasoning': {'enabled': True, 'effort': 'xhigh'}}}
api_params: temperature
response = await _get_openrouter_client().chat.completions.create(**api_params)
error_msg = f'{model} failed after {max_retries} attempts: {error_str}'
api_params = {'model': AGGREGATOR_MODEL, 'messages': [{'role': 'system', 'content': system_prompt}, {'role': 'user', 'content': user_prompt}], 'extra_body': {'reasoning': {'enabled': True, 'effort': 'xhigh'}}}
api_params: temperature
response = await _get_openrouter_client().chat.completions.create(**api_params)
response = await _get_openrouter_client().chat.completions.create(**api_params)
debug_call_data = {'parameters': {'user_prompt': user_prompt[:200] + '...' if len(user_prompt) > 200 else user_prompt, 'reference_models': reference_models or REFERENCE_MODELS, 'aggregator_model': aggregator_model or AGGREGATOR_MODEL, 'reference_temperature': REFERENCE_TEMPERATURE, 'aggregator_temperature': AGGREGATOR_TEMPERATURE, 'min_successful_references': MIN_SUCCESSFUL_REFERENCES}, 'error': None, 'success': False, 'reference_responses_count': 0, 'failed_models_count': 0, 'failed_models': [], 'final_response_length': 0, 'processing_time_seconds': 0, 'models_used': {}}
ref_models = reference_models or REFERENCE_MODELS
agg_model = aggregator_model or AGGREGATOR_MODEL
model_results = await asyncio.gather(*[_run_reference_model_safe(model, user_prompt, REFERENCE_TEMPERATURE) for model in ref_models])
successful_responses = []
failed_models = []
debug_call_data: successful_count
debug_call_data: failed_count
debug_call_data: failed_models
final_response = await _run_aggregator_model(aggregator_system_prompt, user_prompt, AGGREGATOR_TEMPERATURE)
result = {'success': True, 'response': final_response, 'models_used': {'reference_models': ref_models, 'aggregator_model': agg_model}}
debug_call_data: True
debug_call_data: len(final_response)
debug_call_data: processing_time
debug_call_data: result['models_used']
error_msg = f'Error in MoA processing: {str(e)}'
result = {'success': False, 'response': 'MoA processing failed. Please try again or use a single model for this query.', 'models_used': {'reference_models': reference_models or REFERENCE_MODELS, 'aggregator_model': aggregator_model or AGGREGATOR_MODEL}, 'error': error_msg}
debug_call_data: error_msg
debug_call_data: processing_time
def check_moa_requirements() -> bool:
    ...

def get_debug_session_info() -> Dict[str, Any]:
    ...

def get_available_models() -> Dict[str, List[str]]:
    ...

def get_moa_configuration() -> Dict[str, Any]:
    ...

MOA_SCHEMA = {'name': 'mixture_of_agents', 'description': 'Route a hard problem through multiple frontier LLMs collaboratively. Makes 5 API calls (4 reference models + 1 aggregator) with maximum reasoning effort — use sparingly for genuinely difficult problems. Best for: complex math, advanced algorithms, multi-step analytical reasoning, problems benefiting from diverse perspectives.', 'parameters': {'type': 'object', 'properties': {'user_prompt': {'type': 'string', 'description': 'The complex query or problem to solve using multiple AI models. Should be a challenging problem that benefits from diverse perspectives and collaborative reasoning.'}}, 'required': ['user_prompt']}}

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import logging
import os
import asyncio
import datetime
import typing
import tools
import tools.openrouter_client
import agent
import agent.auxiliary_client
import tools.debug_helpers
import tools.registry