# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, List, Optional, Tuple
from dataclasses import dataclass
import difflib
import re

class OperationType(Enum):
@dataclass
class HunkLine:
@dataclass
class Hunk:
@dataclass
class PatchOperation:
def parse_v4a_patch(patch_content: str) -> Tuple[List[PatchOperation], Optional[str]]:
    ...

def _count_occurrences(text: str, pattern: str) -> int:
    ...

def _validate_operations(operations: List[PatchOperation], file_ops: Any) -> List[str]:
    ...

def apply_v4a_operations(operations: List[PatchOperation], file_ops: Any) -> 'PatchResult':
    ...

def _apply_add(op: PatchOperation, file_ops: Any) -> Tuple[bool, str]:
    ...

def _apply_delete(op: PatchOperation, file_ops: Any) -> Tuple[bool, str]:
    ...

def _apply_move(op: PatchOperation, file_ops: Any) -> Tuple[bool, str]:
    ...

def _apply_update(op: PatchOperation, file_ops: Any) -> Tuple[bool, str]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import difflib
import re
import dataclasses
import typing
import enum
import tools
import tools.fuzzy_match
import tools.file_operations