# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from typing import Optional
import logging

def validate_within_dir(path: Path, root: Path) -> Optional[str]:
    ...

def has_traversal_component(path_str: str) -> bool:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import pathlib
import typing