# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from dataclasses import dataclass
from datetime import datetime
from hermes_constants import get_hermes_home
from pathlib import Path
from tools.registry import registry
from typing import Any, Dict, List, Optional
from typing_extensions import TypeAlias
from dataclasses import dataclass
import ast
import asyncio
import copy
import importlib.util
import json
import logging
import os
import subprocess
import sys
import time
import uuid
import wandb
import yaml

HERMES_ROOT = Path(__file__).parent.parent
TINKER_ATROPOS_ROOT = HERMES_ROOT / 'tinker-atropos'
ENVIRONMENTS_DIR = TINKER_ATROPOS_ROOT / 'tinker_atropos' / 'environments'
CONFIGS_DIR = TINKER_ATROPOS_ROOT / 'configs'
LOGS_DIR = get_hermes_home() / 'logs' / 'rl_training'
def _ensure_logs_dir() -> Any:
    ...

LOCKED_FIELDS = {'env': {'tokenizer_name': 'Qwen/Qwen3-8B', 'rollout_server_url': 'http://localhost:8000', 'use_wandb': True, 'max_token_length': 8192, 'max_num_workers': 2048, 'worker_timeout': 3600, 'total_steps': 2500, 'steps_per_eval': 25, 'max_batches_offpolicy': 3, 'inference_weight': 1.0, 'eval_limit_ratio': 0.1}, 'openai': [{'model_name': 'Qwen/Qwen3-8B', 'base_url': 'http://localhost:8001/v1', 'api_key': 'x', 'weight': 1.0, 'num_requests_for_eval': 256, 'timeout': 3600, 'server_type': 'sglang'}], 'tinker': {'lora_rank': 32, 'learning_rate': 4e-05, 'max_token_trainer_length': 9000, 'checkpoint_dir': './temp/', 'save_checkpoint_interval': 25}, 'slurm': False, 'testing': False}
@dataclass
class EnvironmentInfo:
@dataclass
class RunState:
_environments: List[EnvironmentInfo] = []
_current_env: Optional[str] = None
_current_config: Dict[str, Any] = {}
_env_config_cache: Dict[str, Dict[str, Dict[str, Any]]] = {}
_active_runs: Dict[str, RunState] = {}
_last_status_check: Dict[str, float] = {}
MIN_STATUS_CHECK_INTERVAL = 30 * 60
def _scan_environments() -> List[EnvironmentInfo]:
    ...

def _get_env_config_fields(env_file_path: str) -> Dict[str, Dict[str, Any]]:
    ...

def _initialize_environments() -> Any:
    ...

run_id = run_state.run_id
api_log = LOGS_DIR / f'api_{run_id}.log'
trainer_log = LOGS_DIR / f'trainer_{run_id}.log'
env_log = LOGS_DIR / f'env_{run_id}.log'
env_info = None
env_info = env
exit_code = run_state.env_process.returncode
exit_code = run_state.trainer_process.returncode
def _stop_training_run(run_state: RunState) -> Any:
    ...

response = {'environments': [{'name': env.name, 'class_name': env.class_name, 'file_path': env.file_path, 'description': env.description} for env in _environments], 'count': len(_environments), 'tips': ['Use rl_select_environment(name) to select an environment', 'Read the file_path with file tools to understand how each environment works', 'Look for load_dataset(), score_answer(), get_next_item() methods']}
env_info = None
env_info = env
_current_env = name
_env_config_cache: config_fields
_current_config = {}
_current_config: field_info.get('default')
_current_config: f'{name}-{timestamp}'
configurable = []
locked = []
field_data = {'name': field_name, 'type': field_info.get('type', 'unknown'), 'default': field_info.get('default'), 'description': field_info.get('description', ''), 'current_value': _current_config.get(field_name, field_info.get('default'))}
field_data: LOCKED_FIELDS.get('env', {}).get(field_name)
field_info: TypeAlias = config_fields[field]
_current_config: value
env_info = None
env_info = env
run_id: TypeAlias = str(uuid.uuid4())[:8]
config_path = CONFIGS_DIR / f'run_{run_id}.yaml'
run_config: {}
run_config: {}
_active_runs: run_state
elapsed = now - _last_status_check[run_id]
remaining = MIN_STATUS_CHECK_INTERVAL - elapsed
_last_status_check: now
run_state: TypeAlias = _active_runs[run_id]
processes = {'api': run_state.api_process.poll() if run_state.api_process else None, 'trainer': run_state.trainer_process.poll() if run_state.trainer_process else None, 'env': run_state.env_process.poll() if run_state.env_process else None}
running_time = time.time() - run_state.start_time if run_state.start_time else 0
result = {'run_id': run_id, 'status': run_state.status, 'environment': run_state.environment, 'running_time_minutes': running_time / 60, 'processes': {name: 'running' if code is None else f'exited ({code})' for name, code in processes.items()}, 'wandb_project': run_state.wandb_project, 'wandb_run_name': run_state.wandb_run_name, 'logs': {'api': str(LOGS_DIR / f'api_{run_id}.log'), 'trainer': str(LOGS_DIR / f'trainer_{run_id}.log'), 'env': str(LOGS_DIR / f'env_{run_id}.log')}}
result: run_state.error_message
wandb_run: TypeAlias = runs[0]
result: wandb_run.url
result: {'step': wandb_run.summary.get('_step', 0), 'reward_mean': wandb_run.summary.get('train/reward_mean'), 'percent_correct': wandb_run.summary.get('train/percent_correct'), 'eval_percent_correct': wandb_run.summary.get('eval/percent_correct')}
result: str(e)
run_state: TypeAlias = _active_runs[run_id]
run_state: TypeAlias = _active_runs[run_id]
result = {'run_id': run_id, 'status': run_state.status, 'environment': run_state.environment, 'wandb_project': run_state.wandb_project, 'wandb_run_name': run_state.wandb_run_name}
wandb_run: TypeAlias = runs[0]
result: wandb_run.url
result: dict(wandb_run.summary)
result: [dict(row) for row in wandb_run.history(samples=10)]
result: str(e)
runs = []
TEST_MODELS = [{'id': 'qwen/qwen3-8b', 'name': 'Qwen3 8B', 'scale': 'small'}, {'id': 'z-ai/glm-4.7-flash', 'name': 'GLM-4.7 Flash', 'scale': 'medium'}, {'id': 'minimax/minimax-m2.7', 'name': 'MiniMax M2.7', 'scale': 'large'}]
DEFAULT_NUM_STEPS = 3
DEFAULT_GROUP_SIZE = 16
env_info = None
env_info = env
test_models = [m for m in TEST_MODELS if m['id'] in models]
test_models = [{'id': m, 'name': m, 'scale': 'custom'} for m in models]
test_models = TEST_MODELS
total_rollouts_per_model = num_steps * group_size
total_rollouts = total_rollouts_per_model * len(test_models)
results = {'environment': _current_env, 'environment_file': env_info.file_path, 'test_config': {'num_steps': num_steps, 'group_size': group_size, 'rollouts_per_model': total_rollouts_per_model, 'total_rollouts': total_rollouts}, 'models_tested': []}
test_output_dir = LOGS_DIR / 'inference_tests'
model_id: TypeAlias = model_info['id']
output_file = test_output_dir / f'test_{_current_env}_{model_safe_name}.jsonl'
test_run_id: TypeAlias = str(uuid.uuid4())[:8]
wandb_run_name = f'test_inference_RSIAgent_{_current_env}_{test_run_id}'
cmd = [sys.executable, env_info.file_path, 'process', '--env.total_steps', str(num_steps), '--env.group_size', str(group_size), '--env.use_wandb', 'true', '--env.wandb_name', wandb_run_name, '--env.data_path_to_save_groups', str(output_file), '--env.tokenizer_name', LOCKED_FIELDS['env']['tokenizer_name'], '--env.max_token_length', str(LOCKED_FIELDS['env']['max_token_length']), '--env.max_num_workers', str(LOCKED_FIELDS['env']['max_num_workers']), '--env.max_batches_offpolicy', str(LOCKED_FIELDS['env']['max_batches_offpolicy']), '--openai.base_url', 'https://openrouter.ai/api/v1', '--openai.api_key', api_key, '--openai.model_name', model_id, '--openai.server_type', 'openai', '--openai.health_check', 'false']
model_results = {'model': model_id, 'name': model_info['name'], 'scale': model_info['scale'], 'wandb_run': wandb_run_name, 'output_file': str(output_file), 'steps': [], 'steps_tested': 0, 'total_completions': 0, 'correct_completions': 0}
process = await asyncio.create_subprocess_exec(*cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE, cwd=str(TINKER_ATROPOS_ROOT))
stdout_lines = []
stderr_lines = []
log_file = test_output_dir / f'test_{_current_env}_{model_safe_name}.log'
line = await stream.readline()
model_results: f'Process exited with code {process.returncode}'
model_results: stderr_text[-1000:]
model_results: stdout_text[-1000:]
model_results: str(log_file)
model_results: f'Output file not created: {output_file}'
model_results: 'Process timed out after 10 minutes'
model_results: str(e)
model_results: round(model_results['correct_completions'] / model_results['total_completions'], 3)
model_results: 0
model_results: steps_with_correct
model_results: round(steps_with_correct / model_results['steps_tested'], 3)
model_results: 0
model_results: 0
working_models = [m for m in results['models_tested'] if m.get('steps_tested', 0) > 0]
results: {'steps_requested': num_steps, 'models_tested': len(test_models), 'models_succeeded': len(working_models), 'best_model': max(working_models, key=lambda x: x.get('accuracy', 0))['model'] if working_models else None, 'avg_accuracy': round(sum((m.get('accuracy', 0) for m in working_models)) / len(working_models), 3) if working_models else 0, 'environment_working': bool(working_models), 'output_directory': str(test_output_dir)}
def check_rl_python_version() -> bool:
    ...

def check_rl_api_keys() -> bool:
    ...

def get_missing_keys() -> List[str]:
    ...

RL_LIST_ENVIRONMENTS_SCHEMA = {'name': 'rl_list_environments', 'description': 'List all available RL environments. Returns environment names, paths, and descriptions. TIP: Read the file_path with file tools to understand how each environment works (verifiers, data loading, rewards).', 'parameters': {'type': 'object', 'properties': {}, 'required': []}}
RL_SELECT_ENVIRONMENT_SCHEMA = {'name': 'rl_select_environment', 'description': "Select an RL environment for training. Loads the environment's default configuration. After selecting, use rl_get_current_config() to see settings and rl_edit_config() to modify them.", 'parameters': {'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'Name of the environment to select (from rl_list_environments)'}}, 'required': ['name']}}
RL_GET_CURRENT_CONFIG_SCHEMA = {'name': 'rl_get_current_config', 'description': 'Get the current environment configuration. Returns only fields that can be modified: group_size, max_token_length, total_steps, steps_per_eval, use_wandb, wandb_name, max_num_workers.', 'parameters': {'type': 'object', 'properties': {}, 'required': []}}
RL_EDIT_CONFIG_SCHEMA = {'name': 'rl_edit_config', 'description': 'Update a configuration field. Use rl_get_current_config() first to see all available fields for the selected environment. Each environment has different configurable options. Infrastructure settings (tokenizer, URLs, lora_rank, learning_rate) are locked.', 'parameters': {'type': 'object', 'properties': {'field': {'type': 'string', 'description': 'Name of the field to update (get available fields from rl_get_current_config)'}, 'value': {'description': 'New value for the field'}}, 'required': ['field', 'value']}}
RL_START_TRAINING_SCHEMA = {'name': 'rl_start_training', 'description': 'Start a new RL training run with the current environment and config. Most training parameters (lora_rank, learning_rate, etc.) are fixed. Use rl_edit_config() to set group_size, batch_size, wandb_project before starting. WARNING: Training takes hours.', 'parameters': {'type': 'object', 'properties': {}, 'required': []}}
RL_CHECK_STATUS_SCHEMA = {'name': 'rl_check_status', 'description': 'Get status and metrics for a training run. RATE LIMITED: enforces 30-minute minimum between checks for the same run. Returns WandB metrics: step, state, reward_mean, loss, percent_correct.', 'parameters': {'type': 'object', 'properties': {'run_id': {'type': 'string', 'description': 'The run ID from rl_start_training()'}}, 'required': ['run_id']}}
RL_STOP_TRAINING_SCHEMA = {'name': 'rl_stop_training', 'description': 'Stop a running training job. Use if metrics look bad, training is stagnant, or you want to try different settings.', 'parameters': {'type': 'object', 'properties': {'run_id': {'type': 'string', 'description': 'The run ID to stop'}}, 'required': ['run_id']}}
RL_GET_RESULTS_SCHEMA = {'name': 'rl_get_results', 'description': 'Get final results and metrics for a completed training run. Returns final metrics and path to trained weights.', 'parameters': {'type': 'object', 'properties': {'run_id': {'type': 'string', 'description': 'The run ID to get results for'}}, 'required': ['run_id']}}
RL_LIST_RUNS_SCHEMA = {'name': 'rl_list_runs', 'description': 'List all training runs (active and completed) with their status.', 'parameters': {'type': 'object', 'properties': {}, 'required': []}}
RL_TEST_INFERENCE_SCHEMA = {'name': 'rl_test_inference', 'description': 'Quick inference test for any environment. Runs a few steps of inference + scoring using OpenRouter. Default: 3 steps x 16 completions = 48 rollouts per model, testing 3 models = 144 total. Tests environment loading, prompt construction, inference parsing, and verifier logic. Use BEFORE training to catch issues.', 'parameters': {'type': 'object', 'properties': {'num_steps': {'type': 'integer', 'description': 'Number of steps to run (default: 3, recommended max for testing)', 'default': 3}, 'group_size': {'type': 'integer', 'description': 'Completions per step (default: 16, like training)', 'default': 16}, 'models': {'type': 'array', 'items': {'type': 'string'}, 'description': 'Optional list of OpenRouter model IDs. Default: qwen/qwen3-8b, z-ai/glm-4.7-flash, minimax/minimax-m2.7'}}, 'required': []}}
_rl_env = ['TINKER_API_KEY', 'WANDB_API_KEY']

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import ast
import asyncio
import importlib
import importlib.util
import json
import os
import subprocess
import sys
import time
import uuid
import logging
import datetime
import yaml
import dataclasses
import pathlib
import typing
import hermes_constants
import atroposlib
import atroposlib.envs
import atroposlib.envs.base
import copy
import wandb
import tools
import tools.registry