# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from agent.redact import redact_sensitive_text
from email.mime.text import MIMEText
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, proxy_kwargs_for_aiohttp, resolve_proxy_url, utf16_len
from gateway.platforms.bluebubbles import BlueBubblesAdapter, check_bluebubbles_requirements
from gateway.platforms.discord import DiscordAdapter
from gateway.platforms.feishu import FEISHU_AVAILABLE, FEISHU_DOMAIN, FeishuAdapter, LARK_DOMAIN
from gateway.platforms.slack import SlackAdapter
from gateway.platforms.telegram import TelegramAdapter, _strip_mdv2
from gateway.platforms.wecom import WeComAdapter, check_wecom_requirements
from gateway.platforms.weixin import check_weixin_requirements, send_weixin_direct
from telegram import Bot
from telegram.constants import ParseMode
from tools.registry import registry, tool_error
from typing import Any
import aiohttp
import base64
import httpx
import json
import logging
import markdown
import os
import re
import smtplib
import ssl
import time

_NUMERIC_TOPIC_RE = _TELEGRAM_TOPIC_TARGET_RE
_IMAGE_EXTS = {'.jpg', '.jpeg', '.png', '.webp', '.gif'}
_VIDEO_EXTS = {'.mp4', '.mov', '.avi', '.mkv', '.3gp'}
_AUDIO_EXTS = {'.ogg', '.opus', '.mp3', '.wav', '.m4a'}
_VOICE_EXTS = {'.ogg', '.opus'}
def _sanitize_error_text(text: Any) -> str:
    ...

def _error(message: str) -> dict:
    ...

SEND_MESSAGE_SCHEMA = {'name': 'send_message', 'description': "Send a message to a connected messaging platform, or list available targets.\n\nIMPORTANT: When the user asks to send to a specific channel or person (not just a bare platform name), call send_message(action='list') FIRST to see available targets, then send to the correct one.\nIf the user just says a platform name like 'send to telegram', send directly to the home channel without listing first.", 'parameters': {'type': 'object', 'properties': {'action': {'type': 'string', 'enum': ['send', 'list'], 'description': "Action to perform. 'send' (default) sends a message. 'list' returns all available channels/contacts across connected platforms."}, 'target': {'type': 'string', 'description': "Delivery target. Format: 'platform' (uses home channel), 'platform:#channel-name', 'platform:chat_id', or 'platform:chat_id:thread_id' for Telegram topics and Discord threads. Examples: 'telegram', 'telegram:-1001234567890:17585', 'discord:999888777:555444333', 'discord:#bot-home', 'slack:#engineering', 'signal:+155****4567'"}, 'message': {'type': 'string', 'description': 'The message text to send'}}, 'required': []}}
def send_message_tool(args: Any) -> Any:
    ...

def _handle_list() -> Any:
    ...

def _handle_send(args: Any) -> Any:
    ...

def _parse_target_ref(platform_name: str, target_ref: str) -> Any:
    ...

def _describe_media_for_mirror(media_files: Any) -> Any:
    ...

def _get_cron_auto_delivery_target() -> Any:
    ...

def _maybe_skip_cron_duplicate_send(platform_name: str, chat_id: str, thread_id: str | None) -> Any:
    ...

_feishu_available = True
_feishu_available = False
media_files = media_files or []
_MAX_LENGTHS = {Platform.TELEGRAM: TelegramAdapter.MAX_MESSAGE_LENGTH, Platform.DISCORD: DiscordAdapter.MAX_MESSAGE_LENGTH, Platform.SLACK: SlackAdapter.MAX_MESSAGE_LENGTH}
_MAX_LENGTHS: FeishuAdapter.MAX_MESSAGE_LENGTH
_len_fn = utf16_len if platform == Platform.TELEGRAM else None
chunks = [message]
last_result = None
is_last = i == len(chunks) - 1
result = await _send_telegram(pconfig.token, chat_id, chunk, media_files=media_files if is_last else [], thread_id=thread_id)
last_result = result
warning = None
warning = f'MEDIA attachments were omitted for {platform.value}; native send_message media delivery is currently only supported for telegram'
last_result = None
result = await _send_discord(pconfig.token, chat_id, chunk, thread_id=thread_id)
result = await _send_slack(pconfig.token, chat_id, chunk)
result = await _send_whatsapp(pconfig.extra, chat_id, chunk)
result = await _send_signal(pconfig.extra, chat_id, chunk)
result = await _send_email(pconfig.extra, chat_id, chunk)
result = await _send_sms(pconfig.api_key, chat_id, chunk)
result = await _send_mattermost(pconfig.token, pconfig.extra, chat_id, chunk)
result = await _send_matrix(pconfig.token, pconfig.extra, chat_id, chunk)
result = await _send_homeassistant(pconfig.token, pconfig.extra, chat_id, chunk)
result = await _send_dingtalk(pconfig.extra, chat_id, chunk)
result = await _send_feishu(pconfig, chat_id, chunk, thread_id=thread_id)
result = await _send_wecom(pconfig.extra, chat_id, chunk)
result = await _send_bluebubbles(pconfig.extra, chat_id, chunk)
result = {'error': f'Direct sending not yet implemented for {platform.value}'}
last_result = result
last_result: warnings
formatted = message
send_parse_mode = ParseMode.HTML
formatted = message
send_parse_mode = ParseMode.MARKDOWN_V2
media_files = media_files or []
thread_kwargs = {}
thread_kwargs: int(thread_id)
last_msg = None
warnings = []
last_msg = await bot.send_message(chat_id=int_chat_id, text=formatted, parse_mode=send_parse_mode, **thread_kwargs)
plain = message
plain = message
last_msg = await bot.send_message(chat_id=int_chat_id, text=plain, parse_mode=None, **thread_kwargs)
warning = f'Media file not found, skipping: {media_path}'
last_msg = await bot.send_photo(chat_id=int_chat_id, photo=f, **thread_kwargs)
last_msg = await bot.send_video(chat_id=int_chat_id, video=f, **thread_kwargs)
last_msg = await bot.send_voice(chat_id=int_chat_id, voice=f, **thread_kwargs)
last_msg = await bot.send_audio(chat_id=int_chat_id, audio=f, **thread_kwargs)
last_msg = await bot.send_document(chat_id=int_chat_id, document=f, **thread_kwargs)
error = 'No deliverable text or media remained after processing MEDIA tags'
result = {'success': True, 'platform': 'telegram', 'chat_id': chat_id, 'message_id': str(last_msg.message_id)}
result: warnings
url = f'https://discord.com/api/v10/channels/{thread_id}/messages'
url = f'https://discord.com/api/v10/channels/{chat_id}/messages'
headers = {'Authorization': f'Bot {token}', 'Content-Type': 'application/json'}
body = await resp.text()
data = await resp.json()
url = 'https://slack.com/api/chat.postMessage'
headers = {'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'}
payload = {'channel': chat_id, 'text': message, 'mrkdwn': True}
data = await resp.json()
data = await resp.json()
body = await resp.text()
params = {'account': account, 'message': message}
params: chat_id[6:]
params: [chat_id]
payload = {'jsonrpc': '2.0', 'method': 'send', 'params': params, 'id': f'send_{int(time.time() * 1000)}'}
resp = await client.post(f'{http_url}/api/v1/rpc', json=payload)
address = extra.get('address') or os.getenv('EMAIL_ADDRESS', '')
smtp_host = extra.get('smtp_host') or os.getenv('EMAIL_SMTP_HOST', '')
smtp_port = 587
msg: address
msg: chat_id
msg: 'Hermes Agent'
creds = f'{account_sid}:{auth_token}'
url = f'https://api.twilio.com/2010-04-01/Accounts/{account_sid}/Messages.json'
headers = {'Authorization': f'Basic {encoded}'}
body = await resp.json()
token = token or os.getenv('MATTERMOST_TOKEN', '')
url = f'{base_url}/api/v4/posts'
headers = {'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'}
body = await resp.text()
data = await resp.json()
token = token or os.getenv('MATRIX_ACCESS_TOKEN', '')
txn_id = f'hermes_{int(time.time() * 1000)}_{os.urandom(4).hex()}'
url = f'{homeserver}/_matrix/client/v3/rooms/{chat_id}/send/m.room.message/{txn_id}'
headers = {'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'}
payload = {'msgtype': 'm.text', 'body': message}
payload: 'org.matrix.custom.html'
payload: html
body = await resp.text()
data = await resp.json()
token = token or os.getenv('HASS_TOKEN', '')
url = f'{hass_url}/api/services/notify/notify'
headers = {'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'}
body = await resp.text()
webhook_url = extra.get('webhook_url') or os.getenv('DINGTALK_WEBHOOK_URL', '')
resp = await client.post(webhook_url, json={'msgtype': 'text', 'text': {'content': message}})
connected = await adapter.connect()
result = await adapter.send(chat_id, message)
connected = await adapter.connect()
result = await adapter.send(chat_id, message)
media_files = media_files or []
domain = FEISHU_DOMAIN if domain_name != 'lark' else LARK_DOMAIN
metadata = {'thread_id': thread_id} if thread_id else None
last_result = None
last_result = await adapter.send(chat_id, message, metadata=metadata)
last_result = await adapter.send_image_file(chat_id, media_path, metadata=metadata)
last_result = await adapter.send_video(chat_id, media_path, metadata=metadata)
last_result = await adapter.send_voice(chat_id, media_path, metadata=metadata)
last_result = await adapter.send_voice(chat_id, media_path, metadata=metadata)
last_result = await adapter.send_document(chat_id, media_path, metadata=metadata)
def _check_send_message() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import logging
import os
import re
import ssl
import time
import agent
import agent.redact
import gateway
import gateway.channel_directory
import tools
import tools.interrupt
import gateway.config
import gateway.platforms
import gateway.platforms.base
import model_tools
import gateway.mirror
import gateway.session_context
import posixpath
import gateway.platforms.telegram
import gateway.platforms.discord
import gateway.platforms.slack
import gateway.platforms.feishu
import telegram
import telegram.constants
import aiohttp
import httpx
import smtplib
import email
import email.mime
import email.mime.text
import base64
import markdown
import gateway.platforms.wecom
import gateway.platforms.weixin
import gateway.platforms.bluebubbles
import gateway.status
import tools.registry