# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from agent.model_metadata import estimate_tokens_rough
from enum import Enum
from hermes_constants import get_hermes_home
from pathlib import Path
from tools.registry import registry, tool_error
from typing import Any, Dict, List, Optional, Set, Tuple
import json
import logging
import os
import re

SKILLS_DIR = HERMES_HOME / 'skills'
MAX_NAME_LENGTH = 64
MAX_DESCRIPTION_LENGTH = 1024
_PLATFORM_MAP = {'macos': 'darwin', 'linux': 'linux', 'windows': 'win32'}
_EXCLUDED_SKILL_DIRS = frozenset(('.git', '.github', '.hub'))
_REMOTE_ENV_BACKENDS = frozenset({'docker', 'singularity', 'modal', 'ssh', 'daytona'})
_secret_capture_callback = None
def load_env() -> Dict[str, str]:
    ...

class SkillReadinessStatus(str, Enum):
def set_secret_capture_callback(callback: Any) -> None:
    ...

def skill_matches_platform(frontmatter: Dict[str, Any]) -> bool:
    ...

def _normalize_prerequisite_values(value: Any) -> List[str]:
    ...

def _collect_prerequisite_values(frontmatter: Dict[str, Any]) -> Tuple[List[str], List[str]]:
    ...

def _normalize_setup_metadata(frontmatter: Dict[str, Any]) -> Dict[str, Any]:
    ...

def _get_required_environment_variables(frontmatter: Dict[str, Any], legacy_env_vars: List[str] | None) -> List[Dict[str, Any]]:
    ...

def _capture_required_environment_variables(skill_name: str, missing_entries: List[Dict[str, Any]]) -> Dict[str, Any]:
    ...

def _is_gateway_surface() -> bool:
    ...

def _get_terminal_backend_name() -> str:
    ...

def _is_env_var_persisted(var_name: str, env_snapshot: Dict[str, str] | None) -> bool:
    ...

def _remaining_required_environment_names(required_env_vars: List[Dict[str, Any]], capture_result: Dict[str, Any]) -> List[str]:
    ...

def _gateway_setup_hint() -> str:
    ...

def _build_setup_note(readiness_status: SkillReadinessStatus, missing: List[str], setup_help: str | None) -> str | None:
    ...

def check_skills_requirements() -> bool:
    ...

def _parse_frontmatter(content: str) -> Tuple[Dict[str, Any], str]:
    ...

def _get_category_from_path(skill_path: Path) -> Optional[str]:
    ...

def _parse_tags(tags_value: Any) -> List[str]:
    ...

def _get_disabled_skill_names() -> Set[str]:
    ...

def _is_skill_disabled(name: str, platform: str) -> bool:
    ...

def _find_all_skills() -> List[Dict[str, Any]]:
    ...

def _load_category_description(category_dir: Path) -> Optional[str]:
    ...

def skills_categories(verbose: bool, task_id: str) -> str:
    ...

def skills_list(category: str, task_id: str) -> str:
    ...

def skill_view(name: str, file_path: str, task_id: str) -> str:
    ...

SKILLS_TOOL_DESCRIPTION = "Access skill documents providing specialized instructions, guidelines, and executable knowledge.\n\nProgressive disclosure workflow:\n1. skills_list() - Returns metadata (name, description, tags, linked_file_count) for all skills\n2. skill_view(name) - Loads full SKILL.md content + shows available linked_files\n3. skill_view(name, file_path) - Loads specific linked file (e.g., 'references/api.md', 'scripts/train.py')\n\nSkills may include:\n- references/: Additional documentation, API specs, examples\n- templates/: Output formats, config files, boilerplate code\n- assets/: Supplementary files (agentskills.io standard)\n- scripts/: Executable helpers (Python, shell scripts)"
SKILLS_LIST_SCHEMA = {'name': 'skills_list', 'description': 'List available skills (name + description). Use skill_view(name) to load full content.', 'parameters': {'type': 'object', 'properties': {'category': {'type': 'string', 'description': 'Optional category filter to narrow results'}}, 'required': []}}
SKILL_VIEW_SCHEMA = {'name': 'skill_view', 'description': "Skills allow for loading information about specific tasks and workflows, as well as scripts and templates. Load a skill's full content or access its linked files (references, templates, scripts). First call returns SKILL.md content plus a 'linked_files' dict showing available references/templates/scripts. To access those, call again with file_path parameter.", 'parameters': {'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'The skill name (use skills_list to see available skills)'}, 'file_path': {'type': 'string', 'description': "OPTIONAL: Path to a linked file within the skill (e.g., 'references/api.md', 'templates/config.yaml', 'scripts/validate.py'). Omit to get the main SKILL.md content."}}, 'required': ['name']}}

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import logging
import hermes_constants
import os
import re
import enum
import pathlib
import typing
import tools
import tools.registry
import agent
import agent.skill_utils
import gateway
import gateway.session_context
import gateway.platforms
import gateway.platforms.base
import agent.model_metadata
import hermes_cli
import hermes_cli.config
import tools.path_security
import tools.env_passthrough
import tools.credential_files