# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_constants import get_hermes_home
from pathlib import Path
from typing import Any, Dict, List, Tuple
import hashlib
import logging
import os
import shutil

SKILLS_DIR = HERMES_HOME / 'skills'
MANIFEST_FILE = SKILLS_DIR / '.bundled_manifest'
def _get_bundled_dir() -> Path:
    ...

def _read_manifest() -> Dict[str, str]:
    ...

def _write_manifest(entries: Dict[str, str]) -> Any:
    ...

def _read_skill_name(skill_md: Path, fallback: str) -> str:
    ...

def _discover_bundled_skills(bundled_dir: Path) -> List[Tuple[str, Path]]:
    ...

def _compute_relative_dest(skill_dir: Path, bundled_dir: Path) -> Path:
    ...

def _dir_hash(directory: Path) -> str:
    ...

def sync_skills(quiet: bool) -> dict:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import hashlib
import logging
import os
import shutil
import pathlib
import hermes_constants
import typing
import tempfile