# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from tools.registry import registry, tool_error
from typing import Any, Dict, List, Optional
from typing_extensions import Self
import json

VALID_STATUSES = {'pending', 'in_progress', 'completed', 'cancelled'}
class TodoStore:
    def __init__(self: Self) -> None: ...
    def write(self: Self, todos: List[Dict[str, Any]], merge: bool) -> List[Dict[str, str]]: ...
    def read(self: Self) -> List[Dict[str, str]]: ...
    def has_items(self: Self) -> bool: ...
    def format_for_injection(self: Self) -> Optional[str]: ...
    @staticmethod
    def _validate(item: Dict[str, Any]) -> Dict[str, str]: ...
    @staticmethod
    def _dedupe_by_id(todos: List[Dict[str, Any]]) -> List[Dict[str, Any]]: ...

def todo_tool(todos: Optional[List[Dict[str, Any]]], merge: bool, store: Optional[TodoStore]) -> str:
    ...

def check_todo_requirements() -> bool:
    ...

TODO_SCHEMA = {'name': 'todo', 'description': "Manage your task list for the current session. Use for complex tasks with 3+ steps or when the user provides multiple tasks. Call with no parameters to read the current list.\n\nWriting:\n- Provide 'todos' array to create/update items\n- merge=false (default): replace the entire list with a fresh plan\n- merge=true: update existing items by id, add any new ones\n\nEach item: {id: string, content: string, status: pending|in_progress|completed|cancelled}\nList order is priority. Only ONE item in_progress at a time.\nMark items completed immediately when done. If something fails, cancel it and add a revised item.\n\nAlways returns the full current list.", 'parameters': {'type': 'object', 'properties': {'todos': {'type': 'array', 'description': 'Task items to write. Omit to read current list.', 'items': {'type': 'object', 'properties': {'id': {'type': 'string', 'description': 'Unique item identifier'}, 'content': {'type': 'string', 'description': 'Task description'}, 'status': {'type': 'string', 'enum': ['pending', 'in_progress', 'completed', 'cancelled'], 'description': 'Current status'}}, 'required': ['id', 'content', 'status']}}, 'merge': {'type': 'boolean', 'description': 'true: update existing items by id, add new ones. false (default): replace the entire list.', 'default': False}}, 'required': []}}

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import typing
import tools
import tools.registry