# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_constants import get_hermes_home
from pathlib import Path
from tools.managed_tool_gateway import resolve_managed_tool_gateway
from tools.tool_backend_helpers import managed_nous_tools_enabled, resolve_openai_audio_api_key
from typing import Any, Dict, Optional
from urllib.parse import urljoin
from utils import is_truthy_value
import importlib.util
import logging
import os
import shlex
import shutil
import subprocess
import tempfile

def _safe_find_spec(module_name: str) -> bool:
    ...

DEFAULT_PROVIDER = 'local'
DEFAULT_LOCAL_MODEL = 'base'
DEFAULT_LOCAL_STT_LANGUAGE = 'en'
LOCAL_STT_COMMAND_ENV = 'HERMES_LOCAL_STT_COMMAND'
LOCAL_STT_LANGUAGE_ENV = 'HERMES_LOCAL_STT_LANGUAGE'
COMMON_LOCAL_BIN_DIRS = ('/opt/homebrew/bin', '/usr/local/bin')
SUPPORTED_FORMATS = {'.mp3', '.mp4', '.mpeg', '.mpga', '.m4a', '.wav', '.webm', '.ogg', '.aac', '.flac'}
LOCAL_NATIVE_AUDIO_FORMATS = {'.wav', '.aiff', '.aif'}
MAX_FILE_SIZE = 25 * 1024 * 1024
OPENAI_MODELS = {'whisper-1', 'gpt-4o-mini-transcribe', 'gpt-4o-transcribe'}
GROQ_MODELS = {'whisper-large-v3', 'whisper-large-v3-turbo', 'distil-whisper-large-v3-en'}
_local_model: Optional[object] = None
_local_model_name: Optional[str] = None
def get_stt_model_from_config() -> Optional[str]:
    ...

def _load_stt_config() -> dict:
    ...

def is_stt_enabled(stt_config: Optional[dict]) -> bool:
    ...

def _has_openai_audio_backend() -> bool:
    ...

def _find_binary(binary_name: str) -> Optional[str]:
    ...

def _find_ffmpeg_binary() -> Optional[str]:
    ...

def _find_whisper_binary() -> Optional[str]:
    ...

def _get_local_command_template() -> Optional[str]:
    ...

def _has_local_command() -> bool:
    ...

def _normalize_local_command_model(model_name: Optional[str]) -> str:
    ...

def _get_provider(stt_config: dict) -> str:
    ...

def _validate_audio_file(file_path: str) -> Optional[Dict[str, Any]]:
    ...

def _transcribe_local(file_path: str, model_name: str) -> Dict[str, Any]:
    ...

def _prepare_local_audio(file_path: str, work_dir: str) -> tuple[Optional[str], Optional[str]]:
    ...

def _transcribe_local_command(file_path: str, model_name: str) -> Dict[str, Any]:
    ...

def _transcribe_groq(file_path: str, model_name: str) -> Dict[str, Any]:
    ...

def _transcribe_openai(file_path: str, model_name: str) -> Dict[str, Any]:
    ...

def _transcribe_mistral(file_path: str, model_name: str) -> Dict[str, Any]:
    ...

def transcribe_audio(file_path: str, model: Optional[str]) -> Dict[str, Any]:
    ...

def _resolve_openai_audio_client_config() -> tuple[str, str]:
    ...

def _extract_transcript_text(transcription: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import os
import shlex
import shutil
import subprocess
import tempfile
import pathlib
import typing
import urllib
import urllib.parse
import utils
import tools
import tools.managed_tool_gateway
import tools.tool_backend_helpers
import hermes_constants
import importlib
import importlib.util
import hermes_cli
import hermes_cli.config
import faster_whisper
import posixpath
import openai
import openai.OpenAI
import openai.APIError
import openai.APIConnectionError
import openai.APITimeoutError
import mistralai
import mistralai.client