# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from tools.managed_tool_gateway import resolve_managed_tool_gateway
from tools.registry import registry, tool_error
from tools.tool_backend_helpers import managed_nous_tools_enabled, resolve_openai_audio_api_key
from typing import Any, Callable, Dict, Optional
from urllib.parse import urljoin
import asyncio
import base64
import datetime
import json
import logging
import os
import queue
import re
import shutil
import subprocess
import tempfile
import threading
import uuid

def _import_edge_tts() -> Any:
    ...

def _import_elevenlabs() -> Any:
    ...

def _import_openai_client() -> Any:
    ...

def _import_mistral_client() -> Any:
    ...

def _import_sounddevice() -> Any:
    ...

DEFAULT_PROVIDER = 'edge'
DEFAULT_EDGE_VOICE = 'en-US-AriaNeural'
DEFAULT_ELEVENLABS_VOICE_ID = 'pNInz6obpgDQGcFmaJgB'
DEFAULT_ELEVENLABS_MODEL_ID = 'eleven_multilingual_v2'
DEFAULT_ELEVENLABS_STREAMING_MODEL_ID = 'eleven_flash_v2_5'
DEFAULT_OPENAI_MODEL = 'gpt-4o-mini-tts'
DEFAULT_OPENAI_VOICE = 'alloy'
DEFAULT_OPENAI_BASE_URL = 'https://api.openai.com/v1'
DEFAULT_MINIMAX_MODEL = 'speech-2.8-hd'
DEFAULT_MINIMAX_VOICE_ID = 'English_Graceful_Lady'
DEFAULT_MINIMAX_BASE_URL = 'https://api.minimax.io/v1/t2a_v2'
DEFAULT_MISTRAL_TTS_MODEL = 'voxtral-mini-tts-2603'
DEFAULT_MISTRAL_TTS_VOICE_ID = 'c69964a6-ab8b-4f8a-9465-ec0925096ec8'
def _get_default_output_dir() -> str:
    ...

MAX_TEXT_LENGTH = 4000
def _load_tts_config() -> Dict[str, Any]:
    ...

def _get_provider(tts_config: Dict[str, Any]) -> str:
    ...

def _has_ffmpeg() -> bool:
    ...

def _convert_to_opus(mp3_path: str) -> Optional[str]:
    ...

kwargs = {'voice': voice}
kwargs: f'{pct:+d}%'
def _generate_elevenlabs(text: str, output_path: str, tts_config: Dict[str, Any]) -> str:
    ...

def _generate_openai_tts(text: str, output_path: str, tts_config: Dict[str, Any]) -> str:
    ...

def _generate_minimax_tts(text: str, output_path: str, tts_config: Dict[str, Any]) -> str:
    ...

def _generate_mistral_tts(text: str, output_path: str, tts_config: Dict[str, Any]) -> str:
    ...

def _check_neutts_available() -> bool:
    ...

def _default_neutts_ref_audio() -> str:
    ...

def _default_neutts_ref_text() -> str:
    ...

def _generate_neutts(text: str, output_path: str, tts_config: Dict[str, Any]) -> str:
    ...

def text_to_speech_tool(text: str, output_path: Optional[str]) -> str:
    ...

def check_tts_requirements() -> bool:
    ...

def _resolve_openai_audio_client_config() -> tuple[str, str]:
    ...

def _has_openai_audio_backend() -> bool:
    ...

def _strip_markdown_for_tts(text: str) -> str:
    ...

def stream_tts_to_speaker(text_queue: queue.Queue, stop_event: threading.Event, tts_done_event: threading.Event, display_callback: Optional[Callable[[str], None]]) -> Any:
    ...

TTS_SCHEMA = {'name': 'text_to_speech', 'description': 'Convert text to speech audio. Returns a MEDIA: path that the platform delivers as a voice message. On Telegram it plays as a voice bubble, on Discord/WhatsApp as an audio attachment. In CLI mode, saves to ~/voice-memos/. Voice and provider are user-configured, not model-selected.', 'parameters': {'type': 'object', 'properties': {'text': {'type': 'string', 'description': 'The text to convert to speech. Keep under 4000 characters.'}, 'output_path': {'type': 'string', 'description': 'Optional custom file path to save the audio. Defaults to ~/.hermes/audio_cache/<timestamp>.mp3'}}, 'required': ['text']}}

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import base64
import datetime
import json
import logging
import os
import queue
import re
import shutil
import subprocess
import tempfile
import threading
import uuid
import pathlib
import typing
import urllib
import urllib.parse
import tools
import tools.managed_tool_gateway
import tools.tool_backend_helpers
import edge_tts
import elevenlabs
import elevenlabs.client
import openai
import openai.OpenAI
import mistralai
import mistralai.client
import sounddevice
import hermes_constants
import hermes_cli
import hermes_cli.config
import posixpath
import requests
import importlib
import importlib.util
import sys
import gateway
import gateway.session_context
import concurrent
import concurrent.futures
import numpy
import wave
import tools.voice_mode
import tools.registry