# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from agent.auxiliary_client import async_call_llm, extract_content_or_reasoning
from hermes_cli.config import load_config
from pathlib import Path
from tools.debug_helpers import DebugSession
from tools.interrupt import is_interrupted
from tools.registry import registry, tool_error
from tools.url_safety import is_safe_url
from tools.website_policy import check_website_access
from typing import Any, Awaitable, Dict, Optional
from typing_extensions import TypeAlias
from urllib.parse import urlparse
import asyncio
import base64
import httpx
import json
import logging
import os
import uuid

def _resolve_download_timeout() -> float:
    ...

_VISION_MAX_DOWNLOAD_BYTES = 50 * 1024 * 1024
def _validate_image_url(url: str) -> bool:
    ...

def _detect_image_mime_type(image_path: Path) -> Optional[str]:
    ...

last_error = None
response = await client.get(image_url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36', 'Accept': 'image/*,*/*;q=0.8'})
body = response.content
last_error = e
wait_time = 2 ** (attempt + 1)
def _determine_mime_type(image_path: Path) -> str:
    ...

def _image_to_base64_data_url(image_path: Path, mime_type: Optional[str]) -> str:
    ...

_MAX_BASE64_BYTES = 20 * 1024 * 1024
_RESIZE_TARGET_BYTES = 5 * 1024 * 1024
def _is_image_size_error(error: Exception) -> bool:
    ...

def _resize_image_for_vision(image_path: Path, mime_type: Optional[str], max_base64_bytes: int) -> str:
    ...

debug_call_data = {'parameters': {'image_url': image_url, 'user_prompt': user_prompt[:200] + '...' if len(user_prompt) > 200 else user_prompt, 'model': model}, 'error': None, 'success': False, 'analysis_length': 0, 'model_used': model, 'image_size_bytes': 0}
temp_image_path = None
should_cleanup = True
detected_mime_type = None
resolved_url = image_url
resolved_url: TypeAlias = resolved_url[len('file://'):]
temp_image_path = local_path
should_cleanup = False
temp_image_path = temp_dir / f'temp_image_{uuid.uuid4()}.jpg'
should_cleanup = True
image_size_bytes = temp_image_path.stat().st_size
image_size_kb = image_size_bytes / 1024
data_size_kb = len(image_data_url) / 1024
debug_call_data: image_size_bytes
comprehensive_prompt = user_prompt
messages = [{'role': 'user', 'content': [{'type': 'text', 'text': comprehensive_prompt}, {'type': 'image_url', 'image_url': {'url': image_data_url}}]}]
vision_timeout = 120.0
call_kwargs = {'task': 'vision', 'messages': messages, 'temperature': 0.1, 'max_tokens': 2000, 'timeout': vision_timeout}
call_kwargs: model
response = await async_call_llm(**call_kwargs)
response = await async_call_llm(**call_kwargs)
response = await async_call_llm(**call_kwargs)
result = {'success': True, 'analysis': analysis or 'There was a problem with the request and the image could not be analyzed.'}
debug_call_data: True
debug_call_data: analysis_length
error_msg = f'Error analyzing image: {str(e)}'
analysis = f'Insufficient credits or payment required. Please top up your API provider account and try again. Error: {e}'
analysis = f'{model} does not support vision or our request was not accepted by the server. Error: {e}'
analysis = f'The vision API rejected the image. This can happen when the image is in an unsupported format, corrupted, or still too large after auto-resize. Try a smaller JPEG/PNG and retry. Error: {e}'
analysis = f'There was a problem with the request and the image could not be analyzed. Error: {e}'
result = {'success': False, 'error': error_msg, 'analysis': analysis}
debug_call_data: error_msg
def check_vision_requirements() -> bool:
    ...

def get_debug_session_info() -> Dict[str, Any]:
    ...

VISION_ANALYZE_SCHEMA = {'name': 'vision_analyze', 'description': 'Analyze images using AI vision. Provides a comprehensive description and answers a specific question about the image content.', 'parameters': {'type': 'object', 'properties': {'image_url': {'type': 'string', 'description': 'Image URL (http/https) or local file path to analyze.'}, 'question': {'type': 'string', 'description': 'Your specific question or request about the image to resolve. The AI will automatically provide a complete image description AND answer your specific question.'}}, 'required': ['image_url', 'question']}}
def _handle_vision_analyze(args: Dict[str, Any]) -> Awaitable[str]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import base64
import json
import logging
import os
import uuid
import pathlib
import typing
import urllib
import urllib.parse
import httpx
import agent
import agent.auxiliary_client
import tools
import tools.debug_helpers
import tools.website_policy
import hermes_cli
import hermes_cli.config
import tools.url_safety
import asyncio
import PIL
import io
import tools.interrupt
import posixpath
import tools.registry