# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from agent.auxiliary_client import async_call_llm, extract_content_or_reasoning, get_async_text_auxiliary_client
from agent.redact import _PREFIX_RE
from firecrawl import Firecrawl
from tools.debug_helpers import DebugSession
from tools.interrupt import is_interrupted
from tools.managed_tool_gateway import build_vendor_gateway_url, read_nous_access_token, resolve_managed_tool_gateway
from tools.registry import registry, tool_error
from tools.tool_backend_helpers import managed_nous_tools_enabled
from tools.url_safety import is_safe_url
from tools.website_policy import check_website_access
from typing import Any, Dict, List, Optional
from typing_extensions import TypeAlias
from urllib.parse import unquote
import asyncio
import httpx
import json
import logging
import os
import re

def _has_env(name: str) -> bool:
    ...

def _load_web_config() -> dict:
    ...

def _get_backend() -> str:
    ...

def _is_backend_available(backend: str) -> bool:
    ...

_firecrawl_client = None
_firecrawl_client_config = None
def _get_direct_firecrawl_config() -> Optional[tuple[Dict[str, str], tuple[str, Optional[str], Optional[str]]]]:
    ...

def _get_firecrawl_gateway_url() -> str:
    ...

def _is_tool_gateway_ready() -> bool:
    ...

def _has_direct_firecrawl_config() -> bool:
    ...

def _raise_web_backend_configuration_error() -> None:
    ...

def _firecrawl_backend_help_suffix() -> str:
    ...

def _web_requires_env() -> list[str]:
    ...

def _get_firecrawl_client() -> Any:
    ...

_parallel_client = None
_async_parallel_client = None
def _get_parallel_client() -> Any:
    ...

def _get_async_parallel_client() -> Any:
    ...

_TAVILY_BASE_URL = 'https://api.tavily.com'
def _tavily_request(endpoint: str, payload: dict) -> dict:
    ...

def _normalize_tavily_search_results(response: dict) -> dict:
    ...

def _normalize_tavily_documents(response: dict, fallback_url: str) -> List[Dict[str, Any]]:
    ...

def _to_plain_object(value: Any) -> Any:
    ...

def _normalize_result_list(values: Any) -> List[Dict[str, Any]]:
    ...

def _extract_web_search_results(response: Any) -> List[Dict[str, Any]]:
    ...

def _extract_scrape_payload(scrape_result: Any) -> Dict[str, Any]:
    ...

DEFAULT_MIN_LENGTH_FOR_SUMMARIZATION = 5000
def _is_nous_auxiliary_client(client: Any) -> bool:
    ...

def _resolve_web_extract_auxiliary(model: Optional[str]) -> tuple[Optional[Any], Optional[str], Dict[str, Any]]:
    ...

def _get_default_summarizer_model() -> Optional[str]:
    ...

MAX_CONTENT_SIZE = 2000000
CHUNK_THRESHOLD = 500000
CHUNK_SIZE = 100000
MAX_OUTPUT_SIZE = 5000
size_mb = content_len / 1000000
context_info = []
context_str = '\n'.join(context_info) + '\n\n' if context_info else ''
processed_content = await _call_summarizer_llm(content, context_str, model)
processed_content = processed_content[:MAX_OUTPUT_SIZE] + '\n\n[... summary truncated for context management ...]'
compression_ratio = processed_length / content_len if content_len > 0 else 1.0
truncated: TypeAlias = content[:MAX_OUTPUT_SIZE]
system_prompt = 'You are an expert content analyst processing a SECTION of a larger document. Your job is to extract and summarize the key information from THIS SECTION ONLY.\n\nImportant guidelines for chunk processing:\n1. Do NOT write introductions or conclusions - this is a partial document\n2. Focus on extracting ALL key facts, figures, data points, and insights from this section\n3. Preserve important quotes, code snippets, and specific details verbatim\n4. Use bullet points and structured formatting for easy synthesis later\n5. Note any references to other sections (e.g., "as mentioned earlier", "see below") without trying to resolve them\n\nYour output will be combined with summaries of other sections, so focus on thorough extraction rather than narrative flow.'
user_prompt = f'Extract key information from this SECTION of a larger document:\n\n{context_str}{chunk_info}\n\nSECTION CONTENT:\n{content}\n\nExtract all important information from this section in a structured format. Focus on facts, data, insights, and key details. Do not add introductions or conclusions.'
system_prompt = 'You are an expert content analyst. Your job is to process web content and create a comprehensive yet concise summary that preserves all important information while dramatically reducing bulk.\n\nCreate a well-structured markdown summary that includes:\n1. Key excerpts (quotes, code snippets, important facts) in their original format\n2. Comprehensive summary of all other important information\n3. Proper markdown formatting with headers, bullets, and emphasis\n\nYour goal is to preserve ALL important information while reducing length. Never lose key facts, figures, insights, or actionable information. Make it scannable and well-organized.'
user_prompt = f'Please process this web content and create a comprehensive markdown summary:\n\n{context_str}CONTENT TO PROCESS:\n{content}\n\nCreate a markdown summary that captures all key information in a well-organized, scannable format. Include important quotes and code snippets in their original formatting. Focus on actionable information, specific details, and unique insights.'
max_retries = 2
retry_delay = 2
last_error = None
call_kwargs = {'task': 'web_extract', 'model': effective_model, 'messages': [{'role': 'system', 'content': system_prompt}, {'role': 'user', 'content': user_prompt}], 'temperature': 0.1, 'max_tokens': max_tokens}
call_kwargs: extra_body
response = await async_call_llm(**call_kwargs)
last_error = api_error
chunks = []
chunk: TypeAlias = content[i:i + chunk_size]
chunk_info = f'[Processing chunk {chunk_idx + 1} of {len(chunks)}]'
summary = await _call_summarizer_llm(chunk_content, context_str, model, max_tokens=10000, is_chunk=True, chunk_info=chunk_info)
tasks = [summarize_chunk(i, chunk) for i, chunk in enumerate(chunks)]
results = await asyncio.gather(*tasks)
summaries = []
result: TypeAlias = summaries[0]
result = result[:max_output_size] + '\n\n[... truncated ...]'
synthesis_prompt = f'You have been given summaries of different sections of a large document. \nSynthesize these into ONE cohesive, comprehensive summary that:\n1. Removes redundancy between sections\n2. Preserves all key facts, figures, and actionable information\n3. Is well-organized with clear structure\n4. Is under {max_output_size} characters\n\n{context_str}SECTION SUMMARIES:\n{combined_summaries}\n\nCreate a single, unified markdown summary.'
fallback = fallback[:max_output_size] + '\n\n[... truncated ...]'
call_kwargs = {'task': 'web_extract', 'model': effective_model, 'messages': [{'role': 'system', 'content': 'You synthesize multiple summaries into one cohesive, comprehensive summary. Be thorough but concise.'}, {'role': 'user', 'content': synthesis_prompt}], 'temperature': 0.1, 'max_tokens': 20000}
call_kwargs: extra_body
response = await async_call_llm(**call_kwargs)
response = await async_call_llm(**call_kwargs)
fallback = fallback[:max_output_size] + '\n\n[... truncated ...]'
final_summary = final_summary[:max_output_size] + '\n\n[... summary truncated for context management ...]'
compression = final_len / original_len if original_len > 0 else 1.0
fallback = fallback[:max_output_size] + '\n\n[... truncated due to synthesis failure ...]'
def clean_base64_images(text: str) -> str:
    ...

_exa_client = None
def _get_exa_client() -> Any:
    ...

def _exa_search(query: str, limit: int) -> dict:
    ...

def _exa_extract(urls: List[str]) -> List[Dict[str, Any]]:
    ...

def _parallel_search(query: str, limit: int) -> dict:
    ...

response = await _get_async_parallel_client().beta.extract(urls=urls, full_content=True)
results = []
content = result.full_content or ''
url = result.url or ''
title = result.title or ''
def web_search_tool(query: str, limit: int) -> str:
    ...

debug_call_data = {'parameters': {'urls': urls, 'format': format, 'use_llm_processing': use_llm_processing, 'model': model, 'min_length': min_length}, 'error': None, 'pages_extracted': 0, 'pages_processed_with_llm': 0, 'original_response_size': 0, 'final_response_size': 0, 'compression_metrics': [], 'processing_applied': []}
safe_urls = []
ssrf_blocked: List[Dict[str, Any]] = []
results = []
results = await _parallel_extract(safe_urls)
formats: List[str] = []
formats = ['markdown']
formats = ['html']
formats = ['markdown', 'html']
results: List[Dict[str, Any]] = []
scrape_result = await asyncio.wait_for(asyncio.to_thread(_get_firecrawl_client().scrape, url=url, formats=formats), timeout=60)
title = ''
metadata = metadata.__dict__
metadata = {}
chosen_content = content_markdown if format == 'markdown' or (format is None and content_markdown) else content_html or content_markdown or ''
results = ssrf_blocked + results
response = {'results': results}
debug_call_data: pages_extracted
debug_call_data: len(json.dumps(response))
effective_model = model or _get_default_summarizer_model()
raw_content = result.get('raw_content', '') or result.get('content', '')
processed = await process_content_with_llm(raw_content, url, title, effective_model, min_length)
compression_ratio = processed_size / original_size if original_size > 0 else 1.0
result: processed
result: raw_content
metrics = {'url': url, 'original_size': original_size, 'processed_size': processed_size, 'compression_ratio': compression_ratio, 'model_used': effective_model}
metrics = {'url': url, 'original_size': original_size, 'processed_size': original_size, 'compression_ratio': 1.0, 'model_used': None, 'reason': 'content_too_short'}
tasks = [process_single_result(result) for result in results_list]
processed_results = await asyncio.gather(*tasks)
trimmed_results = [{'url': r.get('url', ''), 'title': r.get('title', ''), 'content': r.get('content', ''), 'error': r.get('error'), **({'blocked_by_policy': r['blocked_by_policy']} if 'blocked_by_policy' in r else {})} for r in response.get('results', [])]
trimmed_response = {'results': trimmed_results}
debug_call_data: len(cleaned_result)
error_msg = f'Error extracting content: {str(e)}'
debug_call_data: error_msg
debug_call_data = {'parameters': {'url': url, 'instructions': instructions, 'depth': depth, 'use_llm_processing': use_llm_processing, 'model': model, 'min_length': min_length}, 'error': None, 'pages_crawled': 0, 'pages_processed_with_llm': 0, 'original_response_size': 0, 'final_response_size': 0, 'compression_metrics': [], 'processing_applied': []}
effective_model = model or _get_default_summarizer_model()
url = f'https://{url}'
payload: Dict[str, Any] = {'url': url, 'limit': 20, 'extract_depth': depth}
payload: instructions
response = {'results': results}
debug_call_data: pages_crawled
debug_call_data: len(json.dumps(response))
processed = await process_content_with_llm(content, page_url, title, effective_model, min_length)
result: content
result: processed
metrics = {'url': page_url, 'original_size': original_size, 'processed_size': len(processed), 'compression_ratio': len(processed) / original_size if original_size else 1.0, 'model_used': effective_model}
metrics = {'url': page_url, 'original_size': original_size, 'processed_size': original_size, 'compression_ratio': 1.0, 'model_used': None, 'reason': 'content_too_short'}
tasks = [_process_tavily_crawl(r) for r in response.get('results', [])]
processed_results = await asyncio.gather(*tasks)
trimmed_results = [{'url': r.get('url', ''), 'title': r.get('title', ''), 'content': r.get('content', ''), 'error': r.get('error'), **({'blocked_by_policy': r['blocked_by_policy']} if 'blocked_by_policy' in r else {})} for r in response.get('results', [])]
debug_call_data: len(cleaned_result)
url = f'https://{url}'
instructions_text = f" with instructions: '{instructions}'" if instructions else ''
crawl_params = {'limit': 20, 'scrape_options': {'formats': ['markdown']}}
pages: List[Dict[str, Any]] = []
data_list = []
data_list = crawl_result.data if crawl_result.data else []
page_url = 'Unknown URL'
title = ''
content_markdown = None
content_html = None
metadata = {}
metadata = metadata_obj.__dict__
metadata = metadata_obj
metadata = {}
metadata = metadata.__dict__
metadata = {}
content = content_markdown or content_html or ''
response = {'results': pages}
debug_call_data: pages_crawled
debug_call_data: len(json.dumps(response))
processed = await process_content_with_llm(content, page_url, title, effective_model, min_length)
compression_ratio = processed_size / original_size if original_size > 0 else 1.0
result: content
result: processed
metrics = {'url': page_url, 'original_size': original_size, 'processed_size': processed_size, 'compression_ratio': compression_ratio, 'model_used': effective_model}
metrics = {'url': page_url, 'original_size': original_size, 'processed_size': original_size, 'compression_ratio': 1.0, 'model_used': None, 'reason': 'content_too_short'}
tasks = [process_single_crawl_result(result) for result in results_list]
processed_results = await asyncio.gather(*tasks)
trimmed_results = [{'url': r.get('url', ''), 'title': r.get('title', ''), 'content': r.get('content', ''), 'error': r.get('error'), **({'blocked_by_policy': r['blocked_by_policy']} if 'blocked_by_policy' in r else {})} for r in response.get('results', [])]
trimmed_response = {'results': trimmed_results}
debug_call_data: len(cleaned_result)
error_msg = f'Error crawling website: {str(e)}'
debug_call_data: error_msg
def check_firecrawl_api_key() -> bool:
    ...

def check_web_api_key() -> bool:
    ...

def check_auxiliary_model() -> bool:
    ...

def get_debug_session_info() -> Dict[str, Any]:
    ...

WEB_SEARCH_SCHEMA = {'name': 'web_search', 'description': 'Search the web for information on any topic. Returns up to 5 relevant results with titles, URLs, and descriptions.', 'parameters': {'type': 'object', 'properties': {'query': {'type': 'string', 'description': 'The search query to look up on the web'}}, 'required': ['query']}}
WEB_EXTRACT_SCHEMA = {'name': 'web_extract', 'description': 'Extract content from web page URLs. Returns page content in markdown format. Also works with PDF URLs (arxiv papers, documents, etc.) — pass the PDF link directly and it converts to markdown text. Pages under 5000 chars return full markdown; larger pages are LLM-summarized and capped at ~5000 chars per page. Pages over 2M chars are refused. If a URL fails or times out, use the browser tool to access it instead.', 'parameters': {'type': 'object', 'properties': {'urls': {'type': 'array', 'items': {'type': 'string'}, 'description': 'List of URLs to extract content from (max 5 URLs per call)', 'maxItems': 5}}, 'required': ['urls']}}

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import logging
import os
import re
import asyncio
import typing
import httpx
import firecrawl
import agent
import agent.auxiliary_client
import tools
import tools.debug_helpers
import tools.managed_tool_gateway
import tools.tool_backend_helpers
import tools.url_safety
import tools.website_policy
import hermes_cli
import hermes_cli.config
import parallel
import urllib
import urllib.parse
import exa_py
import tools.interrupt
import agent.redact
import tools.registry