# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from hermes_constants import get_hermes_home
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import urlparse
import fnmatch
import logging
import threading
import time

_DEFAULT_WEBSITE_BLOCKLIST = {'enabled': False, 'domains': [], 'shared_files': []}
_CACHE_TTL_SECONDS = 30.0
_cached_policy: Optional[Dict[str, Any]] = None
_cached_policy_path: Optional[str] = None
_cached_policy_time: float = 0.0
def _get_default_config_path() -> Path:
    ...

class WebsitePolicyError(Exception): ...
def _normalize_host(host: str) -> str:
    ...

def _normalize_rule(rule: Any) -> Optional[str]:
    ...

def _iter_blocklist_file_rules(path: Path) -> List[str]:
    ...

def _load_policy_config(config_path: Optional[Path]) -> Dict[str, Any]:
    ...

def load_website_blocklist(config_path: Optional[Path]) -> Dict[str, Any]:
    ...

def invalidate_cache() -> None:
    ...

def _match_host_against_rule(host: str, pattern: str) -> bool:
    ...

def _extract_host_from_urlish(url: str) -> str:
    ...

def check_website_access(url: str, config_path: Optional[Path]) -> Optional[Dict[str, str]]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import fnmatch
import logging
import threading
import time
import pathlib
import typing
import urllib
import urllib.parse
import hermes_constants
import yaml