# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_constants import get_hermes_home
from pathlib import Path
import logging
import os
import threading

BOOT_FILE = HERMES_HOME / 'BOOT.md'
def _build_boot_prompt(content: str) -> str:
    ...

def _run_boot_agent(content: str) -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import os
import threading
import pathlib
import hermes_constants
import run_agent