# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from pathlib import Path
from typing import Any
from typing_extensions import Self
import hashlib
import json
import logging
import numpy
import os
import pickle
import requests
import time

_PLUGIN_DIR = Path(__file__).resolve().parent.parent
_PLUGIN_ROOT = _PLUGIN_DIR.parent
_VENDORED_MODEL_DIR = _PLUGIN_ROOT / 'vendored' / 'models' / 'bge-m3'
_CACHE_DIR = _PLUGIN_DIR / 'retrieval' / '.embedding_cache'
_tool_docs: dict[str, str] | None = None
_reranker_docs: dict[str, str] | None = None
def set_tool_docs(docs: dict[str, str]) -> None:
    ...

def get_tool_docs() -> dict[str, str]:
    ...

def set_reranker_docs(docs: dict[str, str]) -> None:
    ...

def get_reranker_docs() -> dict[str, str]:
    ...

_SILICONFLOW_URL = 'https://api.siliconflow.cn/v1/embeddings'
_MAX_RETRIES = 3
_RETRY_DELAYS = (1, 3, 6)
def _siliconflow_encode(texts: list[str], api_key: str, model: str, api_url: str) -> np.ndarray:
    ...

_local_model = None
_local_reranker = None
_local_reranker_tokenizer = None
def _get_reranker(model_path: str, use_fp16: bool) -> Any:
    ...

def _rerank(query: str, candidates: list[dict], tool_docs: dict[str, str], model_path: str, use_fp16: bool, config: dict | None) -> list[dict]:
    ...

def _sparse_match_score(q_weights: dict, d_weights: dict) -> float:
    ...

def _colbert_score(q_vecs: np.ndarray, d_vecs: np.ndarray) -> float:
    ...

def _local_encode(texts: list[str], model_path: str, return_sparse: bool, return_colbert: bool) -> np.ndarray | tuple:
    ...

class ToolRetriever:
    def __init__(self: Self, config: dict | None) -> None: ...
    def _get_provider(self: Self) -> str: ...
    def _use_hybrid(self: Self) -> bool: ...
    def _should_rerank(self: Self) -> bool: ...
    def _encode_dense(self: Self, texts: list[str]) -> np.ndarray: ...
    def _encode_hybrid(self: Self, texts: list[str]) -> tuple: ...
    def _cache_key(self: Self) -> str: ...
    def _load_or_build_corpus(self: Self) -> Any: ...
    def _load_or_build_dense_corpus(self: Self, cache_key: str) -> Any: ...
    def _load_or_build_hybrid_corpus(self: Self, cache_key: str) -> Any: ...
    def retrieve(self: Self, query: str, top_k: int) -> list[dict]: ...
    def _retrieve_dense(self: Self, query: str, top_k: int) -> list[dict]: ...
    def _retrieve_hybrid(self: Self, query: str, top_k: int) -> list[dict]: ...

_retriever_instance: ToolRetriever | None = None
def get_retriever() -> ToolRetriever:
    ...

def has_retriever() -> bool:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import hashlib
import json
import logging
import os
import pickle
import time
import pathlib
import numpy
import requests
import torch
import transformers
import transformers.AutoModelForSequenceClassification
import transformers.AutoTokenizer
import FlagEmbedding
import FlagEmbedding.BGEM3FlagModel
import yaml