# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_constants import get_hermes_home
from pathlib import Path
import asyncio
import logging
import sys

def _setup_logging() -> None:
    ...

def _load_env() -> None:
    ...

def main() -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import logging
import sys
import pathlib
import hermes_constants
import hermes_cli
import hermes_cli.env_loader
import acp