# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from collections import deque
from tools import build_tool_complete, build_tool_start, make_tool_call_id
from typing import Any, Callable, Deque, Dict
import acp
import asyncio
import json
import logging

def _send_update(conn: acp.Client, session_id: str, loop: asyncio.AbstractEventLoop, update: Any) -> None:
    ...

def make_tool_progress_cb(conn: acp.Client, session_id: str, loop: asyncio.AbstractEventLoop, tool_call_ids: Dict[str, Deque[str]]) -> Callable:
    ...

def make_thinking_cb(conn: acp.Client, session_id: str, loop: asyncio.AbstractEventLoop) -> Callable:
    ...

def make_step_cb(conn: acp.Client, session_id: str, loop: asyncio.AbstractEventLoop, tool_call_ids: Dict[str, Deque[str]]) -> Callable:
    ...

def make_message_cb(conn: acp.Client, session_id: str, loop: asyncio.AbstractEventLoop) -> Callable:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import json
import logging
import collections
import collections.deque
import typing
import acp