# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from acp.schema import AllowedOutcome, PermissionOption
from concurrent.futures import TimeoutError
from typing import Callable
import asyncio
import logging

_KIND_TO_HERMES = {'allow_once': 'once', 'allow_always': 'always', 'reject_once': 'deny', 'reject_always': 'deny'}
def make_approval_callback(request_permission_fn: Callable, loop: asyncio.AbstractEventLoop, session_id: str, timeout: float) -> Callable[[str, str], str]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import asyncio
import logging
import concurrent
import concurrent.futures
import concurrent.futures.TimeoutError
import typing
import acp
import acp.schema