# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from dataclasses import dataclass, field
from hermes_constants import get_hermes_home
from threading import Lock
from typing import Any, Dict, List, Optional
from typing_extensions import Self
from dataclasses import dataclass
import copy
import json
import logging
import sys
import uuid

def _acp_stderr_print() -> None:
    ...

def _register_task_cwd(task_id: str, cwd: str) -> None:
    ...

def _clear_task_cwd(task_id: str) -> None:
    ...

@dataclass
class SessionState:
class SessionManager:
    def __init__(self: Self, agent_factory: Any, db: Any) -> None: ...
    def create_session(self: Self, cwd: str) -> SessionState: ...
    def get_session(self: Self, session_id: str) -> Optional[SessionState]: ...
    def remove_session(self: Self, session_id: str) -> bool: ...
    def fork_session(self: Self, session_id: str, cwd: str) -> Optional[SessionState]: ...
    def list_sessions(self: Self) -> List[Dict[str, Any]]: ...
    def update_cwd(self: Self, session_id: str, cwd: str) -> Optional[SessionState]: ...
    def cleanup(self: Self) -> None: ...
    def save_session(self: Self, session_id: str) -> None: ...
    def _get_db(self: Self) -> Any: ...
    def _persist(self: Self, state: SessionState) -> None: ...
    def _restore(self: Self, session_id: str) -> Optional[SessionState]: ...
    def _delete_persisted(self: Self, session_id: str) -> bool: ...
    def _make_agent(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import hermes_constants
import copy
import json
import logging
import sys
import uuid
import dataclasses
import threading
import typing
import tools
import tools.terminal_tool
import hermes_state
import run_agent
import hermes_cli
import hermes_cli.config
import hermes_cli.runtime_provider