# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Dict
from typing_extensions import Self

class CloudBrowserProvider(ABC):
    def provider_name(self: Self) -> str: ...
    def is_configured(self: Self) -> bool: ...
    def create_session(self: Self, task_id: str) -> Dict[str, object]: ...
    def close_session(self: Self, session_id: str) -> bool: ...
    def emergency_cleanup(self: Self, session_id: str) -> None: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import abc
import typing