# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from tools.browser_providers.base import CloudBrowserProvider
from typing import Any, Dict, Optional
from typing_extensions import Self
import logging
import os
import requests
import uuid

class BrowserbaseProvider(CloudBrowserProvider):
    def provider_name(self: Self) -> str: ...
    def is_configured(self: Self) -> bool: ...
    def _get_config_or_none(self: Self) -> Optional[Dict[str, Any]]: ...
    def _get_config(self: Self) -> Dict[str, Any]: ...
    def create_session(self: Self, task_id: str) -> Dict[str, object]: ...
    def close_session(self: Self, session_id: str) -> bool: ...
    def emergency_cleanup(self: Self, session_id: str) -> None: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import os
import uuid
import typing
import requests
import tools
import tools.browser_providers
import tools.browser_providers.base