# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from tools.browser_providers.base import CloudBrowserProvider
from tools.managed_tool_gateway import resolve_managed_tool_gateway
from tools.tool_backend_helpers import managed_nous_tools_enabled
from typing import Any, Dict, Optional
from typing_extensions import Self
import logging
import os
import requests
import threading
import uuid

_pending_create_keys: Dict[str, str] = {}
_BASE_URL = 'https://api.browser-use.com/api/v3'
_DEFAULT_MANAGED_TIMEOUT_MINUTES = 5
_DEFAULT_MANAGED_PROXY_COUNTRY_CODE = 'us'
def _get_or_create_pending_create_key(task_id: str) -> str:
    ...

def _clear_pending_create_key(task_id: str) -> None:
    ...

def _should_preserve_pending_create_key(response: requests.Response) -> bool:
    ...

class BrowserUseProvider(CloudBrowserProvider):
    def provider_name(self: Self) -> str: ...
    def is_configured(self: Self) -> bool: ...
    def _get_config_or_none(self: Self) -> Optional[Dict[str, Any]]: ...
    def _get_config(self: Self) -> Dict[str, Any]: ...
    def _headers(self: Self, config: Dict[str, Any]) -> Dict[str, str]: ...
    def create_session(self: Self, task_id: str) -> Dict[str, object]: ...
    def close_session(self: Self, session_id: str) -> bool: ...
    def emergency_cleanup(self: Self, session_id: str) -> None: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import os
import threading
import uuid
import typing
import requests
import tools
import tools.browser_providers
import tools.browser_providers.base
import tools.managed_tool_gateway
import tools.tool_backend_helpers