# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from hermes_constants import get_hermes_home
from pathlib import Path
from plugins.memory.honcho.client import HOST, resolve_active_host, resolve_config_path
from typing import Any
import json
import os
import sys

def clone_honcho_for_profile(profile_name: str) -> bool:
    ...

def _ensure_peer_exists(host_key: str | None) -> bool:
    ...

def cmd_enable(args: Any) -> None:
    ...

def cmd_disable(args: Any) -> None:
    ...

def cmd_sync(args: Any) -> None:
    ...

def sync_honcho_profiles_quiet() -> int:
    ...

_profile_override: str | None = None
def _host_key() -> str:
    ...

def _config_path() -> Path:
    ...

def _local_config_path() -> Path:
    ...

def _read_config() -> dict:
    ...

def _write_config(cfg: dict, path: Path | None) -> None:
    ...

def _resolve_api_key(cfg: dict) -> str:
    ...

def _prompt(label: str, default: str | None, secret: bool) -> str:
    ...

def _ensure_sdk_installed() -> bool:
    ...

def cmd_setup(args: Any) -> None:
    ...

def _active_profile_name() -> str:
    ...

def _all_profile_host_configs() -> list[tuple[str, str, dict]]:
    ...

def cmd_status(args: Any) -> None:
    ...

def _show_peer_cards(hcfg: Any, client: Any) -> None:
    ...

def _cmd_status_all() -> None:
    ...

def cmd_peers(args: Any) -> None:
    ...

def cmd_sessions(args: Any) -> None:
    ...

def cmd_map(args: Any) -> None:
    ...

def cmd_peer(args: Any) -> None:
    ...

def cmd_mode(args: Any) -> None:
    ...

def cmd_tokens(args: Any) -> None:
    ...

def cmd_identity(args: Any) -> None:
    ...

def cmd_migrate(args: Any) -> None:
    ...

def honcho_command(args: Any) -> None:
    ...

def register_cli(subparser: Any) -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import json
import os
import sys
import pathlib
import hermes_constants
import plugins
import plugins.memory
import plugins.memory.honcho
import plugins.memory.honcho.client
import hermes_cli
import hermes_cli.profiles
import getpass
import honcho
import subprocess
import hermes_cli.config
import plugins.memory.honcho.session
import re
import hermes_cli.memory_setup