# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from dataclasses import dataclass, field
from hermes_constants import get_hermes_home
from honcho import Honcho
from pathlib import Path
from typing import Any, TYPE_CHECKING
from typing_extensions import Self
from dataclasses import dataclass
import json
import logging
import os

GLOBAL_CONFIG_PATH = Path.home() / '.honcho' / 'config.json'
HOST = 'hermes'
def resolve_active_host() -> str:
    ...

def resolve_config_path() -> Path:
    ...

_RECALL_MODE_ALIASES = {'auto': 'hybrid'}
_VALID_RECALL_MODES = {'hybrid', 'context', 'tools'}
def _normalize_recall_mode(val: str) -> str:
    ...

def _resolve_bool(host_val: Any, root_val: Any) -> bool:
    ...

_VALID_OBSERVATION_MODES = {'unified', 'directional'}
_OBSERVATION_MODE_ALIASES = {'shared': 'unified', 'separate': 'directional', 'cross': 'directional'}
def _normalize_observation_mode(val: str) -> str:
    ...

_OBSERVATION_PRESETS = {'directional': {'user_observe_me': True, 'user_observe_others': True, 'ai_observe_me': True, 'ai_observe_others': True}, 'unified': {'user_observe_me': True, 'user_observe_others': False, 'ai_observe_me': False, 'ai_observe_others': True}}
def _resolve_observation(mode: str, observation_obj: dict | None) -> dict:
    ...

@dataclass
class HonchoClientConfig:
    @classmethod
    def from_env(cls, workspace_id: str, host: str | None) -> HonchoClientConfig: ...
    @classmethod
    def from_global_config(cls, host: str | None, config_path: Path | None) -> HonchoClientConfig: ...
    @staticmethod
    def _git_repo_name(cwd: str) -> str | None: ...
    def resolve_session_name(self: Self, cwd: str | None, session_title: str | None, session_id: str | None) -> str | None: ...

_honcho_client: Honcho | None = None
def get_honcho_client(config: HonchoClientConfig | None) -> Honcho:
    ...

def reset_honcho_client() -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import json
import os
import logging
import dataclasses
import pathlib
import hermes_constants
import typing
import hermes_cli
import hermes_cli.profiles
import subprocess
import re
import honcho
import hermes_cli.config