# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from aiohttp import web
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, SendResult, is_network_accessible
from typing import Any, Dict, List, Optional
from typing_extensions import Self
import asyncio
import hashlib
import hmac
import json
import logging
import os
import re
import socket
import sqlite3
import time
import uuid

AIOHTTP_AVAILABLE = True
AIOHTTP_AVAILABLE = False
web = None
DEFAULT_HOST = '127.0.0.1'
DEFAULT_PORT = 8642
MAX_STORED_RESPONSES = 100
MAX_REQUEST_BYTES = 1000000
CHAT_COMPLETIONS_SSE_KEEPALIVE_SECONDS = 30.0
MAX_NORMALIZED_TEXT_LENGTH = 65536
MAX_CONTENT_LIST_SIZE = 1000
def _normalize_chat_content(content: Any) -> str:
    ...

def check_api_server_requirements() -> bool:
    ...

class ResponseStore:
    def __init__(self: Self, max_size: int, db_path: str) -> None: ...
    def get(self: Self, response_id: str) -> Optional[Dict[str, Any]]: ...
    def put(self: Self, response_id: str, data: Dict[str, Any]) -> None: ...
    def delete(self: Self, response_id: str) -> bool: ...
    def get_conversation(self: Self, name: str) -> Optional[str]: ...
    def set_conversation(self: Self, name: str, response_id: str) -> None: ...
    def close(self: Self) -> None: ...
    def __len__(self: Self) -> int: ...

_CORS_HEADERS = {'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Allow-Headers': 'Authorization, Content-Type, Idempotency-Key'}
cors_headers = None
response = await handler(request)
cors_middleware = None
def _openai_error(message: str, err_type: str, param: str, code: str) -> Dict[str, Any]:
    ...

body_limit_middleware = None
_SECURITY_HEADERS = {'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'no-referrer'}
response = await handler(request)
security_headers_middleware = None
class _IdempotencyCache:
    def __init__(self: Self, max_items: int, ttl_seconds: int) -> None: ...
    def _purge(self: Self) -> Any: ...

def _make_request_fingerprint(body: Dict[str, Any], keys: List[str]) -> str:
    ...

def _derive_chat_session_id(system_prompt: Optional[str], first_user_message: str) -> str:
    ...

class APIServerAdapter(BasePlatformAdapter):
    def __init__(self: Self, config: PlatformConfig) -> None: ...
    @staticmethod
    def _parse_cors_origins(value: Any) -> tuple[str, ...]: ...
    @staticmethod
    def _resolve_model_name(explicit: str) -> str: ...
    def _cors_headers_for_origin(self: Self, origin: str) -> Optional[Dict[str, str]]: ...
    def _origin_allowed(self: Self, origin: str) -> bool: ...
    def _check_auth(self: Self, request: 'web.Request') -> Optional['web.Response']: ...
    def _ensure_session_db(self: Self) -> Any: ...
    def _create_agent(self: Self, ephemeral_system_prompt: Optional[str], session_id: Optional[str], stream_delta_callback: Any, tool_progress_callback: Any) -> Any: ...
    def _check_jobs_available(self: Self) -> Optional['web.Response']: ...
    def _check_job_id(self: Self, request: 'web.Request') -> tuple: ...
    @staticmethod
    def _extract_output_items(result: Dict[str, Any]) -> List[Dict[str, Any]]: ...
    def _make_run_event_callback(self: Self, run_id: str, loop: 'asyncio.AbstractEventLoop') -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import hashlib
import hmac
import json
import logging
import os
import socket
import re
import sqlite3
import time
import uuid
import typing
import aiohttp
import gateway
import gateway.config
import gateway.platforms
import gateway.platforms.base
import hermes_cli
import hermes_cli.config
import collections
import collections.OrderedDict
import hermes_cli.profiles
import hermes_state
import run_agent
import gateway.run
import hermes_cli.tools_config
import queue
import agent
import agent.display
import cron
import cron.jobs
import hermes_cli.auth