# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from gateway.config import Platform, PlatformConfig
from gateway.session import SessionSource, build_session_key
from hermes_constants import get_hermes_dir
from pathlib import Path
from tools.url_safety import is_safe_url
from typing import Any, Awaitable, Callable, Dict, List, Optional, Tuple
from typing_extensions import Self, TypeAlias
from urllib.parse import urlsplit
from dataclasses import dataclass
import asyncio
import httpx
import ipaddress
import logging
import os
import random
import re
import socket
import subprocess
import sys
import uuid

def utf16_len(s: str) -> int:
    ...

def _prefix_within_utf16_limit(s: str, limit: int) -> str:
    ...

def _custom_unit_to_cp(s: str, budget: int, len_fn: Any) -> int:
    ...

def is_network_accessible(host: str) -> bool:
    ...

def _detect_macos_system_proxy() -> str | None:
    ...

def resolve_proxy_url(platform_env_var: str | None) -> str | None:
    ...

def proxy_kwargs_for_bot(proxy_url: str | None) -> dict:
    ...

def proxy_kwargs_for_aiohttp(proxy_url: str | None) -> tuple[dict, dict]:
    ...

GATEWAY_SECRET_CAPTURE_UNSUPPORTED_MESSAGE = 'Secure secret entry is not supported over messaging. Load this skill in the local CLI to be prompted, or add the key to ~/.hermes/.env manually.'
def safe_url_for_log(url: str, max_len: int) -> str:
    ...

def get_image_cache_dir() -> Path:
    ...

def _looks_like_image(data: bytes) -> bool:
    ...

def cache_image_from_bytes(data: bytes, ext: str) -> str:
    ...

last_exc = None
response = await client.get(url, headers={'User-Agent': 'Mozilla/5.0 (compatible; HermesAgent/1.0)', 'Accept': 'image/*,*/*;q=0.8'})
last_exc = exc
wait = 1.5 * (attempt + 1)
def cleanup_image_cache(max_age_hours: int) -> int:
    ...

def get_audio_cache_dir() -> Path:
    ...

def cache_audio_from_bytes(data: bytes, ext: str) -> str:
    ...

last_exc = None
response = await client.get(url, headers={'User-Agent': 'Mozilla/5.0 (compatible; HermesAgent/1.0)', 'Accept': 'audio/*,*/*;q=0.8'})
last_exc = exc
wait = 1.5 * (attempt + 1)
SUPPORTED_DOCUMENT_TYPES = {'.pdf': 'application/pdf', '.md': 'text/markdown', '.txt': 'text/plain', '.log': 'text/plain', '.zip': 'application/zip', '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', '.pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation'}
def get_document_cache_dir() -> Path:
    ...

def cache_document_from_bytes(data: bytes, filename: str) -> str:
    ...

def cleanup_document_cache(max_age_hours: int) -> int:
    ...

class MessageType(Enum):
class ProcessingOutcome(Enum):
@dataclass
class MessageEvent:
    def is_command(self: Self) -> bool: ...
    def get_command(self: Self) -> Optional[str]: ...
    def get_command_args(self: Self) -> str: ...

@dataclass
class SendResult:
def merge_pending_message_event(pending_messages: Dict[str, MessageEvent], session_key: str, event: MessageEvent) -> None:
    ...

_RETRYABLE_ERROR_PATTERNS = ('connecterror', 'connectionerror', 'connectionreset', 'connectionrefused', 'connecttimeout', 'network', 'broken pipe', 'remotedisconnected', 'eoferror')
MessageHandler: TypeAlias = Callable[[MessageEvent], Awaitable[Optional[str]]]
class BasePlatformAdapter(ABC):
    def __init__(self: Self, config: PlatformConfig, platform: Platform) -> None: ...
    def has_fatal_error(self: Self) -> bool: ...
    def fatal_error_message(self: Self) -> Optional[str]: ...
    def fatal_error_code(self: Self) -> Optional[str]: ...
    def fatal_error_retryable(self: Self) -> bool: ...
    def set_fatal_error_handler(self: Self, handler: Callable[['BasePlatformAdapter'], Awaitable[None] | None]) -> None: ...
    def _mark_connected(self: Self) -> None: ...
    def _mark_disconnected(self: Self) -> None: ...
    def _set_fatal_error(self: Self, code: str, message: str) -> None: ...
    def _acquire_platform_lock(self: Self, scope: str, identity: str, resource_desc: str) -> bool: ...
    def _release_platform_lock(self: Self) -> None: ...
    def name(self: Self) -> str: ...
    def is_connected(self: Self) -> bool: ...
    def set_message_handler(self: Self, handler: MessageHandler) -> None: ...
    def set_busy_session_handler(self: Self, handler: Optional[Callable[[MessageEvent, str], Awaitable[bool]]]) -> None: ...
    def set_session_store(self: Self, session_store: Any) -> None: ...
    @staticmethod
    def _is_animation_url(url: str) -> bool: ...
    @staticmethod
    def extract_images(content: str) -> Tuple[List[Tuple[str, str]], str]: ...
    @staticmethod
    def extract_media(content: str) -> Tuple[List[Tuple[str, bool]], str]: ...
    @staticmethod
    def extract_local_files(content: str) -> Tuple[List[str], str]: ...
    def pause_typing_for_chat(self: Self, chat_id: str) -> None: ...
    def resume_typing_for_chat(self: Self, chat_id: str) -> None: ...
    @staticmethod
    def _is_retryable_error(error: Optional[str]) -> bool: ...
    @staticmethod
    def _is_timeout_error(error: Optional[str]) -> bool: ...
    @staticmethod
    def _merge_caption(existing_text: Optional[str], new_text: str) -> str: ...
    @staticmethod
    def _get_human_delay() -> float: ...
    def has_pending_interrupt(self: Self, session_key: str) -> bool: ...
    def get_pending_message(self: Self, session_key: str) -> Optional[MessageEvent]: ...
    def build_source(self: Self, chat_id: str, chat_name: Optional[str], chat_type: str, user_id: Optional[str], user_name: Optional[str], thread_id: Optional[str], chat_topic: Optional[str], user_id_alt: Optional[str], chat_id_alt: Optional[str]) -> SessionSource: ...
    def format_message(self: Self, content: str) -> str: ...
    @staticmethod
    def truncate_message(content: str, max_length: int, len_fn: Optional['Callable[[str], int]']) -> List[str]: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import ipaddress
import logging
import os
import random
import re
import socket
import subprocess
import sys
import uuid
import abc
import urllib
import urllib.parse
import aiohttp_socks
import dataclasses
import datetime
import pathlib
import typing
import enum
import gateway
import gateway.config
import gateway.session
import hermes_constants
import tools
import tools.url_safety
import httpx
import time
import gateway.status
import posixpath
import tools.tts_tool
import json