# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, MessageEvent, MessageType, SendResult, cache_audio_from_bytes, cache_document_from_bytes, cache_image_from_bytes
from gateway.platforms.helpers import strip_markdown
from typing import Any, Dict, List, Optional
from typing_extensions import Self
from urllib.parse import quote
import asyncio
import httpx
import json
import logging
import os
import re
import uuid

DEFAULT_WEBHOOK_HOST = '127.0.0.1'
DEFAULT_WEBHOOK_PORT = 8645
DEFAULT_WEBHOOK_PATH = '/bluebubbles-webhook'
MAX_TEXT_LENGTH = 4000
_TAPBACK_ADDED = {2000: 'love', 2001: 'like', 2002: 'dislike', 2003: 'laugh', 2004: 'emphasize', 2005: 'question'}
_TAPBACK_REMOVED = {3000: 'love', 3001: 'like', 3002: 'dislike', 3003: 'laugh', 3004: 'emphasize', 3005: 'question'}
_MESSAGE_EVENTS = {'new-message', 'message', 'updated-message'}
def _redact(text: str) -> str:
    ...

def check_bluebubbles_requirements() -> bool:
    ...

def _normalize_server_url(raw: str) -> str:
    ...

class BlueBubblesAdapter(BasePlatformAdapter):
    def __init__(self: Self, config: PlatformConfig) -> None: ...
    def _api_url(self: Self, path: str) -> str: ...
    def _webhook_url(self: Self) -> str: ...
    def format_message(self: Self, content: str) -> str: ...
    def _extract_payload_record(self: Self, payload: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    @staticmethod
    def _value() -> Optional[str]: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import json
import logging
import os
import re
import uuid
import datetime
import typing
import urllib
import urllib.parse
import httpx
import gateway
import gateway.config
import gateway.platforms
import gateway.platforms.base
import gateway.platforms.helpers
import aiohttp