# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime, timezone
from dingtalk_stream import ChatbotHandler, ChatbotMessage
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, MessageEvent, MessageType, SendResult
from gateway.platforms.helpers import MessageDeduplicator
from typing import Any, Dict, Optional
from typing_extensions import Self
import asyncio
import dingtalk_stream
import httpx
import logging
import os
import re
import time
import uuid

DINGTALK_STREAM_AVAILABLE = True
DINGTALK_STREAM_AVAILABLE = False
dingtalk_stream = None
HTTPX_AVAILABLE = True
HTTPX_AVAILABLE = False
httpx = None
MAX_MESSAGE_LENGTH = 20000
RECONNECT_BACKOFF = [2, 5, 10, 30, 60]
_SESSION_WEBHOOKS_MAX = 500
def check_dingtalk_requirements() -> bool:
    ...

class DingTalkAdapter(BasePlatformAdapter):
    def __init__(self: Self, config: PlatformConfig) -> None: ...
    @staticmethod
    def _extract_text(message: 'ChatbotMessage') -> str: ...

class _IncomingHandler:
    def __init__(self: Self, adapter: DingTalkAdapter, loop: asyncio.AbstractEventLoop) -> None: ...
    def process(self: Self, message: 'ChatbotMessage') -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import logging
import os
import re
import time
import uuid
import datetime
import typing
import dingtalk_stream
import httpx
import gateway
import gateway.config
import gateway.platforms
import gateway.platforms.helpers
import gateway.platforms.base