# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from email import encoders
from email.header import decode_header
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, MessageEvent, MessageType, SendResult, cache_document_from_bytes, cache_image_from_bytes
from pathlib import Path
from typing import Any, Dict, List, Optional
from typing_extensions import Self
import asyncio
import email
import imaplib
import logging
import os
import re
import smtplib
import ssl
import uuid

_NOREPLY_PATTERNS = ('noreply', 'no-reply', 'no_reply', 'donotreply', 'do-not-reply', 'mailer-daemon', 'postmaster', 'bounce', 'notifications@', 'automated@', 'auto-confirm', 'auto-reply', 'automailer')
_AUTOMATED_HEADERS = {'Auto-Submitted': lambda v: v.lower() != 'no', 'Precedence': lambda v: v.lower() in ('bulk', 'list', 'junk'), 'X-Auto-Response-Suppress': lambda v: bool(v), 'List-Unsubscribe': lambda v: bool(v)}
MAX_MESSAGE_LENGTH = 50000
_IMAGE_EXTS = {'.jpg', '.jpeg', '.png', '.gif', '.webp'}
def _is_automated_sender(address: str, headers: dict) -> bool:
    ...

def check_email_requirements() -> bool:
    ...

def _decode_header_value(raw: str) -> str:
    ...

def _extract_text_body(msg: email_lib.message.Message) -> str:
    ...

def _strip_html(html: str) -> str:
    ...

def _extract_email_address(raw: str) -> str:
    ...

def _extract_attachments(msg: email_lib.message.Message, skip_attachments: bool) -> List[Dict[str, Any]]:
    ...

class EmailAdapter(BasePlatformAdapter):
    def __init__(self: Self, config: PlatformConfig) -> None: ...
    def _trim_seen_uids(self: Self) -> None: ...
    def _fetch_new_messages(self: Self) -> List[Dict[str, Any]]: ...
    def _send_email(self: Self, to_addr: str, body: str, reply_to_msg_id: Optional[str]) -> str: ...
    def _send_email_with_attachment(self: Self, to_addr: str, body: str, file_path: str, file_name: Optional[str]) -> str: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import imaplib
import logging
import os
import re
import smtplib
import ssl
import uuid
import email.header
import email.mime
import email.mime.multipart
import email.mime.text
import email.mime.base
import pathlib
import typing
import gateway
import gateway.platforms
import gateway.platforms.base
import gateway.config