# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from aiohttp import web
from dataclasses import dataclass, field
from datetime import datetime
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, MessageEvent, MessageType, SUPPORTED_DOCUMENT_TYPES, SendResult, cache_audio_from_bytes, cache_document_from_bytes, cache_image_from_bytes, cache_image_from_url
from gateway.status import acquire_scoped_lock, release_scoped_lock
from hermes_constants import get_hermes_home
from lark_oapi.api.application.v6 import GetApplicationRequest
from lark_oapi.api.im.v1 import CreateFileRequest, CreateFileRequestBody, CreateImageRequest, CreateImageRequestBody, CreateMessageRequest, CreateMessageRequestBody, GetChatRequest, GetMessageRequest, GetMessageResourceRequest, P2ImMessageMessageReadV1, ReplyMessageRequest, ReplyMessageRequestBody, UpdateMessageRequest, UpdateMessageRequestBody
from lark_oapi.core.const import FEISHU_DOMAIN, LARK_DOMAIN
from lark_oapi.event.callback.model.p2_card_action_trigger import P2CardActionTriggerResponse
from lark_oapi.event.dispatcher_handler import EventDispatcherHandler
from lark_oapi.ws import Client
from pathlib import Path
from types import SimpleNamespace
from typing import Any, Dict, List, Optional
from typing_extensions import Self
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode
from urllib.request import Request, urlopen
from dataclasses import dataclass
import aiohttp
import asyncio
import hashlib
import hmac
import itertools
import json
import lark_oapi
import logging
import mimetypes
import os
import qrcode
import re
import threading
import time
import uuid
import websockets

aiohttp = None
web = None
websockets = None
FEISHU_AVAILABLE = True
FEISHU_AVAILABLE = False
lark = None
P2CardActionTriggerResponse = None
EventDispatcherHandler = None
FeishuWSClient = None
FEISHU_DOMAIN = None
LARK_DOMAIN = None
FEISHU_WEBSOCKET_AVAILABLE = websockets is not None
FEISHU_WEBHOOK_AVAILABLE = aiohttp is not None
_IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp'}
_AUDIO_EXTENSIONS = {'.ogg', '.mp3', '.wav', '.m4a', '.aac', '.flac', '.opus', '.webm'}
_VIDEO_EXTENSIONS = {'.mp4', '.mov', '.avi', '.mkv', '.webm', '.m4v', '.3gp'}
_DOCUMENT_MIME_TO_EXT = {mime: ext for ext, mime in SUPPORTED_DOCUMENT_TYPES.items()}
_FEISHU_IMAGE_UPLOAD_TYPE = 'message'
_FEISHU_FILE_UPLOAD_TYPE = 'stream'
_FEISHU_OPUS_UPLOAD_EXTENSIONS = {'.ogg', '.opus'}
_FEISHU_MEDIA_UPLOAD_EXTENSIONS = {'.mp4', '.mov', '.avi', '.m4v'}
_FEISHU_DOC_UPLOAD_TYPES = {'.pdf': 'pdf', '.doc': 'doc', '.docx': 'doc', '.xls': 'xls', '.xlsx': 'xls', '.ppt': 'ppt', '.pptx': 'ppt'}
_MAX_TEXT_INJECT_BYTES = 100 * 1024
_FEISHU_CONNECT_ATTEMPTS = 3
_FEISHU_SEND_ATTEMPTS = 3
_FEISHU_APP_LOCK_SCOPE = 'feishu-app-id'
_DEFAULT_TEXT_BATCH_DELAY_SECONDS = 0.6
_DEFAULT_TEXT_BATCH_MAX_MESSAGES = 8
_DEFAULT_TEXT_BATCH_MAX_CHARS = 4000
_DEFAULT_MEDIA_BATCH_DELAY_SECONDS = 0.8
_DEFAULT_DEDUP_CACHE_SIZE = 2048
_DEFAULT_WEBHOOK_HOST = '127.0.0.1'
_DEFAULT_WEBHOOK_PORT = 8765
_DEFAULT_WEBHOOK_PATH = '/feishu/webhook'
_FEISHU_DEDUP_TTL_SECONDS = 24 * 60 * 60
_FEISHU_SENDER_NAME_TTL_SECONDS = 10 * 60
_FEISHU_WEBHOOK_MAX_BODY_BYTES = 1 * 1024 * 1024
_FEISHU_WEBHOOK_RATE_WINDOW_SECONDS = 60
_FEISHU_WEBHOOK_RATE_LIMIT_MAX = 120
_FEISHU_WEBHOOK_RATE_MAX_KEYS = 4096
_FEISHU_WEBHOOK_BODY_TIMEOUT_SECONDS = 30
_FEISHU_WEBHOOK_ANOMALY_THRESHOLD = 25
_FEISHU_WEBHOOK_ANOMALY_TTL_SECONDS = 6 * 60 * 60
_FEISHU_CARD_ACTION_DEDUP_TTL_SECONDS = 15 * 60
_FEISHU_BOT_MSG_TRACK_SIZE = 512
_FEISHU_REPLY_FALLBACK_CODES = frozenset({230011, 231003})
_FEISHU_ACK_EMOJI = 'OK'
_ONBOARD_ACCOUNTS_URLS = {'feishu': 'https://accounts.feishu.cn', 'lark': 'https://accounts.larksuite.com'}
_ONBOARD_OPEN_URLS = {'feishu': 'https://open.feishu.cn', 'lark': 'https://open.larksuite.com'}
_REGISTRATION_PATH = '/oauth/v1/app/registration'
_ONBOARD_REQUEST_TIMEOUT_S = 10
FALLBACK_POST_TEXT = '[Rich text message]'
FALLBACK_FORWARD_TEXT = '[Merged forward message]'
FALLBACK_SHARE_CHAT_TEXT = '[Shared chat]'
FALLBACK_INTERACTIVE_TEXT = '[Interactive message]'
FALLBACK_IMAGE_TEXT = '[Image]'
FALLBACK_ATTACHMENT_TEXT = '[Attachment]'
_PREFERRED_LOCALES = ('zh_cn', 'en_us')
_SUPPORTED_CARD_TEXT_KEYS = ('title', 'text', 'content', 'label', 'value', 'name', 'summary', 'subtitle', 'description', 'placeholder', 'hint')
_SKIP_TEXT_KEYS = {'tag', 'type', 'msg_type', 'message_type', 'chat_id', 'open_chat_id', 'share_chat_id', 'file_key', 'image_key', 'user_id', 'open_id', 'union_id', 'url', 'href', 'link', 'token', 'template', 'locale'}
@dataclass
class FeishuPostMediaRef:
@dataclass
class FeishuPostParseResult:
@dataclass
class FeishuNormalizedMessage:
@dataclass
class FeishuAdapterSettings:
@dataclass
class FeishuGroupRule:
@dataclass
class FeishuBatchState:
def _escape_markdown_text(text: str) -> str:
    ...

def _to_boolean(value: Any) -> bool:
    ...

def _is_style_enabled(style: Dict[str, Any] | None, key: str) -> bool:
    ...

def _wrap_inline_code(text: str) -> str:
    ...

def _sanitize_fence_language(language: str) -> str:
    ...

def _render_text_element(element: Dict[str, Any]) -> str:
    ...

def _render_code_block_element(element: Dict[str, Any]) -> str:
    ...

def _strip_markdown_to_plain_text(text: str) -> str:
    ...

def _coerce_int(value: Any, default: Optional[int], min_value: int) -> Optional[int]:
    ...

def _coerce_required_int(value: Any, default: int, min_value: int) -> int:
    ...

def _build_markdown_post_payload(content: str) -> str:
    ...

def parse_feishu_post_content(raw_content: str) -> FeishuPostParseResult:
    ...

def parse_feishu_post_payload(payload: Any) -> FeishuPostParseResult:
    ...

def _resolve_post_payload(payload: Any) -> Dict[str, Any]:
    ...

def _resolve_locale_payload(payload: Any) -> Dict[str, Any]:
    ...

def _to_post_payload(candidate: Any) -> Dict[str, Any]:
    ...

def _render_post_element(element: Any, image_keys: List[str], media_refs: List[FeishuPostMediaRef], mentioned_ids: List[str]) -> str:
    ...

def _render_nested_post(value: Any, image_keys: List[str], media_refs: List[FeishuPostMediaRef], mentioned_ids: List[str]) -> str:
    ...

def normalize_feishu_message() -> FeishuNormalizedMessage:
    ...

def _load_feishu_payload(raw_content: str) -> Dict[str, Any]:
    ...

def _normalize_merge_forward_message(payload: Dict[str, Any]) -> FeishuNormalizedMessage:
    ...

def _normalize_share_chat_message(payload: Dict[str, Any]) -> FeishuNormalizedMessage:
    ...

def _normalize_interactive_message(message_type: str, payload: Dict[str, Any]) -> FeishuNormalizedMessage:
    ...

def _collect_forward_entries(payload: Dict[str, Any]) -> List[str]:
    ...

def _collect_card_lines(payload: Any) -> List[str]:
    ...

def _collect_action_labels(payload: Any) -> List[str]:
    ...

def _collect_text_segments(value: Any) -> List[str]:
    ...

def _build_media_ref_from_payload(payload: Dict[str, Any]) -> FeishuPostMediaRef:
    ...

def _attachment_placeholder(file_name: str) -> str:
    ...

def _find_header_title(payload: Any) -> str:
    ...

def _find_first_text(payload: Any) -> str:
    ...

def _walk_nodes(value: Any) -> Any:
    ...

def _first_non_empty_text() -> str:
    ...

def _normalize_feishu_text(text: str) -> str:
    ...

def _unique_lines(lines: List[str]) -> List[str]:
    ...

def _run_official_feishu_ws_client(ws_client: Any, adapter: Any) -> None:
    ...

def check_feishu_requirements() -> bool:
    ...

class FeishuAdapter(BasePlatformAdapter):
    def __init__(self: Self, config: PlatformConfig) -> None: ...
    @staticmethod
    def _load_settings(extra: Dict[str, Any]) -> FeishuAdapterSettings: ...
    def _apply_settings(self: Self, settings: FeishuAdapterSettings) -> None: ...
    def _build_event_handler(self: Self) -> Any: ...
    def _reset_batch_buffers(self: Self) -> None: ...
    def _disable_websocket_auto_reconnect(self: Self) -> None: ...
    def format_message(self: Self, content: str) -> str: ...
    def _on_message_event(self: Self, data: Any) -> None: ...
    def _on_message_read_event(self: Self, data: P2ImMessageMessageReadV1) -> None: ...
    def _on_bot_added_to_chat(self: Self, data: Any) -> None: ...
    def _on_bot_removed_from_chat(self: Self, data: Any) -> None: ...
    def _on_reaction_event(self: Self, event_type: str, data: Any) -> None: ...
    def _on_card_action_trigger(self: Self, data: Any) -> Any: ...
    def _is_card_action_duplicate(self: Self, token: str) -> bool: ...
    def _get_chat_lock(self: Self, chat_id: str) -> asyncio.Lock: ...
    def _record_webhook_anomaly(self: Self, remote_ip: str, status: str) -> None: ...
    def _clear_webhook_anomaly(self: Self, remote_ip: str) -> None: ...
    def _should_batch_media_event(self: Self, event: MessageEvent) -> bool: ...
    def _media_batch_key(self: Self, event: MessageEvent) -> str: ...
    @staticmethod
    def _media_batch_is_compatible(existing: MessageEvent, incoming: MessageEvent) -> bool: ...
    def _schedule_media_batch_flush(self: Self, key: str) -> None: ...
    @staticmethod
    def _guess_remote_extension(url: str) -> str: ...
    @staticmethod
    def _derive_remote_filename(file_url: str) -> str: ...
    @staticmethod
    def _namespace_from_mapping(value: Any) -> Any: ...
    def _is_webhook_signature_valid(self: Self, headers: Any, body_bytes: bytes) -> bool: ...
    def _check_webhook_rate_limit(self: Self, rate_key: str) -> bool: ...
    def _text_batch_key(self: Self, event: MessageEvent) -> str: ...
    @staticmethod
    def _text_batch_is_compatible(existing: MessageEvent, incoming: MessageEvent) -> bool: ...
    def _schedule_text_batch_flush(self: Self, key: str) -> None: ...
    @staticmethod
    def _reschedule_batch_task(task_map: Dict[str, asyncio.Task], key: str, flush_fn: Any) -> None: ...
    @staticmethod
    def _resolve_media_message_type(media_type: str) -> MessageType: ...
    def _resolve_normalized_message_type(self: Self, normalized: FeishuNormalizedMessage, media_types: List[str]) -> MessageType: ...
    def _normalize_inbound_text(self: Self, text: str) -> str: ...
    @staticmethod
    def _read_binary_response(response: Any) -> bytes: ...
    @staticmethod
    def _get_response_header(response: Any, name: str) -> str: ...
    @staticmethod
    def _guess_extension(filename: str, content_type: str, default: str) -> str: ...
    @staticmethod
    def _normalize_media_type(content_type: str) -> str: ...
    @staticmethod
    def _guess_document_media_type(filename: str) -> str: ...
    @staticmethod
    def _display_name_from_cached_path(path: str) -> str: ...
    @staticmethod
    def _guess_media_type_from_filename(filename: str) -> str: ...
    @staticmethod
    def _map_chat_type(raw_chat_type: str) -> str: ...
    @staticmethod
    def _resolve_source_chat_type() -> str: ...
    def _extract_text_from_raw_content(self: Self) -> Optional[str]: ...
    @staticmethod
    def _default_image_media_type(ext: str) -> str: ...
    @staticmethod
    def _log_background_failure(future: Any) -> None: ...
    def _allow_group_message(self: Self, sender_id: Any, chat_id: str) -> bool: ...
    def _should_accept_group_message(self: Self, message: Any, sender_id: Any, chat_id: str) -> bool: ...
    def _message_mentions_bot(self: Self, mentions: List[Any]) -> bool: ...
    def _post_mentions_bot(self: Self, mentioned_ids: List[str]) -> bool: ...
    def _load_seen_message_ids(self: Self) -> None: ...
    def _persist_seen_message_ids(self: Self) -> None: ...
    def _is_duplicate(self: Self, message_id: str) -> bool: ...
    def _build_outbound_payload(self: Self, content: str) -> tuple[str, str]: ...
    @staticmethod
    def _response_succeeded(response: Any) -> bool: ...
    @staticmethod
    def _extract_response_field(response: Any, field_name: str) -> Any: ...
    def _response_error_result(self: Self, response: Any) -> SendResult: ...
    def _finalize_send_result(self: Self, response: Any, default_message: str) -> SendResult: ...
    def _build_lark_client(self: Self, domain: Any) -> Any: ...
    @staticmethod
    def _build_get_chat_request(chat_id: str) -> Any: ...
    @staticmethod
    def _build_get_message_request(message_id: str) -> Any: ...
    @staticmethod
    def _build_message_resource_request() -> Any: ...
    @staticmethod
    def _build_get_application_request() -> Any: ...
    @staticmethod
    def _build_reply_message_body() -> Any: ...
    @staticmethod
    def _build_reply_message_request(message_id: str, request_body: Any) -> Any: ...
    @staticmethod
    def _build_update_message_body() -> Any: ...
    @staticmethod
    def _build_update_message_request(message_id: str, request_body: Any) -> Any: ...
    @staticmethod
    def _build_create_message_body() -> Any: ...
    @staticmethod
    def _build_create_message_request(receive_id_type: str, request_body: Any) -> Any: ...
    @staticmethod
    def _build_image_upload_body() -> Any: ...
    @staticmethod
    def _build_image_upload_request(request_body: Any) -> Any: ...
    @staticmethod
    def _build_file_upload_body() -> Any: ...
    @staticmethod
    def _build_file_upload_request(request_body: Any) -> Any: ...
    def _build_post_payload(self: Self, content: str) -> str: ...
    def _build_media_post_payload(self: Self) -> str: ...
    @staticmethod
    def _resolve_outbound_file_routing() -> tuple[str, str]: ...

def _accounts_base_url(domain: str) -> str:
    ...

def _onboard_open_base_url(domain: str) -> str:
    ...

def _post_registration(base_url: str, body: Dict[str, str]) -> dict:
    ...

def _init_registration(domain: str) -> None:
    ...

def _begin_registration(domain: str) -> dict:
    ...

def _poll_registration() -> Optional[dict]:
    ...

_qrcode_mod = None
def _render_qr(url: str) -> bool:
    ...

def probe_bot(app_id: str, app_secret: str, domain: str) -> Optional[dict]:
    ...

def _build_onboard_client(app_id: str, app_secret: str, domain: str) -> Any:
    ...

def _parse_bot_response(data: dict) -> Optional[dict]:
    ...

def _probe_bot_sdk(app_id: str, app_secret: str, domain: str) -> Optional[dict]:
    ...

def _probe_bot_http(app_id: str, app_secret: str, domain: str) -> Optional[dict]:
    ...

def qr_register() -> Optional[dict]:
    ...

def _qr_register_inner() -> Optional[dict]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import asyncio
import hashlib
import hmac
import itertools
import json
import logging
import mimetypes
import os
import re
import threading
import time
import uuid
import dataclasses
import datetime
import pathlib
import types
import typing
import urllib
import urllib.error
import urllib.parse
import urllib.request
import aiohttp
import websockets
import lark_oapi
import lark_oapi.api
import lark_oapi.api.application
import lark_oapi.api.application.v6
import lark_oapi.api.im
import lark_oapi.api.im.v1
import lark_oapi.core
import lark_oapi.core.const
import lark_oapi.event
import lark_oapi.event.callback
import lark_oapi.event.callback.model
import lark_oapi.event.callback.model.p2_card_action_trigger
import lark_oapi.event.dispatcher_handler
import lark_oapi.ws
import gateway
import gateway.config
import gateway.platforms
import gateway.platforms.base
import gateway.status
import hermes_constants
import gateway.platforms.helpers
import lark_oapi.ws.client
import io
import tools
import tools.approval
import gateway.session
import tools.url_safety
import httpx
import posixpath
import lark_oapi.api.contact
import lark_oapi.api.contact.v3
import qrcode