# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, MessageEvent, MessageType, SendResult
from typing import Any, Dict, Optional, Set
from typing_extensions import Self
import aiohttp
import asyncio
import json
import logging
import os
import time
import uuid

AIOHTTP_AVAILABLE = True
AIOHTTP_AVAILABLE = False
aiohttp = None
def check_ha_requirements() -> bool:
    ...

class HomeAssistantAdapter(BasePlatformAdapter):
    def __init__(self: Self, config: PlatformConfig) -> None: ...
    def _next_id(self: Self) -> int: ...
    @staticmethod
    def _format_state_change(entity_id: str, old_state: Dict[str, Any], new_state: Dict[str, Any]) -> Optional[str]: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import json
import logging
import os
import time
import uuid
import datetime
import typing
import aiohttp
import gateway
import gateway.config
import gateway.platforms
import gateway.platforms.base