# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, MessageEvent, MessageType, SendResult
from gateway.platforms.helpers import MessageDeduplicator
from pathlib import Path
from typing import Any, Dict, List, Optional
from typing_extensions import Self
import asyncio
import json
import logging
import os
import re

MAX_POST_LENGTH = 4000
_CHANNEL_TYPE_MAP = {'D': 'dm', 'G': 'group', 'P': 'group', 'O': 'channel'}
_RECONNECT_BASE_DELAY = 2.0
_RECONNECT_MAX_DELAY = 60.0
_RECONNECT_JITTER = 0.2
def check_mattermost_requirements() -> bool:
    ...

class MattermostAdapter(BasePlatformAdapter):
    def __init__(self: Self, config: PlatformConfig) -> None: ...
    def _headers(self: Self) -> Dict[str, str]: ...
    def format_message(self: Self, content: str) -> str: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import asyncio
import json
import logging
import os
import re
import pathlib
import typing
import gateway
import gateway.config
import gateway.platforms
import gateway.platforms.helpers
import gateway.platforms.base
import aiohttp
import tools
import tools.url_safety
import mimetypes
import random