# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime, timezone
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, MessageEvent, MessageType, SendResult, cache_audio_from_bytes, cache_document_from_bytes, cache_image_from_bytes, cache_image_from_url
from gateway.platforms.helpers import redact_phone
from pathlib import Path
from typing import Any, Dict, List, Optional
from typing_extensions import Self
from urllib.parse import quote, unquote
import asyncio
import base64
import httpx
import json
import logging
import os
import random
import re
import time

SIGNAL_MAX_ATTACHMENT_SIZE = 100 * 1024 * 1024
MAX_MESSAGE_LENGTH = 8000
TYPING_INTERVAL = 8.0
SSE_RETRY_DELAY_INITIAL = 2.0
SSE_RETRY_DELAY_MAX = 60.0
HEALTH_CHECK_INTERVAL = 30.0
HEALTH_CHECK_STALE_THRESHOLD = 120.0
def _parse_comma_list(value: str) -> List[str]:
    ...

def _guess_extension(data: bytes) -> str:
    ...

def _is_image_ext(ext: str) -> bool:
    ...

def _is_audio_ext(ext: str) -> bool:
    ...

_EXT_TO_MIME = {'.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png', '.gif': 'image/gif', '.webp': 'image/webp', '.ogg': 'audio/ogg', '.mp3': 'audio/mpeg', '.wav': 'audio/wav', '.m4a': 'audio/mp4', '.aac': 'audio/aac', '.mp4': 'video/mp4', '.pdf': 'application/pdf', '.zip': 'application/zip'}
def _ext_to_mime(ext: str) -> str:
    ...

def _render_mentions(text: str, mentions: list) -> str:
    ...

def check_signal_requirements() -> bool:
    ...

class SignalAdapter(BasePlatformAdapter):
    def __init__(self: Self, config: PlatformConfig) -> None: ...
    def _force_reconnect(self: Self) -> None: ...
    def _track_sent_timestamp(self: Self, rpc_result: Any) -> None: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import base64
import json
import logging
import os
import random
import re
import time
import datetime
import pathlib
import typing
import urllib
import urllib.parse
import httpx
import gateway
import gateway.config
import gateway.platforms
import gateway.platforms.base
import gateway.platforms.helpers