# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, MessageEvent, MessageType, SendResult
from gateway.platforms.helpers import redact_phone, strip_markdown
from typing import Any, Dict, Optional
from typing_extensions import Self
import asyncio
import base64
import hashlib
import hmac
import logging
import os
import urllib.parse

TWILIO_API_BASE = 'https://api.twilio.com/2010-04-01/Accounts'
MAX_SMS_LENGTH = 1600
DEFAULT_WEBHOOK_PORT = 8080
DEFAULT_WEBHOOK_HOST = '0.0.0.0'
def check_sms_requirements() -> bool:
    ...

class SmsAdapter(BasePlatformAdapter):
    def __init__(self: Self, config: PlatformConfig) -> None: ...
    def _basic_auth_header(self: Self) -> str: ...
    def format_message(self: Self, content: str) -> str: ...
    def _validate_twilio_signature(self: Self, url: str, post_params: dict, signature: str) -> bool: ...
    def _check_signature(self: Self, url: str, post_params: dict, signature: str) -> bool: ...
    @staticmethod
    def _port_variant_url(url: str) -> str | None: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import base64
import hashlib
import hmac
import logging
import os
import urllib
import urllib.parse
import typing
import gateway
import gateway.config
import gateway.platforms
import gateway.platforms.base
import gateway.platforms.helpers
import aiohttp