# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, MessageEvent, MessageType, ProcessingOutcome, SUPPORTED_DOCUMENT_TYPES, SendResult, _prefix_within_utf16_limit, cache_audio_from_bytes, cache_document_from_bytes, cache_image_from_bytes, utf16_len
from gateway.platforms.telegram_network import TelegramFallbackTransport, discover_fallback_ips, parse_fallback_ip_env
from pathlib import Path
from telegram import Bot, InlineKeyboardButton, InlineKeyboardMarkup, Message, Update
from telegram.constants import ChatType, ParseMode
from telegram.ext import Application, CallbackQueryHandler, CommandHandler, ContextTypes, MessageHandler, filters
from telegram.request import HTTPXRequest
from typing import Any, Dict, List, Optional
from typing_extensions import Self
Any
import asyncio
import json
import logging
import os
import re
import sys

TELEGRAM_AVAILABLE = True
TELEGRAM_AVAILABLE = False
Update: Any
Bot: Any
Message: Any
InlineKeyboardButton: Any
InlineKeyboardMarkup: Any
Application: Any
CommandHandler: Any
CallbackQueryHandler: Any
TelegramMessageHandler: Any
HTTPXRequest: Any
filters = None
ParseMode = None
ChatType = None
class _MockContextTypes:
ContextTypes = _MockContextTypes
def check_telegram_requirements() -> bool:
    ...

def _escape_mdv2(text: str) -> str:
    ...

def _strip_mdv2(text: str) -> str:
    ...

class TelegramAdapter(BasePlatformAdapter):
    def __init__(self: Self, config: PlatformConfig) -> None: ...
    def _fallback_ips(self: Self) -> list[str]: ...
    @staticmethod
    def _looks_like_polling_conflict(error: Exception) -> bool: ...
    @staticmethod
    def _looks_like_network_error(error: Exception) -> bool: ...
    def _persist_dm_topic_thread_id(self: Self, chat_id: int, topic_name: str, thread_id: int) -> None: ...
    def _should_thread_reply(self: Self, reply_to: Optional[str], chunk_index: int) -> bool: ...
    def _build_model_keyboard(self: Self, models: list, page: int) -> tuple: ...
    def format_message(self: Self, content: str) -> str: ...
    def _telegram_require_mention(self: Self) -> bool: ...
    def _telegram_free_response_chats(self: Self) -> set[str]: ...
    def _compile_mention_patterns(self: Self) -> List[re.Pattern]: ...
    def _is_group_chat(self: Self, message: Message) -> bool: ...
    def _is_reply_to_bot(self: Self, message: Message) -> bool: ...
    def _message_mentions_bot(self: Self, message: Message) -> bool: ...
    def _message_matches_mention_patterns(self: Self, message: Message) -> bool: ...
    def _clean_bot_trigger_text(self: Self, text: Optional[str]) -> Optional[str]: ...
    def _should_process_message(self: Self, message: Message) -> bool: ...
    def _text_batch_key(self: Self, event: MessageEvent) -> str: ...
    def _enqueue_text_event(self: Self, event: MessageEvent) -> None: ...
    def _photo_batch_key(self: Self, event: MessageEvent, msg: Message) -> str: ...
    def _enqueue_photo_event(self: Self, batch_key: str, event: MessageEvent) -> None: ...
    def _reload_dm_topics_from_config(self: Self) -> None: ...
    def _get_dm_topic_info(self: Self, chat_id: str, thread_id: Optional[str]) -> Optional[Dict[str, Any]]: ...
    def _cache_dm_topic_from_message(self: Self, chat_id: str, thread_id: str, topic_name: str) -> None: ...
    def _build_message_event(self: Self, message: Message, msg_type: MessageType) -> MessageEvent: ...
    def _reactions_enabled(self: Self) -> bool: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import json
import logging
import os
import re
import typing
import telegram.ext
import telegram.constants
import telegram.request
import sys
import pathlib
import gateway
import gateway.config
import gateway.platforms
import gateway.platforms.base
import gateway.platforms.telegram_network
import telegram.error
import hermes_constants
import yaml
import urllib
import urllib.parse
import hermes_cli
import hermes_cli.commands
import itertools
import hermes_cli.providers
import tools
import tools.approval
import tools.url_safety
import httpx
import gateway.session
import posixpath
import gateway.sticker_cache
import tools.vision_tools