# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from typing import Any, Iterable, Optional
from typing_extensions import Self
import asyncio
import httpx
import ipaddress
import logging
import os
import socket

_TELEGRAM_API_HOST = 'api.telegram.org'
_DOH_TIMEOUT = 4.0
_DOH_PROVIDERS: list[dict] = [{'url': 'https://dns.google/resolve', 'params': {'name': _TELEGRAM_API_HOST, 'type': 'A'}, 'headers': {}}, {'url': 'https://cloudflare-dns.com/dns-query', 'params': {'name': _TELEGRAM_API_HOST, 'type': 'A'}, 'headers': {'Accept': 'application/dns-json'}}]
_SEED_FALLBACK_IPS: list[str] = ['149.154.167.220']
def _resolve_proxy_url() -> str | None:
    ...

class TelegramFallbackTransport:
    def __init__(self: Self, fallback_ips: Iterable[str]) -> None: ...

def _normalize_fallback_ips(values: Iterable[str]) -> list[str]:
    ...

def parse_fallback_ip_env(value: str | None) -> list[str]:
    ...

def _resolve_system_dns() -> set[str]:
    ...

resp = await client.get(provider['url'], params=provider['params'], headers=provider['headers'])
ips: list[str] = []
doh_tasks = [_query_doh_provider(client, p) for p in _DOH_PROVIDERS]
results = await asyncio.gather(system_dns_task, *doh_tasks, return_exceptions=True)
system_ips: set[str] = results[0] if isinstance(results[0], set) else set()
doh_ips: list[str] = []
seen: set[str] = set()
candidates: list[str] = []
def _rewrite_request_for_ip(request: httpx.Request, ip: str) -> httpx.Request:
    ...

def _is_retryable_connect_error(exc: Exception) -> bool:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import asyncio
import ipaddress
import logging
import os
import socket
import typing
import httpx
import gateway
import gateway.platforms
import gateway.platforms.base