# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from aiohttp import web
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, MessageEvent, MessageType, SendResult
from typing import Any, Dict, List, Optional
from typing_extensions import Self
import asyncio
import hashlib
import hmac
import json
import logging
import os
import re
import subprocess
import time

AIOHTTP_AVAILABLE = True
AIOHTTP_AVAILABLE = False
web = None
DEFAULT_HOST = '0.0.0.0'
DEFAULT_PORT = 8644
_INSECURE_NO_AUTH = 'INSECURE_NO_AUTH'
_DYNAMIC_ROUTES_FILENAME = 'webhook_subscriptions.json'
def check_webhook_requirements() -> bool:
    ...

class WebhookAdapter(BasePlatformAdapter):
    def __init__(self: Self, config: PlatformConfig) -> None: ...
    def _prune_delivery_info(self: Self, now: float) -> None: ...
    def _reload_dynamic_routes(self: Self) -> None: ...
    def _validate_signature(self: Self, request: 'web.Request', body: bytes, secret: str) -> bool: ...
    def _render_prompt(self: Self, template: str, payload: dict, event_type: str, route_name: str) -> str: ...
    def _render_delivery_extra(self: Self, extra: dict, payload: dict) -> dict: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import hashlib
import hmac
import json
import logging
import os
import re
import subprocess
import time
import typing
import aiohttp
import gateway
import gateway.config
import gateway.platforms
import gateway.platforms.base
import socket
import hermes_constants
import urllib
import urllib.parse
import agent
import agent.skill_commands