# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from typing import Any, Optional
from typing_extensions import Self
from xml.etree import ElementTree
import base64
import hashlib
import os
import secrets
import socket
import struct

class WeComCryptoError(Exception): ...
class SignatureError(WeComCryptoError):
class DecryptError(WeComCryptoError):
class EncryptError(WeComCryptoError):
class PKCS7Encoder:
    @classmethod
    def encode(cls, text: bytes) -> bytes: ...
    @classmethod
    def decode(cls, decrypted: bytes) -> bytes: ...

def _sha1_signature(token: str, timestamp: str, nonce: str, encrypt: str) -> str:
    ...

class WXBizMsgCrypt:
    def __init__(self: Self, token: str, encoding_aes_key: str, receive_id: str) -> None: ...
    def verify_url(self: Self, msg_signature: str, timestamp: str, nonce: str, echostr: str) -> str: ...
    def decrypt(self: Self, msg_signature: str, timestamp: str, nonce: str, encrypt: str) -> bytes: ...
    def encrypt(self: Self, plaintext: str, nonce: Optional[str], timestamp: Optional[str]) -> str: ...
    def _encrypt_bytes(self: Self, raw: bytes) -> str: ...
    @staticmethod
    def _random_nonce(length: int) -> str: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import base64
import hashlib
import os
import secrets
import socket
import struct
import typing
import xml
import xml.etree
import xml.etree.ElementTree
import cryptography
import cryptography.hazmat
import cryptography.hazmat.backends
import cryptography.hazmat.backends.default_backend
import cryptography.hazmat.primitives
import cryptography.hazmat.primitives.ciphers
import cryptography.hazmat.primitives.ciphers.Cipher
import cryptography.hazmat.primitives.ciphers.algorithms
import cryptography.hazmat.primitives.ciphers.modes
import time