# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from datetime import datetime, timezone
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, MessageEvent, MessageType, SendResult, cache_document_from_bytes, cache_image_from_bytes
from gateway.platforms.helpers import MessageDeduplicator
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
from typing_extensions import Self
from urllib.parse import unquote, urlparse
import aiohttp
import asyncio
import base64
import hashlib
import httpx
import json
import logging
import mimetypes
import os
import re
import time
import uuid

AIOHTTP_AVAILABLE = True
AIOHTTP_AVAILABLE = False
aiohttp = None
HTTPX_AVAILABLE = True
HTTPX_AVAILABLE = False
httpx = None
DEFAULT_WS_URL = 'wss://openws.work.weixin.qq.com'
APP_CMD_SUBSCRIBE = 'aibot_subscribe'
APP_CMD_CALLBACK = 'aibot_msg_callback'
APP_CMD_LEGACY_CALLBACK = 'aibot_callback'
APP_CMD_EVENT_CALLBACK = 'aibot_event_callback'
APP_CMD_SEND = 'aibot_send_msg'
APP_CMD_RESPONSE = 'aibot_respond_msg'
APP_CMD_PING = 'ping'
APP_CMD_UPLOAD_MEDIA_INIT = 'aibot_upload_media_init'
APP_CMD_UPLOAD_MEDIA_CHUNK = 'aibot_upload_media_chunk'
APP_CMD_UPLOAD_MEDIA_FINISH = 'aibot_upload_media_finish'
CALLBACK_COMMANDS = {APP_CMD_CALLBACK, APP_CMD_LEGACY_CALLBACK}
NON_RESPONSE_COMMANDS = CALLBACK_COMMANDS | {APP_CMD_EVENT_CALLBACK}
MAX_MESSAGE_LENGTH = 4000
CONNECT_TIMEOUT_SECONDS = 20.0
REQUEST_TIMEOUT_SECONDS = 15.0
HEARTBEAT_INTERVAL_SECONDS = 30.0
RECONNECT_BACKOFF = [2, 5, 10, 30, 60]
DEDUP_MAX_SIZE = 1000
IMAGE_MAX_BYTES = 10 * 1024 * 1024
VIDEO_MAX_BYTES = 10 * 1024 * 1024
VOICE_MAX_BYTES = 2 * 1024 * 1024
FILE_MAX_BYTES = 20 * 1024 * 1024
ABSOLUTE_MAX_BYTES = FILE_MAX_BYTES
UPLOAD_CHUNK_SIZE = 512 * 1024
MAX_UPLOAD_CHUNKS = 100
VOICE_SUPPORTED_MIMES = {'audio/amr'}
def check_wecom_requirements() -> bool:
    ...

def _coerce_list(value: Any) -> List[str]:
    ...

def _normalize_entry(raw: str) -> str:
    ...

def _entry_matches(entries: List[str], target: str) -> bool:
    ...

class WeComAdapter(BasePlatformAdapter):
    def __init__(self: Self, config: PlatformConfig) -> None: ...
    def _fail_pending_responses(self: Self, exc: Exception) -> None: ...
    @staticmethod
    def _new_req_id(prefix: str) -> str: ...
    @staticmethod
    def _payload_req_id(payload: Dict[str, Any]) -> str: ...
    @staticmethod
    def _parse_json(raw: Any) -> Optional[Dict[str, Any]]: ...
    def _text_batch_key(self: Self, event: MessageEvent) -> str: ...
    def _enqueue_text_event(self: Self, event: MessageEvent) -> None: ...
    @staticmethod
    def _extract_text(body: Dict[str, Any]) -> Tuple[str, Optional[str]]: ...
    @staticmethod
    def _decode_base64(data: str) -> bytes: ...
    @staticmethod
    def _detect_image_ext(data: bytes) -> str: ...
    @staticmethod
    def _mime_for_ext(ext: str, fallback: str) -> str: ...
    @staticmethod
    def _guess_extension(url: str, content_type: str, fallback: str) -> str: ...
    @staticmethod
    def _guess_filename(url: str, content_disposition: Optional[str], content_type: str) -> str: ...
    @staticmethod
    def _derive_message_type(body: Dict[str, Any], text: str, media_types: List[str]) -> MessageType: ...
    def _is_dm_allowed(self: Self, sender_id: str) -> bool: ...
    def _is_group_allowed(self: Self, chat_id: str, sender_id: str) -> bool: ...
    def _resolve_group_cfg(self: Self, chat_id: str) -> Dict[str, Any]: ...
    def _remember_reply_req_id(self: Self, message_id: str, req_id: str) -> None: ...
    def _reply_req_id_for_message(self: Self, reply_to: Optional[str]) -> Optional[str]: ...
    @staticmethod
    def _guess_mime_type(filename: str) -> str: ...
    @staticmethod
    def _normalize_content_type(content_type: str, filename: str) -> str: ...
    @staticmethod
    def _detect_wecom_media_type(content_type: str) -> str: ...
    @staticmethod
    def _apply_file_size_limits(file_size: int, detected_type: str, content_type: Optional[str]) -> Dict[str, Any]: ...
    @staticmethod
    def _response_error(response: Dict[str, Any]) -> Optional[str]: ...
    @classmethod
    def _raise_for_wecom_error(cls, response: Dict[str, Any], operation: str) -> None: ...
    @staticmethod
    def _decrypt_file_bytes(encrypted_data: bytes, aes_key: str) -> bytes: ...
    @staticmethod
    def _looks_like_url(media_source: str) -> bool: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import asyncio
import base64
import hashlib
import json
import logging
import mimetypes
import os
import re
import time
import uuid
import datetime
import pathlib
import typing
import urllib
import urllib.parse
import aiohttp
import httpx
import gateway
import gateway.config
import gateway.platforms
import gateway.platforms.helpers
import gateway.platforms.base
import gateway.session
import cryptography
import cryptography.hazmat
import cryptography.hazmat.primitives
import cryptography.hazmat.primitives.ciphers
import cryptography.hazmat.primitives.ciphers.Cipher
import cryptography.hazmat.primitives.ciphers.algorithms
import cryptography.hazmat.primitives.ciphers.modes
import tools
import tools.url_safety