# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from datetime import datetime
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, MessageEvent, MessageType, SendResult, cache_audio_from_bytes, cache_document_from_bytes, cache_image_from_bytes
from gateway.platforms.helpers import MessageDeduplicator
from hermes_constants import get_hermes_home
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
from typing_extensions import Self
from urllib.parse import quote
from utils import atomic_json_write
import aiohttp
import asyncio
import base64
import hashlib
import json
import logging
import mimetypes
import os
import qrcode
import re
import secrets
import struct
import tempfile
import time
import uuid

AIOHTTP_AVAILABLE = True
aiohttp = None
AIOHTTP_AVAILABLE = False
CRYPTO_AVAILABLE = True
default_backend = None
Cipher = None
algorithms = None
modes = None
CRYPTO_AVAILABLE = False
ILINK_BASE_URL = 'https://ilinkai.weixin.qq.com'
WEIXIN_CDN_BASE_URL = 'https://novac2c.cdn.weixin.qq.com/c2c'
ILINK_APP_ID = 'bot'
CHANNEL_VERSION = '2.2.0'
ILINK_APP_CLIENT_VERSION = 2 << 16 | 2 << 8 | 0
EP_GET_UPDATES = 'ilink/bot/getupdates'
EP_SEND_MESSAGE = 'ilink/bot/sendmessage'
EP_SEND_TYPING = 'ilink/bot/sendtyping'
EP_GET_CONFIG = 'ilink/bot/getconfig'
EP_GET_UPLOAD_URL = 'ilink/bot/getuploadurl'
EP_GET_BOT_QR = 'ilink/bot/get_bot_qrcode'
EP_GET_QR_STATUS = 'ilink/bot/get_qrcode_status'
LONG_POLL_TIMEOUT_MS = 35000
API_TIMEOUT_MS = 15000
CONFIG_TIMEOUT_MS = 10000
QR_TIMEOUT_MS = 35000
MAX_CONSECUTIVE_FAILURES = 3
RETRY_DELAY_SECONDS = 2
BACKOFF_DELAY_SECONDS = 30
SESSION_EXPIRED_ERRCODE = -14
MESSAGE_DEDUP_TTL_SECONDS = 300
MEDIA_IMAGE = 1
MEDIA_VIDEO = 2
MEDIA_FILE = 3
MEDIA_VOICE = 4
ITEM_TEXT = 1
ITEM_IMAGE = 2
ITEM_VOICE = 3
ITEM_FILE = 4
ITEM_VIDEO = 5
MSG_TYPE_USER = 1
MSG_TYPE_BOT = 2
MSG_STATE_FINISH = 2
TYPING_START = 1
TYPING_STOP = 2
def check_weixin_requirements() -> bool:
    ...

def _safe_id(value: Optional[str], keep: int) -> str:
    ...

def _json_dumps(payload: Dict[str, Any]) -> str:
    ...

def _pkcs7_pad(data: bytes, block_size: int) -> bytes:
    ...

def _aes128_ecb_encrypt(plaintext: bytes, key: bytes) -> bytes:
    ...

def _aes128_ecb_decrypt(ciphertext: bytes, key: bytes) -> bytes:
    ...

def _aes_padded_size(size: int) -> int:
    ...

def _random_wechat_uin() -> str:
    ...

def _base_info() -> Dict[str, Any]:
    ...

def _headers(token: Optional[str], body: str) -> Dict[str, str]:
    ...

def _account_dir(hermes_home: str) -> Path:
    ...

def _account_file(hermes_home: str, account_id: str) -> Path:
    ...

def save_weixin_account(hermes_home: str) -> None:
    ...

def load_weixin_account(hermes_home: str, account_id: str) -> Optional[Dict[str, Any]]:
    ...

class ContextTokenStore:
    def __init__(self: Self, hermes_home: str) -> None: ...
    def _path(self: Self, account_id: str) -> Path: ...
    def _key(self: Self, account_id: str, user_id: str) -> str: ...
    def restore(self: Self, account_id: str) -> None: ...
    def get(self: Self, account_id: str, user_id: str) -> Optional[str]: ...
    def set(self: Self, account_id: str, user_id: str, token: str) -> None: ...
    def _persist(self: Self, account_id: str) -> None: ...

class TypingTicketCache:
    def __init__(self: Self, ttl_seconds: float) -> None: ...
    def get(self: Self, user_id: str) -> Optional[str]: ...
    def set(self: Self, user_id: str, ticket: str) -> None: ...

def _cdn_download_url(cdn_base_url: str, encrypted_query_param: str) -> str:
    ...

def _cdn_upload_url(cdn_base_url: str, upload_param: str, filekey: str) -> str:
    ...

def _parse_aes_key(aes_key_b64: str) -> bytes:
    ...

def _guess_chat_type(message: Dict[str, Any], account_id: str) -> Tuple[str, str]:
    ...

url = f"{base_url.rstrip('/')}/{endpoint}"
raw = await response.text()
url = f"{base_url.rstrip('/')}/{endpoint}"
headers = {'iLink-App-Id': ILINK_APP_ID, 'iLink-App-ClientVersion': str(ILINK_APP_CLIENT_VERSION)}
raw = await response.text()
message: Dict[str, Any] = {'from_user_id': '', 'to_user_id': to, 'client_id': client_id, 'message_type': MSG_TYPE_BOT, 'message_state': MSG_STATE_FINISH, 'item_list': [{'type': ITEM_TEXT, 'text_item': {'text': text}}]}
message: context_token
payload: Dict[str, Any] = {'ilink_user_id': user_id}
payload: context_token
raw = await response.text()
raw = await response.text()
def _media_reference(item: Dict[str, Any], key: str) -> Dict[str, Any]:
    ...

raw = await _download_bytes(session, url=_cdn_download_url(cdn_base_url, encrypted_query_param), timeout_seconds=timeout_seconds)
raw = await _download_bytes(session, url=full_url, timeout_seconds=timeout_seconds)
def _mime_from_filename(filename: str) -> str:
    ...

def _split_table_row(line: str) -> List[str]:
    ...

def _rewrite_headers_for_weixin(line: str) -> str:
    ...

def _rewrite_table_block_for_weixin(lines: List[str]) -> str:
    ...

def _normalize_markdown_blocks(content: str) -> str:
    ...

def _split_markdown_blocks(content: str) -> List[str]:
    ...

def _split_delivery_units_for_weixin(content: str) -> List[str]:
    ...

def _looks_like_chatty_line_for_weixin(line: str) -> bool:
    ...

def _looks_like_heading_line_for_weixin(line: str) -> bool:
    ...

def _should_split_short_chat_block_for_weixin(block: str) -> bool:
    ...

def _pack_markdown_blocks_for_weixin(content: str, max_length: int) -> List[str]:
    ...

def _split_text_for_weixin_delivery(content: str, max_length: int, split_per_line: bool) -> List[str]:
    ...

def _coerce_bool(value: Any, default: bool) -> bool:
    ...

def _extract_text(item_list: List[Dict[str, Any]]) -> str:
    ...

def _message_type_from_media(media_types: List[str], text: str) -> MessageType:
    ...

def _sync_buf_path(hermes_home: str, account_id: str) -> Path:
    ...

def _load_sync_buf(hermes_home: str, account_id: str) -> str:
    ...

def _save_sync_buf(hermes_home: str, account_id: str, sync_buf: str) -> None:
    ...

qr_resp = await _api_get(session, base_url=ILINK_BASE_URL, endpoint=f'{EP_GET_BOT_QR}?bot_type={bot_type}', timeout_ms=QR_TIMEOUT_MS)
deadline = time.time() + timeout_seconds
current_base_url = ILINK_BASE_URL
refresh_count = 0
status_resp = await _api_get(session, base_url=current_base_url, endpoint=f'{EP_GET_QR_STATUS}?qrcode={qrcode_value}', timeout_ms=QR_TIMEOUT_MS)
current_base_url = f'https://{redirect_host}'
qr_resp = await _api_get(session, base_url=ILINK_BASE_URL, endpoint=f'{EP_GET_BOT_QR}?bot_type={bot_type}', timeout_ms=QR_TIMEOUT_MS)
class WeixinAdapter(BasePlatformAdapter):
    def __init__(self: Self, config: PlatformConfig) -> None: ...
    @staticmethod
    def _coerce_list(value: Any) -> List[str]: ...
    def _is_dm_allowed(self: Self, sender_id: str) -> bool: ...
    def _split_text(self: Self, content: str) -> List[str]: ...
    def _outbound_media_builder(self: Self, path: str) -> Any: ...
    def format_message(self: Self, content: Optional[str]) -> str: ...

last_result: Optional[SendResult] = None
last_result = await adapter.send(chat_id, cleaned)
last_result = await adapter.send_image_file(chat_id, media_path)
last_result = await adapter.send_document(chat_id, media_path)

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import asyncio
import base64
import hashlib
import json
import logging
import mimetypes
import os
import re
import secrets
import struct
import tempfile
import time
import uuid
import datetime
import pathlib
import typing
import urllib
import urllib.parse
import aiohttp
import cryptography
import cryptography.hazmat
import cryptography.hazmat.backends
import cryptography.hazmat.backends.default_backend
import cryptography.hazmat.primitives
import cryptography.hazmat.primitives.ciphers
import cryptography.hazmat.primitives.ciphers.Cipher
import cryptography.hazmat.primitives.ciphers.algorithms
import cryptography.hazmat.primitives.ciphers.modes
import gateway
import gateway.config
import gateway.platforms
import gateway.platforms.helpers
import gateway.platforms.base
import hermes_constants
import utils
import qrcode
import posixpath
import tools
import tools.url_safety