# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from gateway.config import Platform, PlatformConfig
from gateway.platforms.base import BasePlatformAdapter, MessageEvent, MessageType, SUPPORTED_DOCUMENT_TYPES, SendResult, cache_audio_from_url, cache_image_from_url
from hermes_constants import get_hermes_dir
from pathlib import Path
from typing import Any, Dict, Optional
from typing_extensions import Self
import asyncio
import json
import logging
import os
import platform
import re
import subprocess
import sys

_IS_WINDOWS = platform.system() == 'Windows'
def _kill_port_process(port: int) -> None:
    ...

def check_whatsapp_requirements() -> bool:
    ...

class WhatsAppAdapter(BasePlatformAdapter):
    def __init__(self: Self, config: PlatformConfig) -> None: ...
    def _whatsapp_require_mention(self: Self) -> bool: ...
    def _whatsapp_free_response_chats(self: Self) -> set[str]: ...
    def _compile_mention_patterns(self: Self) -> Any: ...
    @staticmethod
    def _normalize_whatsapp_id(value: Optional[str]) -> str: ...
    def _bot_ids_from_message(self: Self, data: Dict[str, Any]) -> set[str]: ...
    def _message_is_reply_to_bot(self: Self, data: Dict[str, Any]) -> bool: ...
    def _message_mentions_bot(self: Self, data: Dict[str, Any]) -> bool: ...
    def _message_matches_mention_patterns(self: Self, data: Dict[str, Any]) -> bool: ...
    def _clean_bot_mention_text(self: Self, text: str, data: Dict[str, Any]) -> str: ...
    def _should_process_message(self: Self, data: Dict[str, Any]) -> bool: ...
    def _close_bridge_log(self: Self) -> None: ...
    def format_message(self: Self, content: str) -> str: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import json
import logging
import os
import platform
import re
import subprocess
import pathlib
import typing
import hermes_constants
import sys
import gateway
import gateway.config
import gateway.platforms
import gateway.platforms.base
import aiohttp
import signal
import posixpath