# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from model_tools import TOOL_TO_TOOLSET_MAP
from multiprocessing import Lock, Pool
from pathlib import Path
from rich.console import Console
from rich.progress import BarColumn, MofNCompleteColumn, Progress, SpinnerColumn, TextColumn, TimeRemainingColumn
from run_agent import AIAgent
from toolset_distributions import list_distributions, sample_toolsets_from_distribution, validate_distribution
from typing import Any, Dict, List, Optional, Tuple
from typing_extensions import Self
import fire
import json
import logging
import os
import time
import traceback

_WORKER_CONFIG = {}
DEFAULT_TOOL_STATS = {'count': 0, 'success': 0, 'failure': 0}
def _normalize_tool_stats(tool_stats: Dict[str, Dict[str, int]]) -> Dict[str, Dict[str, int]]:
    ...

def _normalize_tool_error_counts(tool_error_counts: Dict[str, int]) -> Dict[str, int]:
    ...

def _extract_tool_stats(messages: List[Dict[str, Any]]) -> Dict[str, Dict[str, int]]:
    ...

def _extract_reasoning_stats(messages: List[Dict[str, Any]]) -> Dict[str, int]:
    ...

def _process_single_prompt(prompt_index: int, prompt_data: Dict[str, Any], batch_num: int, config: Dict[str, Any]) -> Dict[str, Any]:
    ...

def _process_batch_worker(args: Tuple) -> Dict[str, Any]:
    ...

class BatchRunner:
    def __init__(self: Self, dataset_file: str, batch_size: int, run_name: str, distribution: str, max_iterations: int, base_url: str, api_key: str, model: str, num_workers: int, verbose: bool, ephemeral_system_prompt: str, log_prefix_chars: int, providers_allowed: List[str], providers_ignored: List[str], providers_order: List[str], provider_sort: str, max_tokens: int, reasoning_config: Dict[str, Any], prefill_messages: List[Dict[str, Any]], max_samples: int) -> None: ...
    def _load_dataset(self: Self) -> List[Dict[str, Any]]: ...
    def _create_batches(self: Self) -> List[List[Tuple[int, Dict[str, Any]]]]: ...
    def _load_checkpoint(self: Self) -> Dict[str, Any]: ...
    def _save_checkpoint(self: Self, checkpoint_data: Dict[str, Any], lock: Optional[Lock]) -> Any: ...
    def _scan_completed_prompts_by_content(self: Self) -> set: ...
    def _filter_dataset_by_completed(self: Self, completed_prompts: set) -> Tuple[List[Dict], List[int]]: ...
    def run(self: Self, resume: bool) -> Any: ...

def main(dataset_file: str, batch_size: int, run_name: str, distribution: str, model: str, api_key: str, base_url: str, max_turns: int, num_workers: int, resume: bool, verbose: bool, list_distributions: bool, ephemeral_system_prompt: str, log_prefix_chars: int, providers_allowed: str, providers_ignored: str, providers_order: str, provider_sort: str, max_tokens: int, reasoning_effort: str, reasoning_disabled: bool, prefill_messages_file: str, max_samples: int) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import logging
import os
import time
import pathlib
import typing
import datetime
import multiprocessing
import multiprocessing.Pool
import multiprocessing.Lock
import traceback
import rich
import rich.progress
import rich.console
import fire
import run_agent
import toolset_distributions
import model_tools
import subprocess
import tools
import tools.terminal_tool
import utils