# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
import os

def get_hermes_home() -> Path:
    ...

def get_default_hermes_root() -> Path:
    ...

def get_optional_skills_dir(default: Path | None) -> Path:
    ...

def get_hermes_dir(new_subpath: str, old_name: str) -> Path:
    ...

def display_hermes_home() -> str:
    ...

def get_subprocess_home() -> str | None:
    ...

VALID_REASONING_EFFORTS = ('minimal', 'low', 'medium', 'high', 'xhigh')
def parse_reasoning_effort(effort: str) -> dict | None:
    ...

def is_termux() -> bool:
    ...

_wsl_detected: bool | None = None
def is_wsl() -> bool:
    ...

_container_detected: bool | None = None
def is_container() -> bool:
    ...

def get_config_path() -> Path:
    ...

def get_skills_dir() -> Path:
    ...

def get_logs_dir() -> Path:
    ...

def get_env_path() -> Path:
    ...

def apply_ipv4_preference(force: bool) -> None:
    ...

OPENROUTER_BASE_URL = 'https://openrouter.ai/api/v1'
OPENROUTER_MODELS_URL = f'{OPENROUTER_BASE_URL}/models'
AI_GATEWAY_BASE_URL = 'https://ai-gateway.vercel.sh/v1'
NOUS_API_BASE_URL = 'https://inference-api.nousresearch.com/v1'

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import pathlib
import posixpath
import socket