# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_constants import get_config_path, get_hermes_home
from logging.handlers import RotatingFileHandler
from pathlib import Path
from typing import Any, Optional, Sequence
from typing_extensions import Self
import logging
import os
import threading

_logging_initialized = False
_LOG_FORMAT = '%(asctime)s %(levelname)s%(session_tag)s %(name)s: %(message)s'
_LOG_FORMAT_VERBOSE = '%(asctime)s - %(name)s - %(levelname)s%(session_tag)s - %(message)s'
_NOISY_LOGGERS = ('openai', 'openai._base_client', 'httpx', 'httpcore', 'asyncio', 'hpack', 'hpack.hpack', 'grpc', 'modal', 'urllib3', 'urllib3.connectionpool', 'websockets', 'charset_normalizer', 'markdown_it')
def set_session_context(session_id: str) -> None:
    ...

def clear_session_context() -> None:
    ...

def _install_session_record_factory() -> None:
    ...

class _ComponentFilter:
    def __init__(self: Self, prefixes: Sequence[str]) -> None: ...
    def filter(self: Self, record: logging.LogRecord) -> bool: ...

COMPONENT_PREFIXES = {'gateway': ('gateway',), 'agent': ('agent', 'run_agent', 'model_tools', 'batch_runner'), 'tools': ('tools',), 'cli': ('hermes_cli', 'cli'), 'cron': ('cron',)}
def setup_logging() -> Path:
    ...

def setup_verbose_logging() -> None:
    ...

class _ManagedRotatingFileHandler(RotatingFileHandler):
    def __init__(self: Self) -> None: ...
    def _chmod_if_managed(self: Self) -> Any: ...
    def _open(self: Self) -> Any: ...
    def doRollover(self: Self) -> Any: ...

def _add_rotating_handler(logger: logging.Logger, path: Path) -> None:
    ...

def _read_logging_config() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import os
import threading
import logging.handlers
import pathlib
import typing
import hermes_constants
import agent
import agent.redact
import hermes_cli
import hermes_cli.config
import yaml