# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from dataclasses import dataclass, field
from mcp.server.fastmcp import FastMCP
from pathlib import Path
from typing import Any, Dict, List, Optional
from typing_extensions import Self
from dataclasses import dataclass
import json
import logging
import os
import re
import sys
import threading
import time

_MCP_SERVER_AVAILABLE = False
_MCP_SERVER_AVAILABLE = True
FastMCP = None
def _get_sessions_dir() -> Path:
    ...

def _get_session_db() -> Any:
    ...

def _load_sessions_index() -> dict:
    ...

def _load_channel_directory() -> dict:
    ...

def _extract_message_content(msg: dict) -> str:
    ...

def _extract_attachments(msg: dict) -> List[dict]:
    ...

QUEUE_LIMIT = 1000
POLL_INTERVAL = 0.2
@dataclass
class QueueEvent:
class EventBridge:
    def __init__(self: Self) -> None: ...
    def start(self: Self) -> Any: ...
    def stop(self: Self) -> Any: ...
    def poll_events(self: Self, after_cursor: int, session_key: Optional[str], limit: int) -> dict: ...
    def wait_for_event(self: Self, after_cursor: int, session_key: Optional[str], timeout_ms: int) -> Optional[dict]: ...
    def list_pending_approvals(self: Self) -> List[dict]: ...
    def respond_to_approval(self: Self, approval_id: str, decision: str) -> dict: ...
    def _enqueue(self: Self, event: QueueEvent) -> None: ...
    def _poll_loop(self: Self) -> Any: ...
    def _poll_once(self: Self, db: Any) -> Any: ...

def create_mcp_server(event_bridge: Optional[EventBridge]) -> 'FastMCP':
    ...

def run_mcp_server(verbose: bool) -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import json
import logging
import os
import re
import sys
import threading
import time
import dataclasses
import pathlib
import typing
import mcp
import mcp.server
import mcp.server.fastmcp
import mcp.server.fastmcp.FastMCP
import hermes_constants
import hermes_state
import datetime
import tools
import tools.send_message_tool
import asyncio