# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from dotenv import load_dotenv
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional
from typing_extensions import Self
import fire
import json
import logging
import os
import sys
import time
import uuid

TERMINAL_TOOL_DEFINITION = {'type': 'function', 'function': {'name': 'terminal', 'description': 'Execute bash commands in a sandboxed environment.\n\n**Environment:**\n- Isolated execution environment (local, Docker, or Modal cloud)\n- Filesystem persists between tool calls within the same task\n- Internet access available\n\n**Command Execution:**\n- Provide the command to execute via the \'command\' parameter\n- Optional \'timeout\' parameter in seconds (default: 60)\n\n**Examples:**\n- Run command: `{"command": "ls -la"}`\n- With timeout: `{"command": "long_task.sh", "timeout": 300}`\n\n**Best Practices:**\n- Use non-interactive commands (avoid vim, nano, interactive python)\n- Pipe to cat if output might be large\n- Install tools with apt-get or pip as needed\n\n**Completion:**\n- When task is complete, output: echo "MINI_SWE_AGENT_FINAL_OUTPUT" followed by your result\n', 'parameters': {'type': 'object', 'properties': {'command': {'type': 'string', 'description': 'The bash command to execute'}, 'timeout': {'type': 'integer', 'description': 'Command timeout in seconds (default: 60)'}}, 'required': ['command']}}}
def create_environment(env_type: str, image: str, cwd: str, timeout: int) -> Any:
    ...

class MiniSWERunner:
    def __init__(self: Self, model: str, base_url: str, api_key: str, env_type: str, image: str, cwd: str, max_iterations: int, command_timeout: int, verbose: bool) -> None: ...
    def _create_env(self: Self) -> Any: ...
    def _cleanup_env(self: Self) -> Any: ...
    def _execute_command(self: Self, command: str, timeout: int) -> Dict[str, Any]: ...
    def _format_tools_for_system_message(self: Self) -> str: ...
    def _convert_to_hermes_format(self: Self, messages: List[Dict[str, Any]], user_query: str, completed: bool) -> List[Dict[str, Any]]: ...
    def run_task(self: Self, task: str) -> Dict[str, Any]: ...
    def run_batch(self: Self, prompts: List[str], output_file: str) -> List[Dict[str, Any]]: ...

def main(task: str, prompts_file: str, output_file: str, model: str, base_url: str, api_key: str, env: str, image: str, cwd: str, max_iterations: int, timeout: int, verbose: bool) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import logging
import os
import sys
import time
import uuid
import datetime
import pathlib
import typing
import fire
import dotenv
import dotenv.load_dotenv
import tools
import tools.environments
import tools.environments.local
import tools.environments.docker
import tools.environments.modal
import openai
import openai.OpenAI
import agent
import agent.auxiliary_client