# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_cli.plugins import discover_plugins
from tools.mcp_tool import discover_mcp_tools
from tools.registry import registry
from toolsets import resolve_toolset, validate_toolset
from typing import Any, Dict, List, Optional, Tuple
import asyncio
import json
import logging
import threading

_tool_loop = None
def _get_tool_loop() -> Any:
    ...

def _get_worker_loop() -> Any:
    ...

def _run_async(coro: Any) -> Any:
    ...

def _discover_tools() -> Any:
    ...

TOOL_TO_TOOLSET_MAP: Dict[str, str] = registry.get_tool_to_toolset_map()
TOOLSET_REQUIREMENTS: Dict[str, dict] = registry.get_toolset_requirements()
_last_resolved_tool_names: List[str] = []
_LEGACY_TOOLSET_MAP = {'web_tools': ['web_search', 'web_extract'], 'terminal_tools': ['terminal'], 'vision_tools': ['vision_analyze'], 'moa_tools': ['mixture_of_agents'], 'image_tools': ['image_generate'], 'skills_tools': ['skills_list', 'skill_view', 'skill_manage'], 'browser_tools': ['browser_navigate', 'browser_snapshot', 'browser_click', 'browser_type', 'browser_scroll', 'browser_back', 'browser_press', 'browser_get_images', 'browser_vision', 'browser_console'], 'cronjob_tools': ['cronjob'], 'rl_tools': ['rl_list_environments', 'rl_select_environment', 'rl_get_current_config', 'rl_edit_config', 'rl_start_training', 'rl_check_status', 'rl_stop_training', 'rl_get_results', 'rl_list_runs', 'rl_test_inference'], 'file_tools': ['read_file', 'write_file', 'patch', 'search_files'], 'tts_tools': ['text_to_speech']}
def get_tool_definitions(enabled_toolsets: List[str], disabled_toolsets: List[str], quiet_mode: bool) -> List[Dict[str, Any]]:
    ...

_AGENT_LOOP_TOOLS = {'todo', 'memory', 'session_search', 'delegate_task'}
_READ_SEARCH_TOOLS = {'read_file', 'search_files'}
def coerce_tool_args(tool_name: str, args: Dict[str, Any]) -> Dict[str, Any]:
    ...

def _coerce_value(value: str, expected_type: Any) -> Any:
    ...

def _coerce_number(value: str, integer_only: bool) -> Any:
    ...

def _coerce_boolean(value: str) -> Any:
    ...

def handle_function_call(function_name: str, function_args: Dict[str, Any], task_id: Optional[str], tool_call_id: Optional[str], session_id: Optional[str], user_task: Optional[str], enabled_tools: Optional[List[str]]) -> str:
    ...

def get_all_tool_names() -> List[str]:
    ...

def get_toolset_for_tool(tool_name: str) -> Optional[str]:
    ...

def get_available_toolsets() -> Dict[str, dict]:
    ...

def check_toolset_requirements() -> Dict[str, bool]:
    ...

def check_tool_availability(quiet: bool) -> Tuple[List[str], List[dict]]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import asyncio
import logging
import threading
import typing
import tools
import tools.registry
import toolsets
import concurrent
import concurrent.futures
import importlib
import tools.mcp_tool
import hermes_cli
import hermes_cli.plugins
import tools.code_execution_tool
import tools.file_tools