# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from typing import Any, List, Optional, Union
import json
import logging
import os
import tempfile
import yaml

TRUTHY_STRINGS = frozenset({'1', 'true', 'yes', 'on'})
def is_truthy_value(value: Any, default: bool) -> bool:
    ...

def env_var_enabled(name: str, default: str) -> bool:
    ...

def atomic_json_write(path: Union[str, Path], data: Any) -> None:
    ...

def atomic_yaml_write(path: Union[str, Path], data: Any) -> None:
    ...

def safe_json_loads(text: str, default: Any) -> Any:
    ...

def read_json_file(path: Path, default: Any) -> Any:
    ...

def read_jsonl(path: Path) -> List[dict]:
    ...

def append_jsonl(path: Path, entry: dict) -> None:
    ...

def env_str(key: str, default: str) -> str:
    ...

def env_lower(key: str, default: str) -> str:
    ...

def env_int(key: str, default: int) -> int:
    ...

def env_bool(key: str, default: bool) -> bool:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import logging
import os
import tempfile
import pathlib
import typing
import yaml