# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_constants import get_hermes_home
from pathlib import Path
from types import SimpleNamespace
from typing import Any, Dict, List, Optional, Tuple
import anthropic
import copy
import json
import logging
import os

_anthropic_sdk = None
THINKING_BUDGET = {'xhigh': 32000, 'high': 16000, 'medium': 8000, 'low': 4000}
ADAPTIVE_EFFORT_MAP = {'xhigh': 'max', 'high': 'high', 'medium': 'medium', 'low': 'low', 'minimal': 'low'}
_ANTHROPIC_OUTPUT_LIMITS = {'claude-opus-4-6': 128000, 'claude-sonnet-4-6': 64000, 'claude-opus-4-5': 64000, 'claude-sonnet-4-5': 64000, 'claude-haiku-4-5': 64000, 'claude-opus-4': 32000, 'claude-sonnet-4': 64000, 'claude-3-7-sonnet': 128000, 'claude-3-5-sonnet': 8192, 'claude-3-5-haiku': 8192, 'claude-3-opus': 4096, 'claude-3-sonnet': 4096, 'claude-3-haiku': 4096, 'minimax': 131072}
_ANTHROPIC_DEFAULT_OUTPUT_LIMIT = 128000
def _get_anthropic_max_output(model: str) -> int:
    ...

def _supports_adaptive_thinking(model: str) -> bool:
    ...

_COMMON_BETAS = ['interleaved-thinking-2025-05-14', 'fine-grained-tool-streaming-2025-05-14']
_TOOL_STREAMING_BETA = 'fine-grained-tool-streaming-2025-05-14'
_FAST_MODE_BETA = 'fast-mode-2026-02-01'
_OAUTH_ONLY_BETAS = ['claude-code-20250219', 'oauth-2025-04-20']
_CLAUDE_CODE_VERSION_FALLBACK = '2.1.74'
_claude_code_version_cache: Optional[str] = None
def _detect_claude_code_version() -> str:
    ...

_CLAUDE_CODE_SYSTEM_PREFIX = "You are Claude Code, Anthropic's official CLI for Claude."
_MCP_TOOL_PREFIX = 'mcp_'
def _get_claude_code_version() -> str:
    ...

def _is_oauth_token(key: str) -> bool:
    ...

def _normalize_base_url_text(base_url: Any) -> str:
    ...

def _is_third_party_anthropic_endpoint(base_url: str | None) -> bool:
    ...

def _requires_bearer_auth(base_url: str | None) -> bool:
    ...

def _common_betas_for_base_url(base_url: str | None) -> list[str]:
    ...

def build_anthropic_client(api_key: str, base_url: str) -> Any:
    ...

def read_claude_code_credentials() -> Optional[Dict[str, Any]]:
    ...

def read_claude_managed_key() -> Optional[str]:
    ...

def is_claude_code_token_valid(creds: Dict[str, Any]) -> bool:
    ...

def refresh_anthropic_oauth_pure(refresh_token: str) -> Dict[str, Any]:
    ...

def _refresh_oauth_token(creds: Dict[str, Any]) -> Optional[str]:
    ...

def _write_claude_code_credentials(access_token: str, refresh_token: str, expires_at_ms: int) -> None:
    ...

def _resolve_claude_code_token_from_credentials(creds: Optional[Dict[str, Any]]) -> Optional[str]:
    ...

def _prefer_refreshable_claude_code_token(env_token: str, creds: Optional[Dict[str, Any]]) -> Optional[str]:
    ...

def resolve_anthropic_token() -> Optional[str]:
    ...

def run_oauth_setup_token() -> Optional[str]:
    ...

_OAUTH_CLIENT_ID = '9d1c250a-e61b-44d9-88ed-5944d1962f5e'
_OAUTH_TOKEN_URL = 'https://console.anthropic.com/v1/oauth/token'
_OAUTH_REDIRECT_URI = 'https://console.anthropic.com/oauth/code/callback'
_OAUTH_SCOPES = 'org:create_api_key user:profile user:inference'
_HERMES_OAUTH_FILE = get_hermes_home() / '.anthropic_oauth.json'
def _generate_pkce() -> tuple:
    ...

def run_hermes_oauth_login_pure() -> Optional[Dict[str, Any]]:
    ...

def read_hermes_oauth_credentials() -> Optional[Dict[str, Any]]:
    ...

def normalize_model_name(model: str, preserve_dots: bool) -> str:
    ...

def _sanitize_tool_id(tool_id: str) -> str:
    ...

def convert_tools_to_anthropic(tools: List[Dict]) -> List[Dict]:
    ...

def _image_source_from_openai_url(url: str) -> Dict[str, str]:
    ...

def _convert_content_part_to_anthropic(part: Any) -> Optional[Dict[str, Any]]:
    ...

def _to_plain_data(value: Any) -> Any:
    ...

def _extract_preserved_thinking_blocks(message: Dict[str, Any]) -> List[Dict[str, Any]]:
    ...

def _convert_content_to_anthropic(content: Any) -> Any:
    ...

def convert_messages_to_anthropic(messages: List[Dict], base_url: str | None) -> Tuple[Optional[Any], List[Dict]]:
    ...

def build_anthropic_kwargs(model: str, messages: List[Dict], tools: Optional[List[Dict]], max_tokens: Optional[int], reasoning_config: Optional[Dict[str, Any]], tool_choice: Optional[str], is_oauth: bool, preserve_dots: bool, context_length: Optional[int], base_url: str | None, fast_mode: bool) -> Dict[str, Any]:
    ...

def normalize_anthropic_response(response: Any, strip_tool_prefix: bool) -> Tuple[SimpleNamespace, str]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import copy
import json
import logging
import os
import pathlib
import hermes_constants
import types
import typing
import anthropic
import subprocess
import httpx
import httpx.Timeout
import time
import urllib
import urllib.parse
import urllib.request
import shutil
import base64
import hashlib
import secrets
import webbrowser
import re