# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from agent.credential_pool import load_pool
from hermes_cli.config import get_hermes_home
from hermes_constants import OPENROUTER_BASE_URL
from openai import OpenAI
from pathlib import Path
from types import SimpleNamespace
from typing import Any, Dict, List, Optional, Tuple
from typing_extensions import Self
import json
import logging
import os
import threading
import time

_stale_base_url_warned = False
_PROVIDER_ALIASES = {'google': 'gemini', 'google-gemini': 'gemini', 'google-ai-studio': 'gemini', 'glm': 'zai', 'z-ai': 'zai', 'z.ai': 'zai', 'zhipu': 'zai', 'kimi': 'kimi-coding', 'moonshot': 'kimi-coding', 'minimax-china': 'minimax-cn', 'minimax_cn': 'minimax-cn', 'claude': 'anthropic', 'claude-code': 'anthropic'}
def _normalize_aux_provider(provider: Optional[str]) -> str:
    ...

_API_KEY_PROVIDER_AUX_MODELS: Dict[str, str] = {'gemini': 'gemini-3-flash-preview', 'zai': 'glm-4.5-flash', 'kimi-coding': 'kimi-k2-turbo-preview', 'minimax': 'MiniMax-M2.7', 'minimax-cn': 'MiniMax-M2.7', 'anthropic': 'claude-haiku-4-5-20251001', 'ai-gateway': 'google/gemini-3-flash', 'opencode-zen': 'gemini-3-flash', 'opencode-go': 'glm-5', 'kilocode': 'google/gemini-3-flash-preview'}
_PROVIDER_VISION_MODELS: Dict[str, str] = {'xiaomi': 'mimo-v2-omni'}
_OR_HEADERS = {'HTTP-Referer': 'https://hermes-agent.nousresearch.com', 'X-OpenRouter-Title': 'Hermes Agent', 'X-OpenRouter-Categories': 'productivity,cli-agent'}
NOUS_EXTRA_BODY = {'tags': ['product=hermes-agent']}
auxiliary_is_nous: bool = False
_OPENROUTER_MODEL = 'google/gemini-3-flash-preview'
_NOUS_MODEL = 'google/gemini-3-flash-preview'
_NOUS_FREE_TIER_VISION_MODEL = 'xiaomi/mimo-v2-omni'
_NOUS_FREE_TIER_AUX_MODEL = 'xiaomi/mimo-v2-pro'
_NOUS_DEFAULT_BASE_URL = 'https://inference-api.nousresearch.com/v1'
_ANTHROPIC_DEFAULT_BASE_URL = 'https://api.anthropic.com'
_AUTH_JSON_PATH = get_hermes_home() / 'auth.json'
_CODEX_AUX_MODEL = 'gpt-5.2-codex'
_CODEX_AUX_BASE_URL = 'https://chatgpt.com/backend-api/codex'
def _to_openai_base_url(base_url: str) -> str:
    ...

def _select_pool_entry(provider: str) -> Tuple[bool, Optional[Any]]:
    ...

def _pool_runtime_api_key(entry: Any) -> str:
    ...

def _pool_runtime_base_url(entry: Any, fallback: str) -> str:
    ...

def _convert_content_for_responses(content: Any) -> Any:
    ...

class _CodexCompletionsAdapter:
    def __init__(self: Self, real_client: OpenAI, model: str) -> None: ...
    def create(self: Self) -> Any: ...

class _CodexChatShim:
    def __init__(self: Self, adapter: _CodexCompletionsAdapter) -> None: ...

class CodexAuxiliaryClient:
    def __init__(self: Self, real_client: OpenAI, model: str) -> None: ...
    def close(self: Self) -> Any: ...

class _AsyncCodexCompletionsAdapter:
    def __init__(self: Self, sync_adapter: _CodexCompletionsAdapter) -> None: ...

class _AsyncCodexChatShim:
    def __init__(self: Self, adapter: _AsyncCodexCompletionsAdapter) -> None: ...

class AsyncCodexAuxiliaryClient:
    def __init__(self: Self, sync_wrapper: 'CodexAuxiliaryClient') -> None: ...

class _AnthropicCompletionsAdapter:
    def __init__(self: Self, real_client: Any, model: str, is_oauth: bool) -> None: ...
    def create(self: Self) -> Any: ...

class _AnthropicChatShim:
    def __init__(self: Self, adapter: _AnthropicCompletionsAdapter) -> None: ...

class AnthropicAuxiliaryClient:
    def __init__(self: Self, real_client: Any, model: str, api_key: str, base_url: str, is_oauth: bool) -> None: ...
    def close(self: Self) -> Any: ...

class _AsyncAnthropicCompletionsAdapter:
    def __init__(self: Self, sync_adapter: _AnthropicCompletionsAdapter) -> None: ...

class _AsyncAnthropicChatShim:
    def __init__(self: Self, adapter: _AsyncAnthropicCompletionsAdapter) -> None: ...

class AsyncAnthropicAuxiliaryClient:
    def __init__(self: Self, sync_wrapper: 'AnthropicAuxiliaryClient') -> None: ...

def _read_nous_auth() -> Optional[dict]:
    ...

def _nous_api_key(provider: dict) -> str:
    ...

def _nous_base_url() -> str:
    ...

def _read_codex_access_token() -> Optional[str]:
    ...

def _resolve_api_key_provider() -> Tuple[Optional[OpenAI], Optional[str]]:
    ...

def _get_auxiliary_provider(task: str) -> str:
    ...

def _get_auxiliary_env_override(task: str, suffix: str) -> Optional[str]:
    ...

def _try_openrouter() -> Tuple[Optional[OpenAI], Optional[str]]:
    ...

def _try_nous(vision: bool) -> Tuple[Optional[OpenAI], Optional[str]]:
    ...

def _read_main_model() -> str:
    ...

def _read_main_provider() -> str:
    ...

def _resolve_custom_runtime() -> Tuple[Optional[str], Optional[str], Optional[str]]:
    ...

def _current_custom_base_url() -> str:
    ...

def _try_custom_endpoint() -> Tuple[Optional[OpenAI], Optional[str]]:
    ...

def _try_codex() -> Tuple[Optional[Any], Optional[str]]:
    ...

def _try_anthropic() -> Tuple[Optional[Any], Optional[str]]:
    ...

_AUTO_PROVIDER_LABELS = {'_try_openrouter': 'openrouter', '_try_nous': 'nous', '_try_custom_endpoint': 'local/custom', '_try_codex': 'openai-codex', '_resolve_api_key_provider': 'api-key'}
_AGGREGATOR_PROVIDERS = frozenset({'openrouter', 'nous'})
_MAIN_RUNTIME_FIELDS = ('provider', 'model', 'base_url', 'api_key', 'api_mode')
def _normalize_main_runtime(main_runtime: Optional[Dict[str, Any]]) -> Dict[str, str]:
    ...

def _get_provider_chain() -> List[tuple]:
    ...

def _is_payment_error(exc: Exception) -> bool:
    ...

def _is_connection_error(exc: Exception) -> bool:
    ...

def _try_payment_fallback(failed_provider: str, task: str, reason: str) -> Tuple[Optional[Any], Optional[str], str]:
    ...

def _resolve_auto(main_runtime: Optional[Dict[str, Any]]) -> Tuple[Optional[OpenAI], Optional[str]]:
    ...

def _to_async_client(sync_client: Any, model: str) -> Any:
    ...

def _normalize_resolved_model(model_name: Optional[str], provider: str) -> Optional[str]:
    ...

def resolve_provider_client(provider: str, model: str, async_mode: bool, raw_codex: bool, explicit_base_url: str, explicit_api_key: str, api_mode: str, main_runtime: Optional[Dict[str, Any]]) -> Tuple[Optional[Any], Optional[str]]:
    ...

def get_text_auxiliary_client(task: str) -> Tuple[Optional[OpenAI], Optional[str]]:
    ...

def get_async_text_auxiliary_client(task: str) -> Any:
    ...

_VISION_AUTO_PROVIDER_ORDER = ('openrouter', 'nous')
def _normalize_vision_provider(provider: Optional[str]) -> str:
    ...

def _resolve_strict_vision_backend(provider: str) -> Tuple[Optional[Any], Optional[str]]:
    ...

def _strict_vision_backend_available(provider: str) -> bool:
    ...

def get_available_vision_backends() -> List[str]:
    ...

def resolve_vision_provider_client(provider: Optional[str], model: Optional[str]) -> Tuple[Optional[str], Optional[Any], Optional[str]]:
    ...

def get_auxiliary_extra_body() -> dict:
    ...

def auxiliary_max_tokens_param(value: int) -> dict:
    ...

_client_cache: Dict[tuple, tuple] = {}
def neuter_async_httpx_del() -> None:
    ...

def _force_close_async_httpx(client: Any) -> None:
    ...

def shutdown_cached_clients() -> None:
    ...

def cleanup_stale_async_clients() -> None:
    ...

def _is_openrouter_client(client: Any) -> bool:
    ...

def _compat_model(client: Any, model: Optional[str], cached_default: Optional[str]) -> Optional[str]:
    ...

def _get_cached_client(provider: str, model: str, async_mode: bool, base_url: str, api_key: str, api_mode: str, main_runtime: Optional[Dict[str, Any]]) -> Tuple[Optional[Any], Optional[str]]:
    ...

def _resolve_task_provider_model(task: str, provider: str, model: str, base_url: str, api_key: str) -> Tuple[str, Optional[str], Optional[str], Optional[str], Optional[str]]:
    ...

_DEFAULT_AUX_TIMEOUT = 30.0
def _get_task_timeout(task: str, default: float) -> float:
    ...

_ANTHROPIC_COMPAT_PROVIDERS = frozenset({'minimax', 'minimax-cn'})
def _is_anthropic_compat_endpoint(provider: str, base_url: str) -> bool:
    ...

def _convert_openai_images_to_anthropic(messages: list) -> list:
    ...

def _build_call_kwargs(provider: str, model: str, messages: list, temperature: Optional[float], max_tokens: Optional[int], tools: Optional[list], timeout: float, extra_body: Optional[dict], base_url: Optional[str]) -> dict:
    ...

def _validate_llm_response(response: Any, task: str) -> Any:
    ...

def call_llm(task: str) -> Any:
    ...

def extract_content_or_reasoning(response: Any) -> str:
    ...

resolved_provider = effective_provider or resolved_provider
effective_timeout = timeout if timeout is not None else _get_task_timeout(task)
kwargs: _convert_openai_images_to_anthropic(kwargs['messages'])
kwargs: max_tokens
first_err = retry_err
should_fallback = _is_payment_error(first_err) or _is_connection_error(first_err)
is_auto = resolved_provider in ('auto', '', None)
reason = 'payment error' if _is_payment_error(first_err) else 'connection error'
fb_kwargs: async_fb_model

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import logging
import os
import threading
import time
import pathlib
import types
import typing
import openai
import openai.OpenAI
import agent
import agent.credential_pool
import hermes_cli
import hermes_cli.config
import hermes_constants
import asyncio
import agent.anthropic_adapter
import hermes_cli.auth
import base64
import hermes_cli.models
import hermes_cli.runtime_provider
import openai.APIConnectionError
import openai.APITimeoutError
import openai.AsyncOpenAI
import hermes_cli.model_normalize
import openai._base_client
import httpx
import httpx._client
import inspect
import re