# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from dataclasses import dataclass, field
from difflib import unified_diff
from pathlib import Path
from typing import Any
from typing_extensions import Self
from utils import safe_json_loads
from dataclasses import dataclass
import logging
import os
import sys
import threading
import time

_RED = '\x1b[31m'
_RESET = '\x1b[0m'
_ANSI_RESET = '\x1b[0m'
_diff_colors_cached: dict[str, str] | None = None
def _diff_ansi() -> dict[str, str]:
    ...

def reset_diff_colors() -> None:
    ...

def _diff_dim() -> Any:
    ...

def _diff_file() -> Any:
    ...

def _diff_hunk() -> Any:
    ...

def _diff_minus() -> Any:
    ...

def _diff_plus() -> Any:
    ...

_MAX_INLINE_DIFF_FILES = 6
_MAX_INLINE_DIFF_LINES = 80
@dataclass
class LocalEditSnapshot:
_tool_preview_max_len: int = 0
def set_tool_preview_max_len(n: int) -> None:
    ...

def get_tool_preview_max_len() -> int:
    ...

def _get_skin() -> Any:
    ...

def get_skin_tool_prefix() -> str:
    ...

def get_tool_emoji(tool_name: str, default: str) -> str:
    ...

def _oneline(text: str) -> str:
    ...

def build_tool_preview(tool_name: str, args: dict, max_len: int | None) -> str | None:
    ...

def _resolved_path(path: str) -> Path:
    ...

def _snapshot_text(path: Path) -> str | None:
    ...

def _display_diff_path(path: Path) -> str:
    ...

def _resolve_skill_manage_paths(args: dict) -> list[Path]:
    ...

def _resolve_local_edit_paths(tool_name: str, function_args: dict | None) -> list[Path]:
    ...

def capture_local_edit_snapshot(tool_name: str, function_args: dict | None) -> LocalEditSnapshot | None:
    ...

def _result_succeeded(result: str | None) -> bool:
    ...

def _diff_from_snapshot(snapshot: LocalEditSnapshot | None) -> str | None:
    ...

def extract_edit_diff(tool_name: str, result: str | None) -> str | None:
    ...

def _emit_inline_diff(diff_text: str, print_fn: Any) -> bool:
    ...

def _render_inline_unified_diff(diff: str) -> list[str]:
    ...

def _split_unified_diff_sections(diff: str) -> list[str]:
    ...

def _summarize_rendered_diff_sections(diff: str) -> list[str]:
    ...

def render_edit_diff_with_delta(tool_name: str, result: str | None) -> bool:
    ...

class KawaiiSpinner:
    def __init__(self: Self, message: str, spinner_type: str, print_fn: Any) -> None: ...
    def _write(self: Self, text: str, end: str, flush: bool) -> Any: ...
    def _is_tty(self: Self) -> bool: ...
    def _is_patch_stdout_proxy(self: Self) -> bool: ...
    def _animate(self: Self) -> Any: ...
    def start(self: Self) -> Any: ...
    def update_text(self: Self, new_message: str) -> Any: ...
    def print_above(self: Self, text: str) -> Any: ...
    def stop(self: Self, final_message: str) -> Any: ...
    def __enter__(self: Self) -> Any: ...
    def __exit__(self: Self, exc_type: Any, exc_val: Any, exc_tb: Any) -> Any: ...

def _detect_tool_failure(tool_name: str, result: str | None) -> tuple[bool, str]:
    ...

def get_cute_tool_message(tool_name: str, args: dict, duration: float, result: str | None) -> str:
    ...

_DIM = '\x1b[2m'
_SKY_BLUE = '\x1b[38;5;117m'
_ANSI_RESET = '\x1b[0m'
_CYAN = '\x1b[36m'
_YELLOW = '\x1b[33m'
_BOLD = '\x1b[1m'
_DIM_ANSI = '\x1b[2m'
_BAR_FILLED = '▰'
_BAR_EMPTY = '▱'
_BAR_WIDTH = 20
def format_context_pressure(compaction_progress: float, threshold_tokens: int, threshold_percent: float, compression_enabled: bool) -> str:
    ...

def format_context_pressure_gateway(compaction_progress: float, threshold_percent: float, compression_enabled: bool) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import os
import sys
import threading
import time
import dataclasses
import difflib
import pathlib
import utils
import hermes_cli
import hermes_cli.skin_engine
import tools
import tools.registry
import posixpath
import tools.skill_manager_tool
import prompt_toolkit
import prompt_toolkit.patch_stdout