# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from typing import Any, Sequence

def summarize_manual_compression(before_messages: Sequence[dict[str, Any]], after_messages: Sequence[dict[str, Any]], before_tokens: int, after_tokens: int) -> dict[str, Any]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import typing