# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any, Dict, List
import copy

def _apply_cache_marker(msg: dict, cache_marker: dict, native_anthropic: bool) -> None:
    ...

def apply_anthropic_cache_control(api_messages: List[Dict[str, Any]], cache_ttl: str, native_anthropic: bool) -> List[Dict[str, Any]]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import copy
import typing