# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Dict, Mapping, Optional
from typing_extensions import Self
from dataclasses import dataclass
import time

@dataclass
class RateLimitBucket:
    def used(self: Self) -> int: ...
    def usage_pct(self: Self) -> float: ...
    def remaining_seconds_now(self: Self) -> float: ...

@dataclass
class RateLimitState:
    def has_data(self: Self) -> bool: ...
    def age_seconds(self: Self) -> float: ...

def _safe_int(value: Any, default: int) -> int:
    ...

def _safe_float(value: Any, default: float) -> float:
    ...

def parse_rate_limit_headers(headers: Mapping[str, str], provider: str) -> Optional[RateLimitState]:
    ...

def _fmt_count(n: int) -> str:
    ...

def _fmt_seconds(seconds: float) -> str:
    ...

def _bar(pct: float, width: int) -> str:
    ...

def _bucket_line(label: str, bucket: RateLimitBucket, label_width: int) -> str:
    ...

def format_rate_limit_display(state: RateLimitState) -> str:
    ...

def format_rate_limit_compact(state: RateLimitState) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import time
import dataclasses
import typing