# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
from typing_extensions import Self
import logging
import os
import re

_REDACT_ENABLED = os.getenv('HERMES_REDACT_SECRETS', '').lower() not in ('0', 'false', 'no', 'off')
_PREFIX_PATTERNS = ['sk-[A-Za-z0-9_-]{10,}', 'ghp_[A-Za-z0-9]{10,}', 'github_pat_[A-Za-z0-9_]{10,}', 'gho_[A-Za-z0-9]{10,}', 'ghu_[A-Za-z0-9]{10,}', 'ghs_[A-Za-z0-9]{10,}', 'ghr_[A-Za-z0-9]{10,}', 'xox[baprs]-[A-Za-z0-9-]{10,}', 'AIza[A-Za-z0-9_-]{30,}', 'pplx-[A-Za-z0-9]{10,}', 'fal_[A-Za-z0-9_-]{10,}', 'fc-[A-Za-z0-9]{10,}', 'bb_live_[A-Za-z0-9_-]{10,}', 'gAAAA[A-Za-z0-9_=-]{20,}', 'AKIA[A-Z0-9]{16}', 'sk_live_[A-Za-z0-9]{10,}', 'sk_test_[A-Za-z0-9]{10,}', 'rk_live_[A-Za-z0-9]{10,}', 'SG\\.[A-Za-z0-9_-]{10,}', 'hf_[A-Za-z0-9]{10,}', 'r8_[A-Za-z0-9]{10,}', 'npm_[A-Za-z0-9]{10,}', 'pypi-[A-Za-z0-9_-]{10,}', 'dop_v1_[A-Za-z0-9]{10,}', 'doo_v1_[A-Za-z0-9]{10,}', 'am_[A-Za-z0-9_-]{10,}', 'sk_[A-Za-z0-9_]{10,}', 'tvly-[A-Za-z0-9]{10,}', 'exa_[A-Za-z0-9]{10,}', 'gsk_[A-Za-z0-9]{10,}', 'syt_[A-Za-z0-9]{10,}', 'retaindb_[A-Za-z0-9]{10,}', 'hsk-[A-Za-z0-9]{10,}', 'mem0_[A-Za-z0-9]{10,}', 'brv_[A-Za-z0-9]{10,}']
_SECRET_ENV_NAMES = '(?:API_?KEY|TOKEN|SECRET|PASSWORD|PASSWD|CREDENTIAL|AUTH)'
_JSON_KEY_NAMES = '(?:api_?[Kk]ey|token|secret|password|access_token|refresh_token|auth_token|bearer|secret_value|raw_secret|secret_input|key_material)'
def _mask_token(token: str) -> str:
    ...

def redact_sensitive_text(text: str) -> str:
    ...

class RedactingFormatter:
    def __init__(self: Self, fmt: Any, datefmt: Any, style: Any) -> None: ...
    def format(self: Self, record: logging.LogRecord) -> str: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import os
import re