# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
import random
import threading
import time

_jitter_counter = 0
def jittered_backoff(attempt: int) -> float:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import random
import threading
import time