# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional
import json
import logging
import re

_skill_commands: Dict[str, Dict[str, Any]] = {}
def build_plan_path(user_instruction: str) -> Path:
    ...

def _load_skill_payload(skill_identifier: str, task_id: str | None) -> tuple[dict[str, Any], Path | None, str] | None:
    ...

def _inject_skill_config(loaded_skill: dict[str, Any], parts: list[str]) -> None:
    ...

def _build_skill_message(loaded_skill: dict[str, Any], skill_dir: Path | None, activation_note: str, user_instruction: str, runtime_note: str) -> str:
    ...

def scan_skill_commands() -> Dict[str, Dict[str, Any]]:
    ...

def get_skill_commands() -> Dict[str, Dict[str, Any]]:
    ...

def resolve_skill_command_key(command: str) -> Optional[str]:
    ...

def build_skill_invocation_message(cmd_key: str, user_instruction: str, task_id: str | None, runtime_note: str) -> Optional[str]:
    ...

def build_preloaded_skills_prompt(skill_identifiers: list[str], task_id: str | None) -> tuple[str, list[str], list[str]]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import logging
import re
import datetime
import pathlib
import typing
import tools
import tools.skills_tool
import agent
import agent.skill_utils