# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_constants import get_config_path, get_skills_dir
from pathlib import Path
from typing import Any, Dict, List, Set, Tuple
import logging
import os
import re
import sys

PLATFORM_MAP = {'macos': 'darwin', 'linux': 'linux', 'windows': 'win32'}
EXCLUDED_SKILL_DIRS = frozenset(('.git', '.github', '.hub'))
_yaml_load_fn = None
def yaml_load(content: str) -> Any:
    ...

def parse_frontmatter(content: str) -> Tuple[Dict[str, Any], str]:
    ...

def skill_matches_platform(frontmatter: Dict[str, Any]) -> bool:
    ...

def get_disabled_skill_names(platform: str | None) -> Set[str]:
    ...

def _normalize_string_set(values: Any) -> Set[str]:
    ...

def get_external_skills_dirs() -> List[Path]:
    ...

def get_all_skills_dirs() -> List[Path]:
    ...

def extract_skill_conditions(frontmatter: Dict[str, Any]) -> Dict[str, List]:
    ...

def extract_skill_config_vars(frontmatter: Dict[str, Any]) -> List[Dict[str, Any]]:
    ...

def discover_all_skill_config_vars() -> List[Dict[str, Any]]:
    ...

SKILL_CONFIG_PREFIX = 'skills.config'
def _resolve_dotpath(config: Dict[str, Any], dotted_key: str) -> Any:
    ...

def resolve_skill_config_values(config_vars: List[Dict[str, Any]]) -> Dict[str, Any]:
    ...

def extract_skill_description(frontmatter: Dict[str, Any]) -> str:
    ...

def iter_skill_index_files(skills_dir: Path, filename: str) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import os
import re
import sys
import pathlib
import typing
import hermes_constants
import yaml
import gateway
import gateway.session_context
import posixpath