# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from typing import Any, Dict, Optional
from utils import is_truthy_value
import os
import re

_COMPLEX_KEYWORDS = {'debug', 'debugging', 'implement', 'implementation', 'refactor', 'patch', 'traceback', 'stacktrace', 'exception', 'error', 'analyze', 'analysis', 'investigate', 'architecture', 'design', 'compare', 'benchmark', 'optimize', 'optimise', 'review', 'terminal', 'shell', 'tool', 'tools', 'pytest', 'test', 'tests', 'plan', 'planning', 'delegate', 'subagent', 'cron', 'docker', 'kubernetes'}
def _coerce_bool(value: Any, default: bool) -> bool:
    ...

def _coerce_int(value: Any, default: int) -> int:
    ...

def choose_cheap_model_route(user_message: str, routing_config: Optional[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    ...

def resolve_turn_route(user_message: str, routing_config: Optional[Dict[str, Any]], primary: Dict[str, Any]) -> Dict[str, Any]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import os
import re
import typing
import utils
import hermes_cli
import hermes_cli.runtime_provider