# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from agent.prompt_builder import _scan_context_content
from pathlib import Path
from typing import Any, Dict, Optional, Set
from typing_extensions import Self
import logging
import os
import shlex

_HINT_FILENAMES = ['AGENTS.md', 'agents.md', 'CLAUDE.md', 'claude.md', '.cursorrules']
_MAX_HINT_CHARS = 8000
_PATH_ARG_KEYS = {'path', 'file_path', 'workdir'}
_COMMAND_TOOLS = {'terminal'}
_MAX_ANCESTOR_WALK = 5
class SubdirectoryHintTracker:
    def __init__(self: Self, working_dir: Optional[str]) -> None: ...
    def check_tool_call(self: Self, tool_name: str, tool_args: Dict[str, Any]) -> Optional[str]: ...
    def _extract_directories(self: Self, tool_name: str, args: Dict[str, Any]) -> list: ...
    def _add_path_candidate(self: Self, raw_path: str, candidates: Set[Path]) -> Any: ...
    def _extract_paths_from_command(self: Self, cmd: str, candidates: Set[Path]) -> Any: ...
    def _is_valid_subdir(self: Self, path: Path) -> bool: ...
    def _load_hints_for_directory(self: Self, directory: Path) -> Optional[str]: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import os
import shlex
import pathlib
import typing
import agent
import agent.prompt_builder