# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from agent.auxiliary_client import call_llm
from typing import Any, Optional
import logging
import threading

_TITLE_PROMPT = 'Generate a short, descriptive title (3-7 words) for a conversation that starts with the following exchange. The title should capture the main topic or intent. Return ONLY the title text, nothing else. No quotes, no punctuation at the end, no prefixes.'
def generate_title(user_message: str, assistant_response: str, timeout: float) -> Optional[str]:
    ...

def auto_title_session(session_db: Any, session_id: str, user_message: str, assistant_response: str) -> None:
    ...

def maybe_auto_title(session_db: Any, session_id: str, user_message: str, assistant_response: str, conversation_history: list) -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import threading
import typing
import agent
import agent.auxiliary_client