# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from tools.environments.base import BaseEnvironment, _popen_bash
from tools.environments.local import _HERMES_PROVIDER_ENV_BLOCKLIST
from typing import Any, Optional
from typing_extensions import Self
import logging
import os
import re
import shutil
import subprocess
import sys
import uuid

_DOCKER_SEARCH_PATHS = ['/usr/local/bin/docker', '/opt/homebrew/bin/docker', '/Applications/Docker.app/Contents/Resources/bin/docker']
_docker_executable: Optional[str] = None
def _normalize_forward_env_names(forward_env: list[str] | None) -> list[str]:
    ...

def _normalize_env_dict(env: dict | None) -> dict[str, str]:
    ...

def _load_hermes_env_vars() -> dict[str, str]:
    ...

def find_docker() -> Optional[str]:
    ...

_SECURITY_ARGS = ['--cap-drop', 'ALL', '--cap-add', 'DAC_OVERRIDE', '--cap-add', 'CHOWN', '--cap-add', 'FOWNER', '--security-opt', 'no-new-privileges', '--pids-limit', '256', '--tmpfs', '/tmp:rw,nosuid,size=512m', '--tmpfs', '/var/tmp:rw,noexec,nosuid,size=256m', '--tmpfs', '/run:rw,noexec,nosuid,size=64m']
_storage_opt_ok: Optional[bool] = None
def _ensure_docker_available() -> None:
    ...

class DockerEnvironment(BaseEnvironment):
    def __init__(self: Self, image: str, cwd: str, timeout: int, cpu: float, memory: int, disk: int, persistent_filesystem: bool, task_id: str, volumes: list, forward_env: list[str] | None, env: dict | None, network: bool, host_cwd: str, auto_mount_cwd: bool) -> None: ...
    def _build_init_env_args(self: Self) -> list[str]: ...
    def _run_bash(self: Self, cmd_string: str) -> subprocess.Popen: ...
    @staticmethod
    def _storage_opt_supported() -> bool: ...
    def cleanup(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import os
import re
import shutil
import subprocess
import sys
import uuid
import typing
import tools
import tools.environments
import tools.environments.base
import tools.environments.local
import hermes_cli
import hermes_cli.config
import posixpath
import tools.credential_files
import tools.env_passthrough