# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from tools.environments.base import _file_mtime_key
from typing import Any, Callable
from typing_extensions import TypeAlias
import logging
import os
import shlex
import time

_SYNC_INTERVAL_SECONDS = 5.0
_FORCE_SYNC_ENV = 'HERMES_FORCE_FILE_SYNC'
UploadFn: TypeAlias = Callable[[str, str], None]
BulkUploadFn: TypeAlias = Callable[[list[tuple[str, str]]], None]
DeleteFn: TypeAlias = Callable[[list[str]], None]
GetFilesFn: TypeAlias = Callable[[], list[tuple[str, str]]]
def iter_sync_files(container_base: str) -> list[tuple[str, str]]:
    ...

def quoted_rm_command(remote_paths: list[str]) -> str:
    ...

def quoted_mkdir_command(dirs: list[str]) -> str:
    ...

def unique_parent_dirs(files: list[tuple[str, str]]) -> list[str]:
    ...

class FileSyncManager:
    def __init__(self: Self, get_files_fn: GetFilesFn, upload_fn: UploadFn, delete_fn: DeleteFn, sync_interval: float, bulk_upload_fn: BulkUploadFn | None) -> None: ...
    def sync(self: Self) -> None: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import os
import shlex
import time
import pathlib
import typing
import tools
import tools.environments
import tools.environments.base
import tools.credential_files