# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from dataclasses import dataclass
from tools.environments.modal_utils import BaseModalExecutionEnvironment, ModalExecStart, PreparedModalExec
from tools.managed_tool_gateway import resolve_managed_tool_gateway
from typing import Any, Dict, Optional
from typing_extensions import Self
from dataclasses import dataclass
import json
import logging
import os
import requests
import uuid

def _request_timeout_env(name: str, default: float) -> float:
    ...

@dataclass
class _ManagedModalExecHandle:
class ManagedModalEnvironment(BaseModalExecutionEnvironment):
    def __init__(self: Self, image: str, cwd: str, timeout: int, modal_sandbox_kwargs: Optional[Dict[str, Any]], persistent_filesystem: bool, task_id: str) -> None: ...
    def _start_modal_exec(self: Self, prepared: PreparedModalExec) -> ModalExecStart: ...
    def _poll_modal_exec(self: Self, handle: _ManagedModalExecHandle) -> dict | None: ...
    def _cancel_modal_exec(self: Self, handle: _ManagedModalExecHandle) -> None: ...
    def _timeout_result_for_modal(self: Self, timeout: int) -> dict: ...
    def cleanup(self: Self) -> Any: ...
    def _create_sandbox(self: Self) -> str: ...
    def _guard_unsupported_credential_passthrough(self: Self) -> None: ...
    def _request(self: Self, method: str, path: str) -> requests.Response: ...
    def _cancel_exec(self: Self, exec_id: str) -> None: ...
    @staticmethod
    def _coerce_number(value: Any, default: float) -> float: ...
    @staticmethod
    def _format_error(prefix: str, response: requests.Response) -> str: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import __future__
import json
import logging
import os
import requests
import uuid
import dataclasses
import typing
import tools
import tools.environments
import tools.environments.modal_utils
import tools.managed_tool_gateway
import tools.credential_files