# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_constants import get_hermes_home
from pathlib import Path
from tools.environments.base import BaseEnvironment, _ThreadedProcessHandle, _load_json_store, _save_json_store
from tools.environments.file_sync import FileSyncManager, iter_sync_files, quoted_mkdir_command, quoted_rm_command, unique_parent_dirs
from typing import Any, Optional
from typing_extensions import Self
import asyncio
import base64
import io
import logging
import shlex
import tarfile
import threading

_SNAPSHOT_STORE = get_hermes_home() / 'modal_snapshots.json'
_DIRECT_SNAPSHOT_NAMESPACE = 'direct'
def _load_snapshots() -> dict:
    ...

def _save_snapshots(data: dict) -> None:
    ...

def _direct_snapshot_key(task_id: str) -> str:
    ...

def _get_snapshot_restore_candidate(task_id: str) -> tuple[str | None, bool]:
    ...

def _store_direct_snapshot(task_id: str, snapshot_id: str) -> None:
    ...

def _delete_direct_snapshot(task_id: str, snapshot_id: str | None) -> None:
    ...

def _resolve_modal_image(image_spec: Any) -> Any:
    ...

class _AsyncWorker:
    def __init__(self: Self) -> None: ...
    def start(self: Self) -> Any: ...
    def _run_loop(self: Self) -> Any: ...
    def run_coroutine(self: Self, coro: Any, timeout: Any) -> Any: ...
    def stop(self: Self) -> Any: ...

class ModalEnvironment(BaseEnvironment):
    def __init__(self: Self, image: str, cwd: str, timeout: int, modal_sandbox_kwargs: Optional[dict[str, Any]], persistent_filesystem: bool, task_id: str) -> None: ...
    def _modal_upload(self: Self, host_path: str, remote_path: str) -> None: ...
    def _modal_bulk_upload(self: Self, files: list[tuple[str, str]]) -> None: ...
    def _modal_delete(self: Self, remote_paths: list[str]) -> None: ...
    def _before_execute(self: Self) -> None: ...
    def _run_bash(self: Self, cmd_string: str) -> Any: ...
    def cleanup(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import base64
import io
import logging
import shlex
import tarfile
import threading
import pathlib
import typing
import hermes_constants
import tools
import tools.environments
import tools.environments.base
import tools.environments.file_sync
import tools.credential_files