# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_constants import get_hermes_home
from pathlib import Path
from tools.environments.base import BaseEnvironment, _load_json_store, _popen_bash, _save_json_store
from typing import Any, Optional
from typing_extensions import Self
import logging
import os
import shutil
import subprocess
import threading
import uuid

_SNAPSHOT_STORE = get_hermes_home() / 'singularity_snapshots.json'
def _find_singularity_executable() -> str:
    ...

def _ensure_singularity_available() -> str:
    ...

def _load_snapshots() -> dict:
    ...

def _save_snapshots(data: dict) -> None:
    ...

def _get_scratch_dir() -> Path:
    ...

def _get_apptainer_cache_dir() -> Path:
    ...

def _get_or_build_sif(image: str, executable: str) -> str:
    ...

class SingularityEnvironment(BaseEnvironment):
    def __init__(self: Self, image: str, cwd: str, timeout: int, cpu: float, memory: int, disk: int, persistent_filesystem: bool, task_id: str) -> None: ...
    def _start_instance(self: Self) -> Any: ...
    def _run_bash(self: Self, cmd_string: str) -> subprocess.Popen: ...
    def cleanup(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import os
import shutil
import subprocess
import threading
import uuid
import pathlib
import typing
import hermes_constants
import tools
import tools.environments
import tools.environments.base
import tools.credential_files