# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from tools.environments.base import BaseEnvironment, _popen_bash
from tools.environments.file_sync import FileSyncManager, iter_sync_files, quoted_mkdir_command, quoted_rm_command, unique_parent_dirs
from typing import Any
from typing_extensions import Self
import logging
import os
import shlex
import shutil
import subprocess
import tempfile

def _ensure_ssh_available() -> None:
    ...

class SSHEnvironment(BaseEnvironment):
    def __init__(self: Self, host: str, user: str, cwd: str, timeout: int, port: int, key_path: str) -> None: ...
    def _build_ssh_command(self: Self, extra_args: list | None) -> list: ...
    def _establish_connection(self: Self) -> Any: ...
    def _detect_remote_home(self: Self) -> str: ...
    def _ensure_remote_dirs(self: Self) -> None: ...
    def _scp_upload(self: Self, host_path: str, remote_path: str) -> None: ...
    def _ssh_bulk_upload(self: Self, files: list[tuple[str, str]]) -> None: ...
    def _ssh_delete(self: Self, remote_paths: list[str]) -> None: ...
    def _before_execute(self: Self) -> None: ...
    def _run_bash(self: Self, cmd_string: str) -> subprocess.Popen: ...
    def cleanup(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import os
import shlex
import shutil
import subprocess
import tempfile
import pathlib
import tools
import tools.environments
import tools.environments.base
import tools.environments.file_sync
import posixpath