# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
import hashlib
import logging
import math
import numpy
import struct

_HAS_NUMPY = True
_HAS_NUMPY = False
_TWO_PI = 2.0 * math.pi
def _require_numpy() -> None:
    ...

def encode_atom(word: str, dim: int) -> 'np.ndarray':
    ...

def bind(a: 'np.ndarray', b: 'np.ndarray') -> 'np.ndarray':
    ...

def unbind(memory: 'np.ndarray', key: 'np.ndarray') -> 'np.ndarray':
    ...

def bundle() -> 'np.ndarray':
    ...

def similarity(a: 'np.ndarray', b: 'np.ndarray') -> float:
    ...

def encode_text(text: str, dim: int) -> 'np.ndarray':
    ...

def encode_fact(content: str, entities: list[str], dim: int) -> 'np.ndarray':
    ...

def phases_to_bytes(phases: 'np.ndarray') -> bytes:
    ...

def bytes_to_phases(data: bytes) -> 'np.ndarray':
    ...

def snr_estimate(dim: int, n_items: int) -> float:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import hashlib
import logging
import struct
import math
import numpy