# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from hermes_cli.config import get_hermes_home
from typing import Any, Dict, List, Optional
from utils import atomic_json_write
import json
import logging

DIRECTORY_PATH = get_hermes_home() / 'channel_directory.json'
def _normalize_channel_query(value: str) -> str:
    ...

def _channel_target_name(platform_name: str, channel: Dict[str, Any]) -> str:
    ...

def _session_entry_id(origin: Dict[str, Any]) -> Optional[str]:
    ...

def _session_entry_name(origin: Dict[str, Any]) -> str:
    ...

def build_channel_directory(adapters: Dict[Any, Any]) -> Dict[str, Any]:
    ...

def _build_discord(adapter: Any) -> List[Dict[str, str]]:
    ...

def _build_slack(adapter: Any) -> List[Dict[str, str]]:
    ...

def _build_from_sessions(platform_name: str) -> List[Dict[str, str]]:
    ...

def load_directory() -> Dict[str, Any]:
    ...

def resolve_channel_name(platform_name: str, name: str) -> Optional[str]:
    ...

def format_directory_for_display() -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import logging
import datetime
import typing
import hermes_cli
import hermes_cli.config
import utils
import gateway
import gateway.config
import discord
import tools
import tools.send_message_tool