# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from config import GatewayConfig, Platform
from dataclasses import dataclass
from datetime import datetime
from hermes_cli.config import get_hermes_home
from pathlib import Path
from session import SessionSource
from typing import Any, Dict, List, Optional, Union
from typing_extensions import Self
from dataclasses import dataclass
import logging

MAX_PLATFORM_OUTPUT = 4000
TRUNCATED_VISIBLE = 3800
@dataclass
class DeliveryTarget:
    @classmethod
    def parse(cls, target: str, origin: Optional[SessionSource]) -> 'DeliveryTarget': ...
    def to_string(self: Self) -> str: ...

class DeliveryRouter:
    def __init__(self: Self, config: GatewayConfig, adapters: Dict[Platform, Any]) -> None: ...
    def _deliver_local(self: Self, content: str, job_id: Optional[str], job_name: Optional[str], metadata: Optional[Dict[str, Any]]) -> Dict[str, Any]: ...
    def _save_full_output(self: Self, content: str, job_id: str) -> Path: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import logging
import pathlib
import datetime
import dataclasses
import typing
import hermes_cli
import hermes_cli.config