# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_cli.config import get_hermes_home
from typing import Any, Callable, Dict, List, Optional
from typing_extensions import Self
import asyncio
import importlib.util
import yaml

HOOKS_DIR = get_hermes_home() / 'hooks'
class HookRegistry:
    def __init__(self: Self) -> None: ...
    def loaded_hooks(self: Self) -> List[dict]: ...
    def _register_builtin_hooks(self: Self) -> None: ...
    def discover_and_load(self: Self) -> None: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import importlib
import importlib.util
import typing
import yaml
import hermes_cli
import hermes_cli.config
import gateway
import gateway.builtin_hooks
import gateway.builtin_hooks.boot_md