# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from hermes_cli.config import get_hermes_home
from typing import Optional
import json
import logging

_SESSIONS_DIR = get_hermes_home() / 'sessions'
_SESSIONS_INDEX = _SESSIONS_DIR / 'sessions.json'
def mirror_to_session(platform: str, chat_id: str, message_text: str, source_label: str, thread_id: Optional[str]) -> bool:
    ...

def _find_session_id(platform: str, chat_id: str, thread_id: Optional[str]) -> Optional[str]:
    ...

def _append_to_jsonl(session_id: str, message: dict) -> None:
    ...

def _append_to_sqlite(session_id: str, message: dict) -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import logging
import datetime
import typing
import hermes_cli
import hermes_cli.config
import hermes_state