# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from agent.redact import RedactingFormatter
from datetime import datetime
from dotenv import load_dotenv
from gateway.config import GatewayConfig, Platform, load_gateway_config
from gateway.delivery import DeliveryRouter
from gateway.platforms.base import BasePlatformAdapter, MessageEvent, MessageType, merge_pending_message_event
from gateway.restart import DEFAULT_GATEWAY_RESTART_DRAIN_TIMEOUT, GATEWAY_SERVICE_RESTART_EXIT_CODE, parse_restart_drain_timeout
from gateway.session import SessionContext, SessionSource, SessionStore, build_session_context, build_session_context_prompt, build_session_key
from gateway.status import get_running_pid, release_all_scoped_locks, remove_pid_file, terminate_pid, write_pid_file
from hermes_cli.config import _expand_env_vars, print_config_warnings
from hermes_cli.env_loader import load_hermes_dotenv
from hermes_constants import apply_ipv4_preference, get_hermes_home
from hermes_logging import setup_logging
from pathlib import Path
from tools.mcp_tool import shutdown_mcp_servers
from tools.skills_sync import sync_skills
from typing import Any, Dict, List, Optional
from typing_extensions import TypeAlias
from utils import atomic_yaml_write, is_truthy_value
from dataclasses import dataclass
import asyncio
import atexit
import json
import logging
import os
import re
import shlex
import signal
import sys
import tempfile
import threading
import time
import yaml

def _ensure_ssl_certs() -> None:
    ...

_env_path = _hermes_home / '.env'
_config_path = _hermes_home / 'config.yaml'
_cfg = _yaml.safe_load(_f) or {}
_terminal_env_map = {'backend': 'TERMINAL_ENV', 'cwd': 'TERMINAL_CWD', 'timeout': 'TERMINAL_TIMEOUT', 'lifetime_seconds': 'TERMINAL_LIFETIME_SECONDS', 'docker_image': 'TERMINAL_DOCKER_IMAGE', 'docker_forward_env': 'TERMINAL_DOCKER_FORWARD_ENV', 'singularity_image': 'TERMINAL_SINGULARITY_IMAGE', 'modal_image': 'TERMINAL_MODAL_IMAGE', 'daytona_image': 'TERMINAL_DAYTONA_IMAGE', 'ssh_host': 'TERMINAL_SSH_HOST', 'ssh_user': 'TERMINAL_SSH_USER', 'ssh_port': 'TERMINAL_SSH_PORT', 'ssh_key': 'TERMINAL_SSH_KEY', 'container_cpu': 'TERMINAL_CONTAINER_CPU', 'container_memory': 'TERMINAL_CONTAINER_MEMORY', 'container_disk': 'TERMINAL_CONTAINER_DISK', 'container_persistent': 'TERMINAL_CONTAINER_PERSISTENT', 'docker_volumes': 'TERMINAL_DOCKER_VOLUMES', 'sandbox_dir': 'TERMINAL_SANDBOX_DIR', 'persistent_shell': 'TERMINAL_PERSISTENT_SHELL'}
_val: TypeAlias = _terminal_cfg[_cfg_key]
_aux_task_env = {'vision': {'provider': 'AUXILIARY_VISION_PROVIDER', 'model': 'AUXILIARY_VISION_MODEL', 'base_url': 'AUXILIARY_VISION_BASE_URL', 'api_key': 'AUXILIARY_VISION_API_KEY'}, 'web_extract': {'provider': 'AUXILIARY_WEB_EXTRACT_PROVIDER', 'model': 'AUXILIARY_WEB_EXTRACT_MODEL', 'base_url': 'AUXILIARY_WEB_EXTRACT_BASE_URL', 'api_key': 'AUXILIARY_WEB_EXTRACT_API_KEY'}, 'approval': {'provider': 'AUXILIARY_APPROVAL_PROVIDER', 'model': 'AUXILIARY_APPROVAL_MODEL', 'base_url': 'AUXILIARY_APPROVAL_BASE_URL', 'api_key': 'AUXILIARY_APPROVAL_API_KEY'}}
messaging_cwd = os.getenv('MESSAGING_CWD') or str(Path.home())
def _normalize_whatsapp_identifier(value: str) -> str:
    ...

def _expand_whatsapp_auth_aliases(identifier: str) -> set:
    ...

def _resolve_runtime_agent_kwargs() -> dict:
    ...

def _build_media_placeholder(event: Any) -> str:
    ...

def _dequeue_pending_event(adapter: Any, session_key: str) -> MessageEvent | None:
    ...

def _check_unavailable_skill(command_name: str) -> str | None:
    ...

def _platform_config_key(platform: 'Platform') -> str:
    ...

def _load_gateway_config() -> dict:
    ...

def _resolve_gateway_model(config: dict | None) -> str:
    ...

def _resolve_hermes_bin() -> Optional[list[str]]:
    ...

def _format_gateway_process_notification(evt: dict) -> 'str | None':
    ...

@dataclass
class GatewayRunner:
    def __init__(self: Self, config: Optional[GatewayConfig]) -> None: ...
    def _has_setup_skill(self: Self) -> bool: ...
    def _load_voice_modes(self: Self) -> Dict[str, str]: ...
    def _save_voice_modes(self: Self) -> None: ...
    def _set_adapter_auto_tts_disabled(self: Self, adapter: Any, chat_id: str, disabled: bool) -> None: ...
    def _sync_voice_mode_state_to_adapter(self: Self, adapter: Any) -> None: ...
    def _flush_memories_for_session(self: Self, old_session_id: str, session_key: Optional[str]) -> Any: ...
    def should_exit_cleanly(self: Self) -> bool: ...
    def should_exit_with_failure(self: Self) -> bool: ...
    def exit_reason(self: Self) -> Optional[str]: ...
    def exit_code(self: Self) -> Optional[int]: ...
    def _session_key_for_source(self: Self, source: SessionSource) -> str: ...
    def _resolve_session_agent_runtime(self: Self) -> tuple[str, dict]: ...
    def _resolve_turn_agent_config(self: Self, user_message: str, model: str, runtime_kwargs: dict) -> dict: ...
    def _request_clean_exit(self: Self, reason: str) -> None: ...
    def _running_agent_count(self: Self) -> int: ...
    def _status_action_label(self: Self) -> str: ...
    def _status_action_gerund(self: Self) -> str: ...
    def _queue_during_drain_enabled(self: Self) -> bool: ...
    def _update_runtime_status(self: Self, gateway_state: Optional[str], exit_reason: Optional[str]) -> None: ...
    def _update_platform_runtime_status(self: Self, platform: str) -> None: ...
    @staticmethod
    def _load_prefill_messages() -> List[Dict[str, Any]]: ...
    @staticmethod
    def _load_ephemeral_system_prompt() -> str: ...
    @staticmethod
    def _load_reasoning_config() -> dict | None: ...
    @staticmethod
    def _load_service_tier() -> str | None: ...
    @staticmethod
    def _load_show_reasoning() -> bool: ...
    @staticmethod
    def _load_busy_input_mode() -> str: ...
    @staticmethod
    def _load_restart_drain_timeout() -> float: ...
    @staticmethod
    def _load_background_notifications_mode() -> str: ...
    @staticmethod
    def _load_provider_routing() -> dict: ...
    @staticmethod
    def _load_fallback_model() -> list | dict | None: ...
    @staticmethod
    def _load_smart_model_routing() -> dict: ...
    def _snapshot_running_agents(self: Self) -> Dict[str, Any]: ...
    def _queue_or_replace_pending_event(self: Self, session_key: str, event: MessageEvent) -> None: ...
    def _interrupt_running_agents(self: Self, reason: str) -> None: ...
    def _finalize_shutdown_agents(self: Self, active_agents: Dict[str, Any]) -> None: ...
    def request_restart(self: Self) -> bool: ...
    def _create_adapter(self: Self, platform: Platform, config: Any) -> Optional[BasePlatformAdapter]: ...
    def _is_user_authorized(self: Self, source: SessionSource) -> bool: ...
    def _get_unauthorized_dm_behavior(self: Self, platform: Optional[Platform]) -> str: ...
    def _format_session_info(self: Self) -> str: ...
    @staticmethod
    def _get_guild_id(event: MessageEvent) -> Optional[int]: ...
    def _handle_voice_timeout_cleanup(self: Self, chat_id: str) -> None: ...
    def _should_send_voice_reply(self: Self, event: MessageEvent, response: str, agent_messages: list, already_sent: bool) -> bool: ...
    def _schedule_update_notification_watch(self: Self) -> None: ...
    def _set_session_env(self: Self, context: SessionContext) -> list: ...
    def _clear_session_env(self: Self, tokens: list) -> None: ...
    @staticmethod
    def _agent_config_signature(model: str, runtime: dict, enabled_toolsets: list, ephemeral_prompt: str) -> str: ...
    def _apply_session_model_override(self: Self, session_key: str, model: str, runtime_kwargs: dict) -> tuple: ...
    def _is_intentional_model_switch(self: Self, session_key: str, agent_model: str) -> bool: ...
    def _evict_cached_agent(self: Self, session_key: str) -> None: ...

def _start_cron_ticker(stop_event: threading.Event, adapters: Any, loop: Any, interval: int) -> Any:
    ...

def shutdown_signal_handler() -> Any:
    ...

def restart_signal_handler() -> Any:
    ...

success = await runner.start()
def main() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import json
import logging
import os
import re
import shlex
import sys
import signal
import tempfile
import threading
import time
import pathlib
import datetime
import typing
import ssl
import certifi
import hermes_constants
import utils
import dotenv
import dotenv.load_dotenv
import hermes_cli
import hermes_cli.env_loader
import yaml
import hermes_cli.config
import gateway
import gateway.config
import gateway.session
import gateway.delivery
import gateway.platforms
import gateway.platforms.base
import gateway.restart
import hermes_cli.runtime_provider
import tools
import tools.skills_tool
import agent
import agent.skill_utils
import shutil
import importlib
import importlib.util
import tools.process_registry
import tools.tirith_security
import hermes_state
import gateway.pairing
import gateway.hooks
import tools.skill_manager_tool
import run_agent
import tools.memory_tool
import hermes_cli.models
import agent.smart_model_routing
import gateway.status
import hermes_cli.plugins
import subprocess
import hermes_cli.profiles
import gateway.channel_directory
import tools.terminal_tool
import tools.browser_tool
import gateway.platforms.telegram
import gateway.platforms.discord
import gateway.platforms.whatsapp
import gateway.platforms.slack
import gateway.platforms.signal
import gateway.platforms.homeassistant
import gateway.platforms.email
import gateway.platforms.sms
import gateway.platforms.dingtalk
import gateway.platforms.feishu
import gateway.platforms.wecom_callback
import gateway.platforms.wecom
import gateway.platforms.weixin
import gateway.platforms.mattermost
import gateway.platforms.matrix
import gateway.platforms.api_server
import gateway.platforms.webhook
import gateway.platforms.bluebubbles
import hermes_cli.commands
import agent.skill_commands
import mimetypes
import posixpath
import agent.context_references
import agent.model_metadata
import gateway.display_config
import math
import tools.env_passthrough
import tools.credential_files
import hermes_cli.tips
import hermes_cli.model_switch
import hermes_cli.providers
import hermes_cli.auth
import types
import uuid
import tools.tts_tool
import tools.checkpoint_manager
import hermes_cli.tools_config
import tools.approval
import agent.manual_compression_feedback
import agent.rate_limit_tracker
import agent.usage_pricing
import agent.insights
import tools.mcp_tool
import hermes_cli.debug
import gateway.session_context
import tools.vision_tools
import tools.transcription_tools
import tools.ansi_strip
import hashlib
import queue
import agent.display
import gateway.stream_consumer
import agent.title_generator
import cron
import cron.scheduler
import tools.skills_sync
import hermes_logging
import agent.redact
import atexit
import argparse