# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from contextvars import ContextVar

_SESSION_PLATFORM: ContextVar[str] = ContextVar('HERMES_SESSION_PLATFORM', default='')
_SESSION_CHAT_ID: ContextVar[str] = ContextVar('HERMES_SESSION_CHAT_ID', default='')
_SESSION_CHAT_NAME: ContextVar[str] = ContextVar('HERMES_SESSION_CHAT_NAME', default='')
_SESSION_THREAD_ID: ContextVar[str] = ContextVar('HERMES_SESSION_THREAD_ID', default='')
_SESSION_USER_ID: ContextVar[str] = ContextVar('HERMES_SESSION_USER_ID', default='')
_SESSION_USER_NAME: ContextVar[str] = ContextVar('HERMES_SESSION_USER_NAME', default='')
_SESSION_KEY: ContextVar[str] = ContextVar('HERMES_SESSION_KEY', default='')
_VAR_MAP = {'HERMES_SESSION_PLATFORM': _SESSION_PLATFORM, 'HERMES_SESSION_CHAT_ID': _SESSION_CHAT_ID, 'HERMES_SESSION_CHAT_NAME': _SESSION_CHAT_NAME, 'HERMES_SESSION_THREAD_ID': _SESSION_THREAD_ID, 'HERMES_SESSION_USER_ID': _SESSION_USER_ID, 'HERMES_SESSION_USER_NAME': _SESSION_USER_NAME, 'HERMES_SESSION_KEY': _SESSION_KEY}
def set_session_vars(platform: str, chat_id: str, chat_name: str, thread_id: str, user_id: str, user_name: str, session_key: str) -> list:
    ...

def clear_session_vars(tokens: list) -> None:
    ...

def get_session_env(name: str, default: str) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import contextvars
import os