# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime, timezone
from hermes_constants import get_hermes_home
from pathlib import Path
from typing import Any, Optional
import hashlib
import json
import os
import signal
import subprocess
import sys

_GATEWAY_KIND = 'hermes-gateway'
_RUNTIME_STATUS_FILE = 'gateway_state.json'
_LOCKS_DIRNAME = 'gateway-locks'
_IS_WINDOWS = sys.platform == 'win32'
def _get_pid_path() -> Path:
    ...

def _get_runtime_status_path() -> Path:
    ...

def _get_lock_dir() -> Path:
    ...

def _utc_now_iso() -> str:
    ...

def terminate_pid(pid: int) -> None:
    ...

def _scope_hash(identity: str) -> str:
    ...

def _get_scope_lock_path(scope: str, identity: str) -> Path:
    ...

def _get_process_start_time(pid: int) -> Optional[int]:
    ...

def _read_process_cmdline(pid: int) -> Optional[str]:
    ...

def _looks_like_gateway_process(pid: int) -> bool:
    ...

def _record_looks_like_gateway(record: dict[str, Any]) -> bool:
    ...

def _build_pid_record() -> dict:
    ...

def _build_runtime_status_record() -> dict[str, Any]:
    ...

def _read_json_file(path: Path) -> Optional[dict[str, Any]]:
    ...

def _write_json_file(path: Path, payload: dict[str, Any]) -> None:
    ...

def _read_pid_record() -> Optional[dict]:
    ...

def write_pid_file() -> None:
    ...

def write_runtime_status() -> None:
    ...

def read_runtime_status() -> Optional[dict[str, Any]]:
    ...

def remove_pid_file() -> None:
    ...

def acquire_scoped_lock(scope: str, identity: str, metadata: Optional[dict[str, Any]]) -> tuple[bool, Optional[dict[str, Any]]]:
    ...

def release_scoped_lock(scope: str, identity: str) -> None:
    ...

def release_all_scoped_locks() -> int:
    ...

def get_running_pid() -> Optional[int]:
    ...

def is_gateway_running() -> bool:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import hashlib
import json
import os
import signal
import subprocess
import sys
import datetime
import pathlib
import hermes_constants
import typing