# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from hermes_cli.config import get_hermes_home
from typing import Optional
import json
import time

CACHE_PATH = get_hermes_home() / 'sticker_cache.json'
STICKER_VISION_PROMPT = 'Describe this sticker in 1-2 sentences. Focus on what it depicts -- character, action, emotion. Be concise and objective.'
def _load_cache() -> dict:
    ...

def _save_cache(cache: dict) -> None:
    ...

def get_cached_description(file_unique_id: str) -> Optional[dict]:
    ...

def cache_sticker_description(file_unique_id: str, description: str, emoji: str, set_name: str) -> None:
    ...

def build_sticker_injection(description: str, emoji: str, set_name: str) -> str:
    ...

def build_animated_sticker_injection(emoji: str) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import time
import typing
import hermes_cli
import hermes_cli.config